feat: backup and restore flow dialogs
wireapp/wire-android pull request #1098
Opened 2022-10-14 11:23 UTC by trOnk12

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-10-17 14:30 UTC, AndroidBob commented
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1098/2/) **failed**.

2022-10-17 20:49 UTC, gongracr requested changes
Impressive effort 👏  I added some small comments, mostly about code formatting, avoiding hardcoded strings and one related with the progress bar not taking the full width of the dialog.

2022-10-17 20:49 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
> +                context.startActivity(Intent.createChooser(intent, "Choose an Email client: "))
I'm not sure how long we want to keep this send feedback option, but I guess it wouldn't harm to add it as a string key and not hardcode the value, even if it's slightly out of the scope of this PR?

2022-10-17 20:49 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/details/AddMembersToConversationViewModel.kt
> +    //            }
Why did you comment these lines? I believe this is out of the scope of this PR. Also it could create undesired code conflicts when merged with develop later on if anyone else works on fixing this.

2022-10-17 20:49 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackUpAndRestoreStateHolder.kt
> +    object Restore : BackupAndRestoreDialog()
Not sure if these values imply current state of the backup process or simply type of dialog state. I guess it's the latter one, so for more clarity can we rename these to:
```suggestion
    object CreateBackup : BackupAndRestoreDialog()
    object RestoreBackup : BackupAndRestoreDialog()
```

2022-10-17 20:49 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreScreen.kt
> +fun RestoreDialogFlow(
For coherence with the other method, can we rename to `RestoreBackupDialogFlow` ?

2022-10-17 20:49 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogStateHolder.kt
> +    fun toCreateBackUp() {
Could get confusing with Up as in going Up in the stack 😅 so maybe make it lowercase.
```suggestion
    fun toCreateBackup() {
```

2022-10-17 20:49 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogStateHolder.kt
> +    GeneralFailure("Something Went Wrong", "Your history could not be restored. Please try again or contact the Wire customer support.")
Even if their values are still not confirmed, let's move these strings to xml file instead of hardcoding them.

2022-10-17 20:49 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogs.kt
> +            text = "Choose Backup File",
Localize string pls.

2022-10-17 20:49 UTC, gongracr commented on app/src/main/res/values/strings.xml
> +    <string name="label_sacing_conversations">Saving conversations</string>
Typo
```suggestion
    <string name="label_saving_conversations">Saving conversations</string>
```

2022-10-17 20:49 UTC, gongracr commented on app/src/main/res/values/strings.xml
> +    <string name="dialog_restore_backup_password_message">This backup is password protected.</string>
Can we prefix all these strings with `backup_xxx_` and maybe add a section divider comment to indicate they all belong to backup screens? Prefixing them that way will definitely help content creators and volunteer translators to identify content before translating.

2022-10-17 20:49 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreScreen.kt
> +                            backupDialogStateHolder.backupProgress = progress.progress
Maybe rename to `value` to avoid double `progress.progress` 😅 ?

2022-10-17 20:49 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
> +            LinearProgressIndicator(progress = createBackupProgress)
On the GIF shared, it seems the linear progress indicator doesn't take all the available width so maybe check what is going on, so that we avoid a design regression issue 😉

2022-10-19 21:30 UTC, AndroidBob commented
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1098/5/) **failed**.

2022-10-21 09:38 UTC, AndroidBob commented
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1098/6/) **failed**.

2022-10-21 10:20 UTC, AndroidBob commented
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1098/7/) **failed**.

2022-11-07 14:58 UTC, ohassine commented
I am wondering why we are doing the migration here in Reloaded repository. I think it should be in kalium as it belongs to Data layer.
We are breaking our architecture this way
https://wearezeta.atlassian.net/wiki/spaces/AR/pages/122618158/Technical+Documentation

2022-11-08 09:23 UTC, trOnk12 commented
> I am wondering why we are doing the migration here in Reloaded repository. I think it should be in kalium as it belongs to Data layer. We are breaking our architecture this way https://wearezeta.atlassian.net/wiki/spaces/AR/pages/122618158/Technical+Documentation

I am not sure what you mean, in AR we will only have the UI that helps the user to restore the backup-up there is also some work being done on Kalium side

2022-11-08 10:43 UTC, AndroidBob commented
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1098/8/) **failed**.

2022-11-08 11:02 UTC, AndroidBob commented
Build [9](https://10.10.124.134/job/wire-android-reloaded/job/PR-1098/9/) **failed**.

2022-11-08 15:59 UTC, AndroidBob commented
Build [10](https://10.10.124.134/job/wire-android-reloaded/job/PR-1098/10/) **failed**.

2022-11-08 16:09 UTC, AndroidBob commented
Build [11](https://10.10.124.134/job/wire-android-reloaded/job/PR-1098/11/) **failed**.

2022-11-10 09:33 UTC, AndroidBob commented
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-1098/12/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4910514)(4910514)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4910514)(4910514)-dev-release.apk)

2022-11-10 13:24 UTC, AndroidBob commented
Build [13](https://10.10.124.134/job/wire-android-reloaded/job/PR-1098/13/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4911912)(4911912)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4911912)(4911912)-dev-release.apk)

2022-11-10 17:23 UTC, AndroidBob commented
Build [16](https://10.10.124.134/job/wire-android-reloaded/job/PR-1098/16/) **failed**.

2022-11-11 12:05 UTC, AndroidBob commented
Build [17](https://10.10.124.134/job/wire-android-reloaded/job/PR-1098/17/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4920072)(4920072)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4920072)(4920072)-dev-release.apk)

2022-11-11 16:33 UTC, merged