fix: duplicate heart emojis [AR-2661]
wireapp/wire-android pull request #1140
Opened 2022-11-04 09:40 UTC by Garzas

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Because current web and iOS don't handle other emojis than the heart so we need temporarily disable other emojis. 
Also, we need to merge different hearts emojis into one, because other platforms are using an ugly ones 😅 
 "❤️" ❤"

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-11-04 09:49 UTC, AndroidBob commented
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1140/1/) **failed**.

2022-11-04 10:24 UTC, vitorhugods requested changes
Just tiny suggestions to reduce the code a bit.

Nicely done.

2022-11-04 10:24 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
> +                .lastOrNull()
Kotlin's stdlib has a [sumOf](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/sum-of.html) and for collections of numbers, [sum](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/sum.html) also exists to make things simpler.

```suggestion
                .sum()
```

2022-11-04 10:24 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
> +                        if (totalHeartsCount != null && totalHeartsCount != 0)
With the suggestion above, totalHeartCount is no longer nullable.
```suggestion
                        if (totalHeartsCount != 0)
```

2022-11-09 19:55 UTC, AndroidBob commented
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1140/2/) **failed**.

2022-11-09 20:08 UTC, vitorhugods approved these changes
👨‍🍳🤌

2022-11-09 20:12 UTC, AndroidBob commented
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1140/3/) **failed**.

2022-11-10 19:38 UTC, AndroidBob commented
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1140/4/) **failed**.

2022-11-11 12:13 UTC, AndroidBob commented
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1140/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4920126)(4920126)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4920126)(4920126)-dev-release.apk)

2022-11-14 08:59 UTC, merged