Fix/slow message insert from scala
wireapp/wire-android pull request #1402
Opened 2023-01-29 20:07 UTC by MohamadJaara

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-01-29 20:16 UTC, AndroidBob commented
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1402/1/) **failed**.

2023-01-29 20:44 UTC, AndroidBob commented
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1402/2/) **failed**.

2023-01-29 21:14 UTC, AndroidBob commented
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1402/3/) **failed**.

2023-01-29 21:35 UTC, AndroidBob commented
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1402/4/) **failed**.

2023-01-29 21:57 UTC, AndroidBob commented
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1402/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5606203)(5606203)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5606203)(5606203)-dev-compat.apk)

2023-01-30 10:42 UTC, AndroidBob commented
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1402/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5610793)(5610793)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5610793)(5610793)-dev-compat.apk)

2023-01-30 11:51 UTC, AndroidBob commented
Build [10](https://10.10.124.134/job/wire-android-reloaded/job/PR-1402/10/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5611202)(5611202)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5611202)(5611202)-dev-compat.apk)

2023-01-30 14:16 UTC, AndroidBob commented
Build [11](https://10.10.124.134/job/wire-android-reloaded/job/PR-1402/11/) **failed**.

2023-01-30 14:54 UTC, AndroidBob commented
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-1402/12/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5612299)(5612299)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5612299)(5612299)-dev-compat.apk)

2023-01-30 16:34 UTC, vitorhugods requested changes
A couple of suggestions to simplify the code a bit, but looks good in general :)

2023-01-30 16:34 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/migration/feature/MigrateClientsDataUseCase.kt
There are no usages of `invoke` with a list. We can simplify the code by removing it and the loop thingy.

2023-01-30 16:34 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/migration/feature/MigrateConversationsUseCase.kt
> +        invoke(listOf(userId)).map { it[userId] ?: listOf() }
Same here

2023-01-30 16:34 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/migration/feature/MigrateMessagesUseCase.kt
> +    suspend operator fun invoke(
And here

2023-01-30 16:34 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/migration/feature/MigrateUsersUseCase.kt
> +        invoke(listOf(userId)).map { userId }
Anotha one

2023-01-30 16:34 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/migration/userDatabase/ScalaMessageDAO.kt
> +            messagesFromConversation(scalaConversation)
```suggestion
```

Not being used

2023-01-30 16:34 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
> +                        appLogger.d("$TAG - Step 4 - Migrating conversations for $userid")
```suggestion
                        appLogger.d("$TAG - Step 4 - Migrating conversations for $userid")
                        migrateConversations(it)
                    }.flatMap {
                        appLogger.d("$TAG - Step 5 - Migrating messages for $userid")
```

2023-01-30 17:32 UTC, vitorhugods approved these changes

2023-01-30 17:50 UTC, AndroidBob commented
Build [15](https://10.10.124.134/job/wire-android-reloaded/job/PR-1402/15/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5613355)(5613355)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5613355)(5613355)-dev-compat.apk)

2023-01-30 18:10 UTC, merged

2023-01-30 18:17 UTC, AndroidBob commented
Build [16](https://10.10.124.134/job/wire-android-reloaded/job/PR-1402/16/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5613518)(5613518)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5613518)(5613518)-dev-compat.apk)