feat: epic user client verificarion other user clients
wireapp/wire-android pull request #1559
Opened 2023-03-17 11:00 UTC by borichellow

# What's new in this PR?

- opening DeviceScreen from OtherUserProfile
- additional changes to finish the feature 
- merged with `develop`
- updated kalium version to https://github.com/wireapp/kalium/pull/1544

https://user-images.githubusercontent.com/6539347/225886230-c311deb1-ecfd-45d2-8ad2-80d80b6bfcc2.mp4

2023-03-17 11:19 UTC, AndroidBob commented
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1559/2/) **failed**.

2023-03-17 12:06 UTC, AndroidBob commented
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1559/3/) **failed**.

2023-03-17 12:52 UTC, AndroidBob commented
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1559/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.2(6008990)(6008990)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.2(6008990)(6008990)-staging-compat.apk)

2023-03-18 09:04 UTC, MohamadJaara commented on app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
> +        VerifyLabel(device.isVerified, Modifier.wrapContentWidth())
The same item is used when encountering too many clients after login and in that case, we do not need to display the VerifyLabel

2023-03-18 09:06 UTC, MohamadJaara requested changes
Looking great as always, we only need to not display the VerifyLabel on the too many clients screen

2023-03-20 12:37 UTC, AndroidBob commented
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1559/5/) **failed**.

2023-03-20 12:49 UTC, MohamadJaara approved these changes

2023-03-20 12:51 UTC, merged

2023-03-20 13:02 UTC, AndroidBob commented
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1559/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.2(6034975)(6034975)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.2(6034975)(6034975)-staging-compat.apk)