fix: call still ringing despite that the caller already ended the call (AR-3046) (RC)
wireapp/wire-android pull request #1592
Opened 2023-03-28 09:42 UTC by ohassine

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Same PR as #1575 to be merged into RC branch

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-03-28 09:59 UTC, AndroidBob commented
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1592/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6102999)(6102999)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6102999)(6102999)-staging-compat.apk)

2023-03-28 15:59 UTC, alexandreferris approved these changes

2023-03-28 16:20 UTC, AndroidBob commented
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1592/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6105275)(6105275)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6105275)(6105275)-staging-compat.apk)

2023-03-29 11:37 UTC, trOnk12 approved these changes

2023-03-29 11:38 UTC, tmspzz requested changes, later dismissed

2023-03-29 11:38 UTC, tmspzz commented on buildSrc/src/main/kotlin/Dependencies.kt
> -        const val workManager = "2.7.1"
Nope, this updates a library

2023-03-29 11:44 UTC, ohassine commented on buildSrc/src/main/kotlin/Dependencies.kt
> -        const val workManager = "2.7.1"
reverted

2023-03-29 12:03 UTC, AndroidBob commented
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1592/5/) **failed**.

2023-03-29 12:42 UTC, AndroidBob commented
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1592/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6112596)(6112596)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6112596)(6112596)-staging-compat.apk)

2023-03-29 16:23 UTC, yamilmedina approved these changes

2023-03-31 13:25 UTC, AndroidBob commented
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1592/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6130144)(6130144)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6130144)(6130144)-staging-compat.apk)

2023-04-05 10:47 UTC, tmspzz approved these changes

2023-04-05 10:50 UTC, merged

2023-04-05 10:58 UTC, AndroidBob commented
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1592/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6172461)(6172461)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6172461)(6172461)-staging-compat.apk)