fix: mention from web [AR-3376]
wireapp/wire-android pull request #1759
Opened 2023-05-05 10:11 UTC by Garzas

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Fixed handling mention from web

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

| Before | After |
| ----------- | ------------ |
| ![before](https://user-images.githubusercontent.com/13151239/236431120-fd6727e5-3f52-4143-9c2c-e61302d93ef4.jpeg) | ![after](https://user-images.githubusercontent.com/13151239/236431157-2dd1f913-879b-4aac-9bbd-9ce417a631df.jpeg) |

2023-05-05 10:17 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
> +                    if (it.length <= 0) {
Can you explain a bit more in detail what was this condition doing?

2023-05-05 10:38 UTC, AndroidBob commented
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1759/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6431489)(6431489)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6431489)(6431489)-staging-compat.apk)

2023-05-05 10:40 UTC, alexandreferris approved these changes
Good catch! But also waiting on a more explanation from Gonzo's comment as well 🙈

2023-05-05 12:35 UTC, MohamadJaara requested changes

2023-05-05 12:35 UTC, MohamadJaara commented on app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
> -                    if (it.length <= 0 || (it.start + it.length) >= textAsString.length) {
this code was added to avoid corrupted messages with mention length is out of range of the message it self

2023-05-05 14:26 UTC, AndroidBob commented
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1759/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6432868)(6432868)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6432868)(6432868)-staging-compat.apk)

2023-05-10 08:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-android-reloaded?pullRequest=1759) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-android-reloaded?pullRequest=1759) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-android-reloaded?pullRequest=1759) it.</sub>

2023-05-11 10:47 UTC, AndroidBob commented
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1759/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6483376)(6483376)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6483376)(6483376)-staging-compat.apk)

2023-05-11 20:44 UTC, MohamadJaara approved these changes, later dismissed

2023-05-12 08:14 UTC, MohamadJaara commented on app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
>                          start = it.start,
can we also make sure that start is not outside the limit of the text length?

2023-05-12 09:07 UTC, AndroidBob commented
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1759/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6491417)(6491417)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6491417)(6491417)-staging-compat.apk)

2023-05-12 09:46 UTC, MohamadJaara approved these changes

2023-05-12 09:50 UTC, AndroidBob commented
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1759/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6491686)(6491686)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6491686)(6491686)-staging-compat.apk)

2023-05-12 09:54 UTC, gongracr approved these changes
LGTM 🍬

2023-05-12 11:53 UTC, merged