feat: Service / Bots Integration (AR-3319)
wireapp/wire-android pull request #1767
Opened 2023-05-09 12:39 UTC by alexandreferris

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3319" title="AR-3319" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-3319</a>  View services as group participant (non admin)
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] contains a reference JIRA issue number like `SQPIT-764`
    - [ X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

There was no way to handle Service Details, addition and removal from a group conversation.

### Solutions

Create Service Details Screen and handle adding, removing and if it ever happens: an empty Service details.

### Dependencies (Optional)

Needs releases with:

- [X] [#1689](https://github.com/wireapp/kalium/pull/1689)
- [X] [#1690](https://github.com/wireapp/kalium/pull/1690)
- [X] [#1691](https://github.com/wireapp/kalium/pull/1691)
- [X] [#1693](https://github.com/wireapp/kalium/pull/1693)
- [X] [#1703](https://github.com/wireapp/kalium/pull/1703)
- [X] [#1705](https://github.com/wireapp/kalium/pull/1705)
- [X] [#1712](https://github.com/wireapp/kalium/pull/1712)
- [X] [#1719](https://github.com/wireapp/kalium/pull/1719)

### Testing

#### Test Coverage (Optional)

- [X] I have added automated test to this contribution

#### How to Test

#---- Service Details -----#
- Open App
- Open Group Conversation that contains a bot/service
- Open Conversation Details
- Go to Participants Tab
- Select a bot/service from the list of participants
- You will be redirected to the Service Details Screen

#---- As an Admin: Add a bot/service -----#
From the Service Details Screen:
- Click `Add To Group`
- Service will be added to group and a snackbar will be shown informing it was added (or an error if it fails)

#---- As an Admin: Remove a bot/service -----#
From the Service Details Screen:
- Click `Remove From Group`
- Service will be removed from group and a snackbar will be shown informing it was removed (or an error if it fails)

### Notes (Optional)

Currently the only way to add a bot is to first remove it from the group, there will be a following up PR containing the flow to add a service from the `Add Participants` flow.

### Attachments (Optional)
| Info | Screenshot |
| ----------- | ------------ |
| Service Not Found / Invalid Information  | <img src="https://github.com/wireapp/wire-android-reloaded/assets/5890660/0e9116cf-e802-4ca3-aced-ec5d0892e994" width="200" height="400" alt="Service Not Found" />  |
| Service Added to Group  | <img src="https://github.com/wireapp/wire-android-reloaded/assets/5890660/d48c0bb3-a53f-4866-b715-739c26ef9852" width="200" height="400" alt="Service Added to Group" />   |
| Service Removed From Group  | <img src="https://github.com/wireapp/wire-android-reloaded/assets/5890660/ea6abe13-0cba-4e7f-9f40-9cc24c706659" width="200" height="400" alt="Service Removed From Group" />   |

2023-05-09 12:45 UTC, MohamadJaara requested changes
nice work, just small comment about avoiding empty strings when mapping

2023-05-09 12:45 UTC, MohamadJaara commented on app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsMapper.kt
> +            else -> ServiceId(id = "", provider = "")
can we avoid empty strings here by mapping to null, and in the view model we navigate back in case off null

2023-05-09 12:52 UTC, AndroidBob commented
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1767/1/) **failed**.

2023-05-09 13:58 UTC, AndroidBob commented
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1767/3/) **failed**.

2023-05-09 14:28 UTC, AndroidBob commented
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1767/4/) **failed**.

2023-05-10 07:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-android-reloaded?pullRequest=1767) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-android-reloaded?pullRequest=1767) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-android-reloaded?pullRequest=1767) it.</sub>

2023-05-10 08:06 UTC, AndroidBob commented
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1767/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6473781)(6473781)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6473781)(6473781)-staging-compat.apk)

2023-05-10 09:06 UTC, AndroidBob commented
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1767/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6474138)(6474138)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6474138)(6474138)-staging-compat.apk)

2023-05-11 10:07 UTC, AndroidBob commented
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1767/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6483108)(6483108)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6483108)(6483108)-staging-compat.apk)

2023-05-11 10:11 UTC, MohamadJaara approved these changes

2023-05-11 11:49 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsScreen.kt
> +) {
Can we make `ServiceDetailsContent` not depending on the viewModel by passing the required params ?

2023-05-11 11:49 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsViewModel.kt
> +class ServiceDetailsViewModel @Inject constructor(
Can we test it ?

2023-05-11 11:49 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsMapper.kt
> +}
Can we cover this mapper with test ?

2023-05-12 08:38 UTC, AndroidBob commented
Build [9](https://10.10.124.134/job/wire-android-reloaded/job/PR-1767/9/) **failed**.

2023-05-12 09:35 UTC, AndroidBob commented
Build [11](https://10.10.124.134/job/wire-android-reloaded/job/PR-1767/11/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6491591)(6491591)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6491591)(6491591)-staging-compat.apk)

2023-05-12 10:08 UTC, ohassine approved these changes
Well done ✨

2023-05-12 10:52 UTC, AndroidBob commented
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-1767/12/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6492060)(6492060)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6492060)(6492060)-staging-compat.apk)

2023-05-12 11:05 UTC, merged