feat: new conversation creation system messages (AR-910)
wireapp/wire-android pull request #1828
Opened 2023-05-30 15:45 UTC by yamilmedina

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-910" title="AR-910" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-910</a>  Initial Group Introduction System Message
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Currently, we don't show a system message when starting a group conversation.

### Solutions

This PR:
- Add the system message info, in conversation creation flow, about members the conversation was started with.
- Adds initial system message about conversation creation date
- Prepares the code for later offline backend handling for conversation creation with remote participants.

Needs to be merged **after** merging:
- https://github.com/wireapp/kalium/pull/1762

### Attachments

https://github.com/wireapp/wire-android-reloaded/assets/5806454/7ec16409-6b5e-4c23-be07-bbc04cfc34e3

### Testing

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-05-30 16:43 UTC, AndroidBob commented
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1828/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6649681)(6649681)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6649681)(6649681)-staging-compat.apk)

2023-05-31 08:18 UTC, alexandreferris reviewed
Looking great!

I just have one tiny question 😅

2023-05-31 08:18 UTC, alexandreferris commented on app/src/main/kotlin/com/wire/android/mapper/SystemMessageContentMapper.kt
> +        )
are we using `userList` here? 🤔

2023-05-31 09:42 UTC, yamilmedina commented on app/src/main/kotlin/com/wire/android/mapper/SystemMessageContentMapper.kt
> +        )
Good catch, fixed, now I'm using it, for preparation for later use on conversation creation event.

2023-05-31 10:10 UTC, AndroidBob commented
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1828/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6655956)(6655956)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6655956)(6655956)-staging-compat.apk)

2023-05-31 10:15 UTC, alexandreferris approved these changes

2023-05-31 14:27 UTC, AndroidBob commented
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1828/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6657496)(6657496)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6657496)(6657496)-staging-compat.apk)

2023-05-31 14:43 UTC, vitorhugods requested changes
Looks awesome!

Just one suggestion for date/time formatting.

2023-05-31 14:43 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/util/DateTimeUtil.kt
> +    "EEE, MMM dd, hh:mm a",
I just wonder how that would look in different languages.

`Day of the week, month, day of the month`

At least in Portuguese that's weird. Also AM/PM may not be followed.

We could use [DateFormat](https://developer.android.com/reference/java/text/DateFormat.html):

```kotlin
DateFormat.getDateTimeInstance(DateFormat.FULL, DateFormat.SHORT).format(date)
```

`DateFormat.FULL` for Dates will include the week day.
`DateFormat.SHORT` for Time will keep only hours and minutes.


But it should respect Locale without we needing to create different patterns for different languages.

2023-05-31 14:43 UTC, MohamadJaara approved these changes

2023-05-31 15:08 UTC, yamilmedina commented on app/src/main/kotlin/com/wire/android/util/DateTimeUtil.kt
> +    "EEE, MMM dd, hh:mm a",
Great idea and makes sense to me, more easy to use the standard one. Changed

2023-05-31 15:36 UTC, AndroidBob commented
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1828/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6657911)(6657911)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6657911)(6657911)-staging-compat.apk)

2023-05-31 17:18 UTC, AndroidBob commented
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1828/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6658531)(6658531)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6658531)(6658531)-staging-compat.apk)

2023-05-31 17:34 UTC, vitorhugods commented on buildSrc/src/main/kotlin/scripts/quality.gradle.kts
> +    exclude("**/*.kts", "*/build/*", "/buildSrc", "**/test/**/*")
Is this necessary?

2023-05-31 17:34 UTC, vitorhugods approved these changes

2023-05-31 20:38 UTC, merged

2023-05-31 20:40 UTC, AndroidBob commented
Build [10](https://10.10.124.134/job/wire-android-reloaded/job/PR-1828/10/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6659717)(6659717)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6659717)(6659717)-staging-compat.apk)