feat: add option to retry or cancel messages that failed to send [AR-2188]
wireapp/wire-android pull request #1830
Opened 2023-05-31 15:23 UTC by saleniuk

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Right now the user doesn’t have the option to retry or cancel messages that failed to send.

### Solutions

For retrying, use newly created use case.
For canceling, use existing logic to delete the message.

### Dependencies (Optional)

Needs releases with:

- https://github.com/wireapp/kalium/pull/1770

### Testing

#### How to Test

Send a message when being offline and cancel or retry it.

### Attachments (Optional)

https://github.com/wireapp/wire-android-reloaded/assets/30429749/33f67078-b035-4ca6-b53a-c56b4f8c5bb4

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-05-31 15:37 UTC, AndroidBob commented
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1830/1/) **failed**.

2023-06-01 07:10 UTC, AndroidBob commented
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1830/3/) **failed**.

2023-06-01 07:38 UTC, ohassine approved these changes

2023-06-01 07:38 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
> +    private val retryFailedMessageUseCase: RetryFailedMessageUseCase,
We don't need to add `useCase` suffix to the name

2023-06-01 07:50 UTC, AndroidBob commented
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1830/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6663755)(6663755)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6663755)(6663755)-staging-compat.apk)

2023-06-01 11:43 UTC, vitorhugods requested changes
Looks great 👨‍🍳🤌🏻

I'll keep it as `Request changes` to wait for @ohassine's suggestion and mine to use `@PreviewMultipleThemes`.

2023-06-01 11:43 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItemComponents.kt
> +@Preview
```suggestion
@PreviewMultipleThemes
```

Maybe this one? :D

2023-06-01 11:43 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItemComponents.kt
> +@Preview
```suggestion
@PreviewMultipleThemes
```

2023-06-01 11:43 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypesPreview.kt
> +@Preview(showBackground = true)
```suggestion
@PreviewMultipleThemes
```

2023-06-01 14:08 UTC, AndroidBob commented
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1830/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6666017)(6666017)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6666017)(6666017)-staging-compat.apk)

2023-06-01 16:30 UTC, AndroidBob commented
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1830/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6666883)(6666883)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6666883)(6666883)-staging-compat.apk)

2023-06-02 07:03 UTC, vitorhugods approved these changes
🧑🏻‍🍳🤌🏻

2023-06-02 07:21 UTC, merged