fix: attachment options in chat not working on android 14 (WPB-1846)
wireapp/wire-android pull request #2073
Opened 2023-08-08 12:15 UTC by ohassine

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

User can't attach files on when using the app on Android 14

### Causes (Optional)

On Android 14, `isImeVisible` is considering the attachments option layout as soft keyboard, causing to return wrong values when calling `isKeyboardVisible()`

### Solutions

Use `isVisible` from `WindowInsetsCompat `only 

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

You should be able to see the attachment options when you try to send a file using a device on Android 14.

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-08-08 12:17 UTC, alexandreferris approved these changes

2023-08-08 13:03 UTC, AndroidBob commented
Build [962](https://10.10.124.134/job/AR-build-pipeline/962/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7253153)(7253153)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7253153)(7253153)-staging-compat.apk)

2023-08-09 09:58 UTC, MohamadJaara approved these changes

2023-08-09 10:14 UTC, trOnk12 requested changes
there is a kalium bump ?

2023-08-09 10:14 UTC, trOnk12 approved these changes

2023-08-09 10:22 UTC, ohassine commented
> there is a kalium bump ?

No just was using old reference

2023-08-09 10:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-android-reloaded?pullRequest=2073) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-android-reloaded?pullRequest=2073) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: tmspzz<br/>:white_check_mark: ohassine<br/>:x: trOnk12<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-android-reloaded?pullRequest=2073) it.</sub>

2023-08-09 11:20 UTC, AndroidBob commented
Build [982](https://10.10.124.134/job/AR-build-pipeline/982/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7261171)(7261171)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7261171)(7261171)-staging-compat.apk)

2023-08-09 11:25 UTC, merged