fix: crash when opening service details screen [WPB-4586]
wireapp/wire-android pull request #2230
Opened 2023-09-12 16:45 UTC by MohamadJaara

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

[WPB-4586](https://wearezeta.atlassian.net/browse/WPB-4586)  when opening  a service details screen the app will try to calculate the security level banner state, and since the screen does not take user id as nav arg then the app crashes

### Solutions

changed the composable to be type safe and enforce passing either a conversation of a user id

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-09-12 18:42 UTC, AndroidBob commented
Build [737](https://10.10.124.134/job/AR-build-pipeline/737/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7557487)(7557487)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7557487)(7557487)-staging-compat.apk)

2023-09-13 07:15 UTC, alexandreferris approved these changes

2023-09-13 07:50 UTC, saleniuk approved these changes

2023-09-13 08:26 UTC, Garzas requested changes, later dismissed

2023-09-13 08:26 UTC, Garzas commented on app/src/main/kotlin/com/wire/android/ui/common/banner/SecurityClassificationBanner.kt
>      viewModel: SecurityClassificationViewModel =
Preview for other composables which are using SecurityClassificationBannerForConversation will not be generated, because we are not using Preview view model when composable is in LocalInspectionMode

```
  val viewModel = if (LocalInspectionMode.current) {
        SecurityClassificationPreviewModel(SecurityClassificationType.CLASSIFIED)
    } else {
hiltViewModelScoped<SecurityClassificationViewModelImpl, SecurityClassificationArgs>(
            SecurityClassificationArgs.Conversation(
                id = conversationId,
            )
        )
    }
```

2023-09-13 08:27 UTC, Garzas commented on app/src/main/kotlin/com/wire/android/ui/common/banner/SecurityClassificationBanner.kt
> +        hiltViewModelScoped<SecurityClassificationViewModelImpl, SecurityClassificationArgs>(
Same situation here

2023-09-13 08:41 UTC, MohamadJaara commented on app/src/main/kotlin/com/wire/android/ui/common/banner/SecurityClassificationBanner.kt
>      viewModel: SecurityClassificationViewModel =
the preview is for the `SecurityClassificationBanner` Composable, so this will not be needed

2023-09-13 09:10 UTC, merged

2023-09-13 09:43 UTC, AndroidBob commented
Build [749](https://10.10.124.134/job/AR-build-pipeline/749/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7562875)(7562875)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7562875)(7562875)-staging-compat.apk)