chore: update localization strings via Crowdin
wireapp/wire-android pull request #2244
Opened 2023-09-18 21:46 UTC by AndroidBob

This PR pulls in the latest localization translations from Crowdin.

2023-09-18 22:31 UTC, AndroidBob commented
Build [833](https://10.10.124.134/job/AR-build-pipeline/833/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7610706)(7610706)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7610706)(7610706)-staging-compat.apk)

2023-09-19 13:07 UTC, AndroidBob commented
Build [844](https://10.10.124.134/job/AR-build-pipeline/844/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7615937)(7615937)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7615937)(7615937)-staging-compat.apk)

2023-09-19 15:08 UTC, ohassine approved these changes

2023-09-19 15:51 UTC, AndroidBob commented
Build [849](https://10.10.124.134/job/AR-build-pipeline/849/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7616961)(7616961)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7616961)(7616961)-staging-compat.apk)

2023-09-20 08:17 UTC, MohamadJaara approved these changes

2023-09-20 09:37 UTC, gongracr requested changes

2023-09-20 09:37 UTC, gongracr commented on app/src/main/res/values-de/strings.xml
> +    <string name="label_not_now">Not Now</string>
This is messing up German translations. Does anyone know where these changes might be coming from @MohamadJaara @ohassine ?

2023-09-20 09:54 UTC, AndroidBob commented
Build [865](https://10.10.124.134/job/AR-build-pipeline/865/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7623465)(7623465)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7623465)(7623465)-staging-compat.apk)

2023-09-20 09:55 UTC, merged