feat: Adding option on bottom sheet to archive use cases
wireapp/wire-android pull request #2262
Opened 2023-09-22 13:54 UTC by gongracr

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We need an option to be able to archive conversations visually and consume `updateConversationArchivedStatusUseCase`.

### Solutions

Added the option on the different bottom sheets displayed when interacting with conversations options in `HomeScreen`, `GroupConversationDetailsScreen`, and `OtherUserProfileScreen`. I also added the respective snackbar messages on success and failed states.

### Dependencies (Optional)

- https://github.com/wireapp/kalium/pull/2082

Needs releases with:

- [x] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Load conversations in `HomeScreen`, long tap on a given one and click on `Move to archive` option. Check the conversation disappears and doesn't get displayed anymore. This behavior can also be replicated on Other users profile screen and on Group details screen.

### Attachments (Optional)

https://github.com/wireapp/wire-android-reloaded/assets/2468164/16095fb5-c9c7-4479-bdca-58d245b1101b

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-09-22 14:06 UTC, AndroidBob commented
Build [919](https://10.10.124.134/job/AR-build-pipeline/919/) **failed**.

2023-09-22 16:12 UTC, AndroidBob commented
Build [928](https://10.10.124.134/job/AR-build-pipeline/928/) **failed**.

2023-09-23 08:49 UTC, AndroidBob commented
Build [931](https://10.10.124.134/job/AR-build-pipeline/931/) **failed**.

2023-09-25 06:56 UTC, Garzas requested changes
Looking good 👍  I would just add some tests for onMoveConversationToArchive

2023-09-25 06:56 UTC, Garzas commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
> +                        conversationId = conversationSheetContent!!.conversationId,
Maybe surround it with ?.let {} to not have a crash in some race condition 🤔

2023-09-25 06:56 UTC, Garzas commented on app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
> +                observeConversationListDetails(fetchArchivedConversations = false)
maybe rename to includeArchived?

2023-09-25 11:03 UTC, Garzas approved these changes

2023-09-25 11:29 UTC, AndroidBob commented
Build [951](https://10.10.124.134/job/AR-build-pipeline/951/) **failed**.

2023-09-25 15:44 UTC, AndroidBob commented
Build [965](https://10.10.124.134/job/AR-build-pipeline/965/) **failed**.

2023-09-26 09:19 UTC, AndroidBob commented
Build [972](https://10.10.124.134/job/AR-build-pipeline/972/) **failed**.

2023-09-26 09:24 UTC, alexandreferris approved these changes

2023-09-26 11:00 UTC, AndroidBob commented
Build [985](https://10.10.124.134/job/AR-build-pipeline/985/) **failed**.

2023-09-26 11:54 UTC, merged

2023-09-26 12:16 UTC, AndroidBob commented
Build [990](https://10.10.124.134/job/AR-build-pipeline/990/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7676111)(7676111)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7676111)(7676111)-staging-compat.apk)