feat: typing indicator in conversation view (WPB-4706)
wireapp/wire-android pull request #2292
Opened 2023-10-02 08:05 UTC by yamilmedina

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We need to add the capability to add the typing indicator for conversations.

### Causes (Optional)

Whenever another user is typing, we are going to show the writing pen indication.

### Testing

#### Test Coverage (Optional)

WIP

- [ ] I have added automated test to this contribution

### Attachments (Optional)

https://github.com/wireapp/wire-android-reloaded/assets/5806454/5335546e-0bae-4c5c-8b38-f0a726335105

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-10-02 08:35 UTC, AndroidBob commented
Build [1093](https://10.10.124.134/job/AR-build-pipeline/1093/) **failed**.

2023-10-02 10:05 UTC, AndroidBob commented
Build [1094](https://10.10.124.134/job/AR-build-pipeline/1094/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7727194)(7727194)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7727194)(7727194)-staging-compat.apk)

2023-10-02 11:08 UTC, AndroidBob commented
Build [1096](https://10.10.124.134/job/AR-build-pipeline/1096/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7727584)(7727584)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7727584)(7727584)-staging-compat.apk)

2023-10-02 12:36 UTC, AndroidBob commented
Build [1100](https://10.10.124.134/job/AR-build-pipeline/1100/) **failed**.

2023-10-02 12:40 UTC, yamilmedina commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationMemberExt.kt
> +fun UserSummary.previewAsset(
@alexandreferris here I refactored to reuse this mapper since we had this `UserSummary` from several points :D

2023-10-02 12:48 UTC, AndroidBob commented
Build [1101](https://10.10.124.134/job/AR-build-pipeline/1101/) **failed**.

2023-10-02 14:30 UTC, AndroidBob commented
Build [1103](https://10.10.124.134/job/AR-build-pipeline/1103/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7728782)(7728782)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7728782)(7728782)-staging-compat.apk)

2023-10-02 14:32 UTC, Garzas requested changes
Looking good 🚀  I would just not use this state with others because it will change a lot

2023-10-02 14:32 UTC, Garzas commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
> +    private fun observeUsersTypingState() {
I would prefer to have small view model for this state. This state is independent from others 🤔

2023-10-02 14:38 UTC, ohassine approved these changes

2023-10-02 14:38 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/UsersTypingIndicator.kt
> +private fun UsersTypingAvatarPreviews(usersTyping: List<UIParticipant>, maxPreviewsDisplay: Int = 3) {
Can we extract `maxPreviewsDisplay` as a const so it will be easier later to change it

2023-10-02 16:23 UTC, yamilmedina commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
> +    private fun observeUsersTypingState() {
Done!

2023-10-02 16:49 UTC, AndroidBob commented
Build [1113](https://10.10.124.134/job/AR-build-pipeline/1113/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7729577)(7729577)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7729577)(7729577)-staging-compat.apk)

2023-10-02 17:41 UTC, AndroidBob commented
Build [1121](https://10.10.124.134/job/AR-build-pipeline/1121/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7729928)(7729928)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7729928)(7729928)-staging-compat.apk)

2023-10-03 06:36 UTC, Garzas approved these changes
Wow that was fast 🐎

2023-10-03 07:59 UTC, merged

2023-10-03 08:14 UTC, AndroidBob commented
Build [1127](https://10.10.124.134/job/AR-build-pipeline/1127/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7735136)(7735136)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7735136)(7735136)-staging-compat.apk)