feat: unlock app with biometrics (WPB-4696)
wireapp/wire-android pull request #2321
Opened 2023-10-12 14:02 UTC by ohassine

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Description

This PR will allow the user to unlock his device using biometrics (fingerprint or FaceId). 

The biometrics prompt dialog will be displayed if you have your fingerprint or faceId configured in device otherwise regular app lock screen will be shown.

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

- Make sure that you have 
- Enable app lock
- Put the app in background for 60s
- Open the app again, you should see biometrics prompt dialog.

### Attachments (Optional)

Samsung S22

| Fingerprint  | FaceId |
| ------------- | ------------- |
| ![Wire 2023-10-12 at 2_59 PM](https://github.com/wireapp/wire-android-reloaded/assets/18124919/0d136536-ad9f-4699-a4cb-29bf1cdc9b87)  | ![Wire 2023-10-12 at 2_59 PM2](https://github.com/wireapp/wire-android-reloaded/assets/18124919/896a7a30-a4d6-4c30-a487-645e2c2577bf)  |

Pixel 6

![Wire 2023-10-12 at 4_02 PM](https://github.com/wireapp/wire-android-reloaded/assets/18124919/21f37a19-ff33-41ed-bdac-d9da48e5bfda)

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-10-12 14:06 UTC, vitorhugods requested changes
LGTM, just wonder about having some strings localised

Exciting to have app lock :)

2023-10-12 14:06 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/biomitric/BiometricPromptUtils.kt
> +            setNegativeButtonText("Use passcode")
Localisation in these Strings!

2023-10-12 14:07 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/biomitric/BiometricPromptUtils.kt
> +            setNegativeButtonText("Use passcode")
Oh! yeah

2023-10-12 14:39 UTC, vitorhugods approved these changes

2023-10-12 14:57 UTC, AndroidBob commented
Build [1269](https://10.10.124.134/job/AR-build-pipeline/1269/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7815370)(7815370)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7815370)(7815370)-staging-compat.apk)

2023-10-13 14:00 UTC, alexandreferris approved these changes

2023-10-13 16:36 UTC, AndroidBob commented
Build [1306](https://10.10.124.134/job/AR-build-pipeline/1306/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7824567)(7824567)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7824567)(7824567)-staging-compat.apk)

2023-10-16 08:41 UTC, merged

2023-10-16 08:41 UTC, saleniuk approved these changes

2023-10-16 08:53 UTC, AndroidBob commented
Build [1318](https://10.10.124.134/job/AR-build-pipeline/1318/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7847702)(7847702)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7847702)(7847702)-staging-compat.apk)