feat: Search inside conversation (WPB-4915)
wireapp/wire-android pull request #2358
Opened 2023-10-20 15:15 UTC by alexandreferris

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] contains a reference JIRA issue number like `SQPIT-764`
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

No way to search messages from a conversation.

### Causes (Optional)

Not implemented.

### Solutions

Addition of screen to search messages of selected conversation.
Entry points:
- Group Details Screen
- Other User Profile Screen

There is a minimum of 2 characters to start the search and a debounce of 500ms in between each search.

This PR aims only to display the searched messages and not being able to select a message and navigate to its place in Conversation screen.

### Dependencies (Optional)

Needs releases with:

- [X] [Kalium - Search inside conversation](https://github.com/wireapp/kalium/pull/2137)

### Testing

#### Test Coverage (Optional)

- [X] I have added automated test to this contribution

#### How to Test

- Open App
- Open a Conversation (Group or 1:1)
- Open Search
- Type desired message to search
- Results will be displayed but not selectable yet.

### Attachments (Optional)

| Default | No Results |
| ----------- | ------------ |
| <img src="https://github.com/wireapp/wire-android-reloaded/assets/5890660/18a212c6-aa38-41d6-abaa-16e9ca009881" width="200" height="400" />  | <img src="https://github.com/wireapp/wire-android-reloaded/assets/5890660/a4b7184b-8138-4929-b782-e6d32f525bd2" width="200" height="400" />  |

| One Result | Multiple Results |
| ----------- | ------------ |
| <img src="https://github.com/wireapp/wire-android-reloaded/assets/5890660/8d47317d-efee-467a-b6bc-e0d114829a2f" width="200" height="400" />  | <img src="https://github.com/wireapp/wire-android-reloaded/assets/5890660/adefd3da-c744-4109-947c-8bd7b0e78e02" width="200" height="400" />  |

2023-10-20 16:23 UTC, AndroidBob commented
Build [1456](https://10.10.124.134/job/AR-build-pipeline/1456/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7884995)(7884995)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7884995)(7884995)-staging-compat.apk)

2023-10-23 08:43 UTC, yamilmedina reviewed
Looks pretty good and solid to me 🚀  
Just added small suggestions, so if it does not makes sense, juit skip them :D

2023-10-23 08:43 UTC, yamilmedina commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesNoResultsScreen.kt
> +fun SearchConversationMessagesNoResultsScreen() {
Suggestion: Maybe we can add a `Preview` here, just for later snapshot (if they come)

2023-10-23 08:43 UTC, yamilmedina commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesScreen.kt
> +fun SearchConversationMessagesResultContent(
Suggestion: Maybe we can add a `Preview` here as well

2023-10-23 08:43 UTC, yamilmedina commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesState.kt
> +    val noneSearchSucceed: Boolean = false
Suggestion: Maybe something like a `isEmptyResult` or `isNoResultsFound` something that  has the results words in the name 🤔

2023-10-23 08:43 UTC, yamilmedina commented on app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/SearchConversationMessagesViewModelTest.kt
> +//            }
```suggestion

```

2023-10-23 08:44 UTC, yamilmedina approved these changes

2023-10-23 09:19 UTC, alexandreferris commented on app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/SearchConversationMessagesViewModelTest.kt
> +//            }
🙈

2023-10-23 10:31 UTC, AndroidBob commented
Build [1465](https://10.10.124.134/job/AR-build-pipeline/1465/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7908758)(7908758)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7908758)(7908758)-staging-compat.apk)

2023-10-23 12:07 UTC, vitorhugods requested changes
Awesome work. Just one suggestion to make `MessageItem` more reusable.

2023-10-23 12:07 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
> +    isFromSearch: Boolean = false
question: can't we just change the background of the search screen instead of doing this?

----

In case it doesn't work, here's a suggestion:

suggestion: the message item shouldn't care if it's from search or not.

What if now we display this also in some other screen, like in the `Mentions` list or whatever. Then we'd need another `isFromMentions`?

instead of `isFromSearch`, perhaps just adding a `defaultBackgroundColor`.

Something like:

```suggestion
    defaultBackgroundColor: Color = Color.Transparent
```

And further down:

```kotlin
        } else {
            Modifier.background(defaultBackgroundColor)
        }
```

instead of adding an extra condition for the `search` part.

The search caller can call it with the desired `defaultBackgroundColor`.

2023-10-23 12:07 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
> +                                if (isMyMessage && !isFromSearch) {
Same here. Instead of `isFromSearch`, it could be `shouldDisplayMessageStatus`

2023-10-23 12:07 UTC, vitorhugods commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
> +                            if (!isFromSearch) {
And here: `shouldDisplayFooter`

2023-10-23 13:25 UTC, vitorhugods approved these changes

2023-10-23 13:36 UTC, AndroidBob commented
Build [1471](https://10.10.124.134/job/AR-build-pipeline/1471/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7909903)(7909903)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7909903)(7909903)-staging-compat.apk)

2023-10-23 14:20 UTC, merged