fix: leaking UI context GetE2EICertificateUseCase (WPB-6648)
wireapp/wire-android pull request #2713
Opened 2024-02-15 15:15 UTC by alexandreferris

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] contains a reference JIRA issue number like `SQPIT-764`
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Leaking Context from `GetE2EICertificateUseCase`

### Causes (Optional)

Context was being passed from UI

### Solutions

Inject `applicationContext` on ViewModel that is calling `GetE2EICertificateUseCase`

2024-02-15 15:34 UTC, saleniuk approved these changes

2024-02-15 16:04 UTC, AndroidBob commented
Build [3158](https://10.10.124.134/job/AR-build-pipeline/3158/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8904382)(8904382)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8904382)(8904382)-staging-compat.apk)

2024-02-15 20:03 UTC, MohamadJaara requested changes

2024-02-15 20:03 UTC, MohamadJaara commented on app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
> +    @ApplicationContext private val applicationContext: Context
There is no need to inject it into the view model, we can directly inject it into the use case constructor this way there is zero chance of someone passing a UI context to the use case

2024-02-16 09:17 UTC, alexandreferris commented on app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
> +    @ApplicationContext private val applicationContext: Context
As we are creating the usecase in this ViewModel we will need to pass something when creating the usecase 🤔

2024-02-16 11:04 UTC, MohamadJaara approved these changes

2024-02-16 11:25 UTC, merged

2024-02-16 12:04 UTC, AndroidBob commented
Build [3172](https://10.10.124.134/job/AR-build-pipeline/3172/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8911541)(8911541)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8911541)(8911541)-staging-compat.apk)