fix(e2ei): error handling (WPB-6271)
wireapp/wire-android pull request #2721
Opened 2024-02-20 20:16 UTC by mchenani

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?
Fixed and refactored the error handling for E2EI
Needs releases with:

- [ ] https://github.com/wireapp/kalium/pull/2522

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-02-20 20:41 UTC, AndroidBob commented
Build [3237](https://10.10.124.134/job/AR-build-pipeline/3237/) **failed**.

2024-02-23 08:28 UTC, Garzas requested changes

2024-02-23 08:28 UTC, Garzas commented on app/src/main/kotlin/com/wire/android/feature/e2ei/GetE2EICertificateUseCase.kt
> +                    applicationContext.getActivity()!!.activityResultRegistry,
Can we secure null here just in case and log some error instead of crash?

2024-02-23 08:30 UTC, mchenani commented on app/src/main/kotlin/com/wire/android/feature/e2ei/GetE2EICertificateUseCase.kt
> +                    applicationContext.getActivity()!!.activityResultRegistry,
Thanks for the comment, it's actually a crash! since the appContext can't give us the activity, @borichellow is refactoring it and will have a fix in another PR. [ it's already broken :D ]

2024-02-23 08:37 UTC, Garzas approved these changes

2024-02-23 08:42 UTC, alexandreferris approved these changes

2024-02-23 08:49 UTC, merged

2024-02-23 09:18 UTC, AndroidBob commented
Build [3276](https://10.10.124.134/job/AR-build-pipeline/3276/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8971040)(8971040)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8971040)(8971040)-staging-compat.apk)