New Backups: Create a backup from UI
wireapp/wire-android pull request #2988
Opened 2020-08-18 15:15 UTC by makingthematrix

This PR contains code connecting Scala and Kotlin (1) and of a fix to BackUpDataSource<T, E> (2)

1.
In BackupExportView in Scala I switched from calling the old backup functionality in BackupManager to calling the new functionality through KotlinServices and BackUpViewModel. This is by necessity a bit hacky: KotlinServices provides a way to call Kotlin from Scala, but it's not a fragment or an activity, so injecting BackUpViewModel is done through a small additional Koin library: koin-java. Its official purpose is to enable calling Koin from Java, but it turns out it also greatly simplifies calling Koin from Kotlin where standard methods don't work.

BackUpViewModel handles CreateBackUpUseCase and in the future it should also handle RestoreBackUpUseCase. It hides from KotlinServices (and Scala) the fact that we use coroutines. Instead, Scala provides two callbacks: onSuccess and onFailure. One (and only one) of them should be called when the Kotlin side finishes working.

2.
The bug was that the abstract type BackUpRepository<List<File>> was referred to and treated as BackUpRepository<File> in CreateBackUpUseCase. The compiler didn't catch it, and on top of that Koin was happy to inject the repositories even though their types didn't fit. Only when I started to test manually, the app crashed with a ClassCastException.
Apart from fixing the type, I had to add names to arguments in Koin. It was necessary also for the point #1 to let Koin know how to create BackUpViewModel.

I made also some changes to the how we write json files and then zip them, but this part will be changed once again. Here I just wanted to make sure it works.

2020-08-20 14:27 UTC, makingthematrix commented
build again

2020-08-25 07:40 UTC, BradleyWire approved these changes

2020-08-25 10:50 UTC, gizemb requested changes

2020-08-25 10:50 UTC, gizemb commented on app/build.gradle
> +    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.0.1"
please add this as the others: `BuildDependencies.coroutines`

2020-08-25 10:50 UTC, gizemb commented on app/src/main/java/com/waz/zclient/KotlinServices.kt
> +    private val backUpViewModel: BackUpViewModel by lazy { inject(BackUpViewModel::class.java).value }
I have some concerns about this injection.
First of all, why do you need a `koin.java` dependency when you're injecting a Kotlin class to a Kotlin class? There's already a `KoinComponent` interface gets you koin dependencies by its `get()` method.

Secondly, `ViewModel`s are special classes that are designed for use with Activities and Fragments. The Android framework has its own way of creating viewModels which requires an Activity or Fragment to do so (see `ViewModelProviders`, `by viewModels()` from `activity-ktx` or, `by viewModel()` from koin). Once the VM is created, its lifecycle is directly related to the Activity or Fragment's lifecycle. 
https://developer.android.com/topic/libraries/architecture/viewmodel#lifecycle

If you don't use the ViewModel inside an Activity or Fragment, I assume you don't care about the Activity/Fragment lifecycle, so there's no benefit in creating a `ViewModel`. It can be any plain Kotlin class instead of BackUpViewModel, and you can inject it here via `KoinComponent`.

If you care about the lifecycle, for instance you want to cancel the operation when the person leaves the Activity, then you should create this VM inside your Scala activity/fragment, and you can use `ViewModelProviders` for the creation.

2020-08-25 10:50 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
> +    factory(named(KEY_VALUES + FILE)) { BackUpFileIOHandler<KeyValuesBackUpModel>(KEY_VALUES, get(named(KEY_VALUES + JSON)), get()) }
I understand the need for `KEY_VALUES` etc, but do you need these `JSON`, `FILE`, `DB`.. suffixes? can't koin resolve the correct dependency by combining the return type + name?

2020-08-25 10:50 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandler.kt
> +            val batch = batchDao.nextBatch(count, Math.min(batchDao.count() - count, batchSize)) ?: emptyList()
there's still a `batchDao.count()` call here which makes a db call each time.

2020-08-25 10:50 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandler.kt
> +            return batchDaoCount() > count
`batchDaoCount()` can throw an exception here (since it makes a db call). I think it should be handled.

2020-08-25 10:50 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandler.kt
> +                    Either.Right(emptyList())
I think failing here (`Either.Left`) would be better. We always expect the users to check for existence with `hasNext()`, before calling `readNext()`, right?

2020-08-25 10:50 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/zip/ZipHandler.kt
> +                Either.Left(ZipFailure("Nothing to zip, the list of files is empty"))
this could be a more specific failure as `NoFilesToZipFailure` (or with a better naming) instead of a generic failure + string message

2020-08-25 10:50 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
> +      android.R.string.ok,
`android.R` resources are not translated, so we should use wire equivalents.

2020-08-25 10:50 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/ZipHandlerTest.kt
> +            .onFailure { assert(it is ZipFailure) }
does `assert()` come from `junit`?

2020-08-25 10:50 UTC, gizemb commented on buildSrc/src/main/kotlin/Dependencies.kt
> +        "androidViewModel" to "org.koin:koin-android-viewmodel:${Versions.KOIN}",
where was this used?

2020-08-26 12:52 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
> +    factory(named(KEY_VALUES + FILE)) { BackUpFileIOHandler<KeyValuesBackUpModel>(KEY_VALUES, get(named(KEY_VALUES + JSON)), get()) }
@gizemb : It looks like it can't. I removed the suffixes from names of `CONVERSATIONS` objects and the app crashed at start (but compilation went fine):
```
    java.lang.RuntimeException: Unable to create application com.waz.zclient.StethoApplication: org.koin.core.error.DefinitionOverrideException: Already existing definition or try to override an existing one with qualifier 'Conversations' with [type:Factory,name:'Conversations', primary_type:'com.waz.zclient.feature.backup.io.database.BatchDatabaseIOHandler'] but has already registered [type:Factory,name:'Conversations', primary_type:'com.waz.zclient.core.utilities.converters.JsonConverter']
```

2020-08-26 13:19 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
> +      android.R.string.ok,
@gizemb : We make exception for this one. "OK" is pretty much the standard positive response everywhere.

2020-08-26 13:20 UTC, makingthematrix commented on app/src/test/kotlin/com/waz/zclient/feature/backup/ZipHandlerTest.kt
> +            .onFailure { assert(it is ZipFailure) }
Right. It should be `assertTrue`. Thanks.

2020-08-26 13:23 UTC, makingthematrix commented on buildSrc/src/main/kotlin/Dependencies.kt
> +        "androidViewModel" to "org.koin:koin-android-viewmodel:${Versions.KOIN}",
Isn't this what gives us `org.koin.android.viewmodel.dsl.viewModel` in koin modules?

2020-08-26 13:57 UTC, makingthematrix commented on app/build.gradle
> +    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.0.1"
It turned out this is not needed anymore. I also removed koin-java.

2020-08-26 13:59 UTC, makingthematrix commented on app/src/main/java/com/waz/zclient/KotlinServices.kt
> +    private val backUpViewModel: BackUpViewModel by lazy { inject(BackUpViewModel::class.java).value }
I switched back from koin-java to `KoinComponent`. 

About the second part: I want to use `BackUpviewModel` as it is now because this way we can later copy the code to the reloaded project. This is the idea behind writing all this in Kotlin.

2020-08-26 14:00 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandler.kt
> +            val batch = batchDao.nextBatch(count, Math.min(batchDao.count() - count, batchSize)) ?: emptyList()
Ok.

2020-08-26 14:00 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandler.kt
> +            return batchDaoCount() > count
Right. I wrapped it in `requestDatabase`.

2020-08-26 14:01 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/zip/ZipHandler.kt
> +                Either.Left(ZipFailure("Nothing to zip, the list of files is empty"))
ok

2020-08-26 14:01 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandler.kt
> +                    Either.Right(emptyList())
Ok. I did it, but to be consistent, I also changed the code in `BatchDatabaseIOHandler` so that it returns a failure if there's nothing left to read.

2020-08-26 16:03 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
> +    factory(named(KEY_VALUES + FILE)) { BackUpFileIOHandler<KeyValuesBackUpModel>(KEY_VALUES, get(named(KEY_VALUES + JSON)), get()) }
fair enough, just wanted to take my chances here :D

2020-08-26 16:04 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
> +      android.R.string.ok,
ok then, btw, I checked and it seems like it's translated too.

2020-08-26 16:05 UTC, gizemb commented on buildSrc/src/main/kotlin/Dependencies.kt
> +        "androidViewModel" to "org.koin:koin-android-viewmodel:${Versions.KOIN}",
ah, ok. I thought this was recently added, but there's just an addition of a comma, so git highlights it.

2020-08-26 16:26 UTC, gizemb requested changes
one minor change:

2020-08-26 16:26 UTC, gizemb commented on app/src/main/java/com/waz/zclient/KotlinServices.kt
> +    private val backUpViewModel: BackUpViewModel by lazy { inject<BackUpViewModel>().value }
inject is already lazy so you can just say 
`private val backUpViewModel: BackUpViewModel by inject()`

2020-08-26 16:28 UTC, gizemb commented on app/src/main/java/com/waz/zclient/KotlinServices.kt
> +    private val backUpViewModel: BackUpViewModel by lazy { inject(BackUpViewModel::class.java).value }
> I switched back from koin-java to `KoinComponent`.
> 
> About the second part: I want to use `BackUpViewModel` as it is now because this way we can later copy the code to the reloaded project. This is the idea behind writing all this in Kotlin.

As far as I can see, BackUpViewModel is also going to change, so that doesn't add much value. But you're the developer so it's up to you to keep it that way. I would then suggest you to make some tests regarding the app lifecycle, for instance when the Activity finishes during back up operation, etc..

2020-08-27 09:46 UTC, mejdoo requested changes

2020-08-27 09:46 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
> +      if (BuildConfig.DEVELOPER_FEATURES_ENABLED && !context.getPackageManager.queryIntentActivities(new Intent(TestingGalleryPackage), PackageManager.MATCH_ALL).isEmpty) {
I think we can get rid of this code related to TestingGallery 

```
if (BuildConfig.DEVELOPER_FEATURES_ENABLED && !context.getPackageManager.queryIntentActivities(new Intent(TestingGalleryPackage), PackageManager.MATCH_ALL).isEmpty) {
         intent.setPackage(TestingGalleryPackage)
       }
```

2020-08-27 09:46 UTC, mejdoo commented on app/src/test/kotlin/com/waz/zclient/feature/backup/BackUpDataSourceTest.kt
> +    fun `given data sources and mapper, when backUp is called, then reads from databaseLocalDataSource, create writeIterator, and write to backUpLocalDataSource`() {
then read

2020-08-27 15:51 UTC, makingthematrix commented on app/src/main/java/com/waz/zclient/KotlinServices.kt
> +    private val backUpViewModel: BackUpViewModel by lazy { inject<BackUpViewModel>().value }
@gizemb : Unfortunately, `inject()` crashes during restoration with the error that Koin is not started. It looks like the injection itself is lazy, but the initial call to Koin is not.

2020-08-27 16:35 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
> +      if (BuildConfig.DEVELOPER_FEATURES_ENABLED && !context.getPackageManager.queryIntentActivities(new Intent(TestingGalleryPackage), PackageManager.MATCH_ALL).isEmpty) {
Ok, I removed it in https://github.com/wireapp/wire-android/pull/3003

2020-08-27 16:35 UTC, makingthematrix commented on app/src/test/kotlin/com/waz/zclient/feature/backup/BackUpDataSourceTest.kt
> +    fun `given data sources and mapper, when backUp is called, then reads from databaseLocalDataSource, create writeIterator, and write to backUpLocalDataSource`() {
Changed in https://github.com/wireapp/wire-android/pull/3003

2020-08-28 08:32 UTC, gizemb commented on app/src/main/java/com/waz/zclient/KotlinServices.kt
> +    private val backUpViewModel: BackUpViewModel by lazy { inject<BackUpViewModel>().value }
hmm, what about 
`private val backUpViewModel: BackUpViewModel by lazy { get() }`

lazy actually creates an object under the hood, and inject is also creating another one, so I want to get rid of one of them.

2020-08-28 09:35 UTC, makingthematrix commented on app/src/main/java/com/waz/zclient/KotlinServices.kt
> +    private val backUpViewModel: BackUpViewModel by lazy { inject<BackUpViewModel>().value }
Ok, this works :) Changed in https://github.com/wireapp/wire-android/pull/3003/commits/c4504c477696356b5487043abf6f9c89baeb3387

2020-08-28 09:38 UTC, gizemb approved these changes

2020-08-28 09:46 UTC, mejdoo approved these changes

2020-08-28 10:20 UTC, merged