New backups: Encryption
wireapp/wire-android pull request #2990
Opened 2020-08-18 16:05 UTC by makingthematrix

EncryptionHandler resotred as a new PR.

I rewrote this code as closesy as possible from Scala. Please take a look at com.waz.service.backup.EncryptionBackupHeader and com.waz.utils.crypto.LibSodiumUtils. 
We know that code works, but it's complex and hard to read. As for this rewritten version, first I'd like to
write some tests (or test it manually).
I'd suggest not to refactor it until we are sure our changes won't break anything.

2020-08-19 10:36 UTC, BradleyWire requested changes
Some key points for the Encryption class: 

1. It should only be decryption / encryption logic 
2. `Sodium` specific logic should be placed in a collaborator you can inject 
3. `EncryptionBackupHeader` does too much, we can break it down into multiple classes 
4.  More idiomatic ways to writing this in Kotlin without refactoring the logic (I haven't addressed them all with these comments)

2020-08-19 10:36 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandlerDataSource.kt
> +        val metadata = EncryptedBackupHeader.readEncryptedMetadata(backupFile)
We'll need to avoid these static calls if we want to properly unit test this. The `EncryptedBackupHeader` does alot considering it's a `data` class, we can probably move this function out of it (and the others based on the comments i've made already)

2020-08-19 10:36 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandlerDataSource.kt
> +        data class EncryptionFailure(val msg: String) : FeatureFailure()
This doesn't need to belong to the `companion object `

2020-08-19 10:36 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandlerDataSource.kt
> +        return if (metadata != null) {
This can be (maybe even broken down into private functions even more):

```
 override fun decrypt(backupFile: File, userId: UserId, password: String): Either<Failure, File> {
        loadLibrary
        return EncryptedBackupHeader.readEncryptedMetadata(backupFile)?.let { metaData ->
            hash(userId.str(), metaData.salt)?.let {
                when (it.contentEquals(metaData.uuidHash)) {
                    true -> {
                        val encryptedBackupBytes = ByteArray(EncryptedBackupHeader.totalHeaderLength)
                        backupFile.inputStream().buffered().read(encryptedBackupBytes)
                        decrypt(encryptedBackupBytes, password, metaData.salt).map { decryptedBackupBytes ->
                            File.createTempFile("wire_backup", ".zip").apply { writeBytes(decryptedBackupBytes) }
                        }
                    }
                    false -> Left(EncryptionFailure("Uuid hashes don't match"))
                }
            } ?: Left(EncryptionFailure("Uuid hashing failed"))
        } ?: Left(EncryptionFailure("metadata could not be read"))
    }

```

2020-08-19 10:36 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandlerDataSource.kt
> +        } catch (ex: IOException) {
Where are we catching this `IOException` from?

2020-08-19 10:36 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandlerDataSource.kt
> +        const val uuidHashLength = 32
This can live inside the `EncryptionHandlerDataSource` class

2020-08-19 10:36 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandlerDataSource.kt
> +        const val uuidHashLength = 32
same with the other constants only used inside that class

2020-08-27 10:53 UTC, mejdoo requested changes
Totally agree with @BradleyWire the encryption stuff is too complex and must be simplified by moving `Sodium` logic outside.

2020-08-27 10:53 UTC, mejdoo commented on app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandlerDataSource.kt
> +class EncryptionHandlerDataSource : EncryptionHandler {
Regarding the naming , renaming this class to **"Encryptor"** makes more sense to me. We have to think about this as a separate component for encryption and decryption.

2020-09-01 13:20 UTC, merged