Feat: Back ups - Encryption unit testing + cleanup
wireapp/wire-android pull request #2994
Opened 2020-08-19 13:42 UTC by BradleyWire

## What's new in this PR?

This is a follow on from: https://github.com/wireapp/wire-android/pull/2990

### Issues

Untestable + less readable encryption logic. 

### Causes

We rely on too many calls to the Sodium library as static calls (which are current untestable). 

### Solutions

Encapsulate the Sodium calls into a `Crypto` class

### Testing

Unit tests should exist for:

1.  EncryptionHandlerDataSource (Incomplete) 
2. EncyptionHeaderMetaData (Incomplete) 
3. EncryptionHeaderMapper (Incomplete)

2020-08-25 11:50 UTC, makingthematrix requested changes

2020-08-25 11:50 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +    private fun initializeState(key: ByteArray, header: ByteArray, init: (ByteArray, ByteArray, ByteArray) -> Int): ByteArray? =
Please use`Either<Failure, ByteArray>`. Return `CryptoFailure` for errors.

2020-08-25 11:50 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +    internal fun hash(input: String, salt: ByteArray): ByteArray? {
Here too it can be Either<Failure, ByteArray>. You can use the failure which now is used in `DecryptionHandler` if `hash` returns `null`: `Either.Left(CryptoFailure("Couldn't derive key from password"))`

2020-08-25 11:50 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/encryption/EncryptionHandler.kt
> +                    return@map File(backupFile.parentFile, backupFile.name + "_encrypted").apply {
`return@map` shouldn't be necessary.

2020-08-25 11:50 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncyptionHeader.kt
> +    fun readEncryptedMetadata(encryptedBackup: File): EncryptedBackupHeader? =
Please change to `Either<Failure, EncryptedBackupHeader>`

2020-08-25 11:50 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncyptionHeader.kt
> +    fun writeEncryptedMetaData(salt: ByteArray, hash: ByteArray): Either<Failure, ByteArray>? =
Let's not mix Either with nullable. And I think here it's not necessary? Even if `takeIf` fails we return `Either.Left`.

2020-08-25 11:50 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncyptionHeader.kt
> +    internal fun fromByteArray(bytes: ByteArray): EncryptedBackupHeader? =
Same as above.

2020-08-26 09:09 UTC, gizemb requested changes

2020-08-26 09:09 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandlerTest.kt
> +            res.onFailure {
why is this nested?
also, we should fail if res is not a Failure, or it is not the expected failure

we have similar usages in other test cases too.

2020-08-26 09:09 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandlerTest.kt
> +        val header = backupFile.readBytes().take(HEADER_STREAM_LENGTH).toByteArray()
do we need super realistic inputs? this looks like an integration test more than a unit test.

2020-08-26 09:09 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandlerTest.kt
> +        Thread.sleep(1)
why do we need `Thread.sleep()` here?

2020-08-26 10:53 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
> +            checkExpectedKeySize(key.size, crypto.decryptExpectedKeyBytes())
@makingthematrix do you know what the preferred behaviour is here?

2020-08-26 10:55 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/encryption/EncryptionHandler.kt
> +            val salt = crypto.generateSalt()
Yes, inside `generateSalt() ` we have a onFailure closure for the library which relies on a java `SecureRandom` generation of the buffer rather than a `LibSodium` based generation of `randomBytes`

2020-08-26 10:55 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncyptionHeader.kt
> +const val TOTAL_HEADER_LENGTH = ANDROID_MAGIC_NUMBER_LENGTH + 1 + 2 + SALT_LENGTH + UUID_HASH_LENGTH + 4 + 4
This is the same as it was before, I'm really not sure what benefit it brings

2020-08-26 14:49 UTC, makingthematrix requested changes

2020-08-26 14:49 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
> +        }
Yes. A simple `if (...)` should be enough.

2020-08-26 14:49 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +        if (header.size != Sodium.crypto_secretstream_xchacha20poly1305_headerbytes()) {
This can return `ByteArray` without `?`, right?

2020-08-26 14:50 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncyptionHeader.kt
> +data class EncryptedBackupHeader(
We never compare two headers, so I think it's not necessary.

2020-08-26 14:51 UTC, makingthematrix commented on app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandlerTest.kt
> +        Thread.sleep(1)
Just a hack to ensure the filename will be unique even if the computer doing the testing is cabale of calling this method twice in one millisecond.

2020-08-26 16:31 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
> +            checkExpectedKeySize(key.size, crypto.decryptExpectedKeyBytes())
ok then, thanks for the clarification.

2020-08-28 10:34 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
> +        } ?: Either.Left(CryptoFailure("Metadata could not be read"))
Now we've refactored this, it looks much more readable

2020-08-28 12:44 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncyptionHeader.kt
> +const val TOTAL_HEADER_LENGTH = ANDROID_MAGIC_NUMBER_LENGTH + 1 + 2 + SALT_LENGTH + UUID_HASH_LENGTH + 4 + 4
it would be handy to document this

2020-08-31 11:51 UTC, franziskuskiefer requested changes
Thanks! Generally looks pretty good already. I added a couple comments inline.

So this looks like it is implementing v2 from https://github.com/wearezeta/documentation/blob/0180afa7073909aef1dd199cd48fcddf4d915038/topics/backup/use-cases/001-export-history-v2.md? Is this documentation already moved to confluence somewhere?
What was the reason to do a v2 (also see inline comments about that)?

2020-08-31 11:51 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +    internal fun hash(input: String, salt: ByteArray): Either<Failure, ByteArray> {
So this is a password hash not a general hash. The naming is a little confusing. Maybe something like `pwdHash`?

2020-08-31 11:51 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            opsLimitInteractive(),
Why don't you use `opsLimit` here? If this ever gets changed you might run into trouble if you call `opsLimitInteractive` here directly.
Same below for `memLimit`.

2020-08-31 11:51 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            Sodium.crypto_pwhash_alg_default()
There's a lot of default values in here that might change over time in Sodium. That's pretty dangerous (for example, you won't be able to import backups anymore after bumping the version of Sodium).
This should be `crypto_pwhash_ALG_ARGON2ID13` according to the docs right now.

2020-08-31 11:51 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            messageBytes,
Shouldn't the first argument be the `state`? Or is `messageBytes` the state? (Then the name should change.)

2020-08-31 11:51 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            Sodium.crypto_secretstream_xchacha20poly1305_tag_final().toShort()
So you always use the final tag here? But then you can't look for the final tag when decrypting.
Shouldn't this be `crypto_secretstream_xchacha20poly1305_TAG_MESSAGE` or something similar?

2020-08-31 11:51 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +        //Got this magic number from https://github.com/joshjdevl/libsodium-jni/blob/master/src/test/java/org/libsodium/jni/crypto/SecretStreamTest.java#L48
This might change if the underlying implementation changes. There's `crypto_secretstream_xchacha20poly1305_statebytes` to get this number.

2020-08-31 11:51 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/encryption/EncryptionHandler.kt
> +    private fun encryptAndCipher(backupBytes: ByteArray, hash: ByteArray): Either<Failure, ByteArray> {
`encrypt` (what does the `Cipher` stand for?)

2020-08-31 11:51 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/encryption/EncryptionHandler.kt
> +            when (val ret: Int = crypto.generatePushMessagePart(state, cipherText, backupBytes)) {
So if I read this correct, we only call `generatePushMessagePart` once. But doesn't this defeat the purpose of having a streaming API (one of the few changes I've seen between v1 and v2 in the docs)?

2020-08-31 11:51 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/encryption/EncryptionHandler.kt
> +    //https://github.com/wearezeta/documentation/blob/master/topics/backup/use-cases/001-export-history.md
Dead link

2020-08-31 11:51 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/encryption/EncryptionHandler.kt
> +            checkExpectedKeySize(hash.size, crypto.encryptExpectedKeyBytes())
This function doesn't appear to actually check the size but only log. If there's a reason to check the size, we must abort if it doesn't match.

2020-08-31 11:51 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncyptionHeader.kt
> +    fun readEncryptedMetadata(encryptedBackup: File): Either<Failure, EncryptedBackupHeader> =
The terminology of `EncryptedBackupHeader` and encrypted metadata in general is pretty confusing. I don't see any encryption for the metadata here.

2020-08-31 11:51 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
> +    private fun decryptAndCipher(input: ByteArray, key: ByteArray): Either<Failure, ByteArray> {
`decrypt`?

2020-08-31 13:59 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/encryption/EncryptionHandler.kt
> +    //https://github.com/wearezeta/documentation/blob/master/topics/backup/use-cases/001-export-history.md
It should be https://github.com/wearezeta/documentation/blob/master/topics/backup/use-cases/001-export-history-v2.md (-v2.md at the end)

2020-08-31 15:37 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +            }.onFailure {
I'm ok with just failing.

2020-08-31 15:43 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +        //Got this magic number from https://github.com/joshjdevl/libsodium-jni/blob/master/src/test/java/org/libsodium/jni/crypto/SecretStreamTest.java#L48
For now, we don't want to support migration to the new version of Sodium. We can either update it right now (since we don't wnat to maintain backward compatibility with old backups) or leave it as it is. If we leave it as it is, then maybe in the future we will come back to this issue and then create some kind of converter for backups encrypted with old version.
So, we shouldn't have to worry about implementation changes for now, but I think we can switch from the magic number `52` to a call to that function.

2020-08-31 15:44 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            messageBytes,
I think `messageBytes` is `state`...

2020-08-31 15:44 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            Sodium.crypto_secretstream_xchacha20poly1305_tag_final().toShort()
Not sure. We have to look closer into this issue.

2020-08-31 15:46 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            Sodium.crypto_pwhash_alg_default()
Let's talk about it. Today I'm going home already but I'll try to set up a chat tomorrow for the three of us.

2020-08-31 15:48 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncyptionHeader.kt
> +    fun readEncryptedMetadata(encryptedBackup: File): Either<Failure, EncryptedBackupHeader> =
Right. Metadata is not encrypted. It's added on top of encrypted data.

2020-09-01 13:41 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +    internal fun hash(input: String, salt: ByteArray): Either<Failure, ByteArray> {
Ok, but it's still not a hash function 🙂 (you actually call `generatePwhashMessagePart` in here).
It's just about naming. But it's important to make clear that this is not a general purpose hash function like `Sha`

2020-09-01 13:41 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            Sodium.crypto_secretstream_xchacha20poly1305_tag_final().toShort()
This relates to the other comments about the streaming API I made. Actually using a streaming API makes sense for lager things. But if we don't do it, we should stick to the basic encryption funciton.

2020-09-01 14:01 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +    internal fun hash(input: String, salt: ByteArray): Either<Failure, ByteArray> {
I appreciate the feedback. I'll happily take suggestions if you have an idea of a name that would be deemed more readable from a security perspective

2020-09-01 14:07 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +    internal fun hash(input: String, salt: ByteArray): Either<Failure, ByteArray> {
Changed to hashWithMessagePart

2020-09-02 12:35 UTC, mejdoo commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +class Crypto(private val cryptoWrapper: CryptoWrapper) {
This looks much better as a refactoring for the first solution 👍

2020-09-02 12:48 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +class Crypto(private val cryptoWrapper: CryptoWrapper) {
Appreciate the feedback

2020-09-08 08:32 UTC, gizemb approved these changes

2020-09-08 11:39 UTC, merged