New backups (17+1r): RestoreBackUpUseCase + changes to MetadataHandler
wireapp/wire-android pull request #2998
Opened 2020-08-21 15:08 UTC by makingthematrix

This PR introduces a use case for restoring data from a backup to the database given a file previously created with `CreateBackUpUseCase`. The steps from `CreateBackUpUseCase` are reverted with the difference being that here we check if we are able to handle the backup version, written down in `metadata.json`. In practice, since this is the first ever backup version, we only check if the version from the file is the same as our current version, namely 1. In future, when we introduce a new version, we will also have to introduce a step for migrating older backups.

#### APK
[Download build #2603](http://10.10.124.11:8080/job/Pull%20Request%20Builder/2603/artifact/build/artifact/wire-dev-PR2998-2603.apk)
[Download build #2618](http://10.10.124.11:8080/job/Pull%20Request%20Builder/2618/artifact/build/artifact/wire-dev-PR2998-2618.apk)
[Download build #2623](http://10.10.124.11:8080/job/Pull%20Request%20Builder/2623/artifact/build/artifact/wire-dev-PR2998-2623.apk)
[Download build #2648](http://10.10.124.11:8080/job/Pull%20Request%20Builder/2648/artifact/build/artifact/wire-dev-PR2998-2648.apk)
[Download build #2652](http://10.10.124.11:8080/job/Pull%20Request%20Builder/2652/artifact/build/artifact/wire-dev-PR2998-2652.apk)

2020-08-25 08:12 UTC, BradleyWire requested changes

2020-08-25 08:12 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandler.kt
> +            val file = File(targetDir, FILENAME).apply {
I think it's more grammatically correct for`FILENAME` to be `FILE_NAME`

2020-08-25 08:12 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
> +            .find { it.isLeft }
It might be worth having a fail fast approach instead

2020-08-25 13:41 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
> +            .find { it.isLeft }
@BradleyWire : Something like `mapRight`, maybe? ;)

2020-08-27 11:34 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandler.kt
> +            val file = File(targetDir, FILENAME).apply {
ok, done in https://github.com/wireapp/wire-android/pull/3003/commits/092ca791e21c0a3ff3a997a3fb81dff2eae14d8c

2020-08-28 09:47 UTC, BradleyWire approved these changes

2020-08-28 10:34 UTC, gizemb requested changes

2020-08-28 10:34 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandler.kt
> +    fun checkMetaData(metaDataFile: File, userId: UserId): Either<Failure, Unit> =
a suggestion: I would personally leave this check to the use case and use this MetadataHandler as a data source only.

2020-08-28 10:34 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandler.kt
> +    fun generateMetaDataFile(userId: UserId, userHandle: String): Either<Failure, File> =
what about passing the `BackUpMetaData` here directly?

2020-08-28 10:34 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerTest.kt
> +    fun `given a valid metadata json, when it is checked, return success`() {
"when checkMetaData is called, then returns success"

2020-08-28 10:34 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerTest.kt
> +            .onSuccess { fail("UserId should be wrong") }
we should check whether it's a `UserIdInvalid` failure as well.

2020-08-28 10:34 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
> +package com.waz.zclient.feature.backup.usecase
The filename should be RestoreBackUpUseCase**Test**

2020-08-28 10:34 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
> +    private val encryptedFile = File("file_encrypted.zip")
can't you just mock with mockito?

2020-08-28 10:34 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
> +            assert(result.isRight)
this `assert` method does not fail the test case properly. please use `assertJ` or `junit` 

also, as an additional step it would be nice to check the error types too.

2020-08-28 14:38 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
> +    factory { MetaDataHandler(BACKUP_VERSION, get(named(METADATA + JSON)), get()) } bind MetaDataHandler::class
ok

2020-08-28 14:38 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandler.kt
> +    fun checkMetaData(metaDataFile: File, userId: UserId): Either<Failure, Unit> =
ok, done

2020-08-28 14:38 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandler.kt
> +    fun generateMetaDataFile(userId: UserId, userHandle: String): Either<Failure, File> =
ok

2020-08-28 14:38 UTC, makingthematrix commented on app/src/test/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerTest.kt
> +    fun `given a valid metadata json, when it is checked, return success`() {
ok

2020-08-28 14:38 UTC, makingthematrix commented on app/src/test/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerTest.kt
> +            .onSuccess { fail("UserId should be wrong") }
ok. I did that in other tests as well.

2020-08-28 14:38 UTC, makingthematrix commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
> +package com.waz.zclient.feature.backup.usecase
ok

2020-08-28 14:40 UTC, makingthematrix commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
> +    private val encryptedFile = File("file_encrypted.zip")
I think that this is actually simpler. A `File` is just a data structure. I can create it and pass it around and it never actually has to refer to any real file.

2020-08-28 14:40 UTC, makingthematrix commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
> +            assert(result.isRight)
ok

2020-08-28 15:07 UTC, gizemb approved these changes

2020-08-28 15:07 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
> +    internal fun checkMetaData(metaDataFile: File, userId: UserId): Either<Failure, Unit> =
`internal` keyword just hides the method from other modules. i think it should be `private` here.

2020-08-31 15:04 UTC, merged