[AN-7048] Add msg size limit
wireapp/wire-android pull request #3001
Opened 2020-08-24 15:40 UTC by CalumMcCall

## What's new in this PR?

### Issues

Currently Android allows the sending of any size text message, this PR adds a check which displays an error if the user attempts to send a message greater than 9000 chars in length. The jira ticket for this issue is [here](https://wearezeta.atlassian.net/browse/AN-7048).

### Testing

Testing was done manually.

2020-08-24 15:41 UTC, AndroidBob commented
Can one of the admins verify this patch?

2020-08-25 07:08 UTC, BradleyWire approved these changes

2020-08-25 07:09 UTC, BradleyWire commented
ok to test

2020-08-25 08:30 UTC, gizemb requested changes

2020-08-25 08:30 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/cursor/CursorController.scala
> +        .setPositiveButton(android.R.string.ok, null)
i suppose we shouldn't use `android.R` resources as they're not translated.

2020-08-25 14:44 UTC, CalumMcCall commented on app/src/main/scala/com/waz/zclient/cursor/CursorController.scala
> +        .setPositiveButton(android.R.string.ok, null)
Good catch!

2020-08-26 07:23 UTC, gizemb approved these changes

2020-08-26 12:00 UTC, merged