New backups (17+2r): Restoring data from the login screen
wireapp/wire-android pull request #3003
Opened 2020-08-25 13:24 UTC by makingthematrix

This is work in progress. For time being I commented out encryption.

2020-08-28 07:43 UTC, makingthematrix commented
build again

2020-08-28 10:20 UTC, mejdoo requested changes

2020-08-28 10:20 UTC, mejdoo commented on app/build.gradle
> -    implementation BuildDependencies.kotlin.coroutinesCore
why do we need to remove `coroutinesCore` dependency? Adding the proguard would be enough to avoid the crash

2020-08-28 10:20 UTC, mejdoo commented on app/src/main/java/com/waz/zclient/KotlinServices.kt
> +    private val backUpViewModel: BackUpViewModel by lazy { get<BackUpViewModel>() }
I recommend to use ` by viewModel` to inject viewModels

2020-08-28 10:20 UTC, mejdoo commented on app/src/main/java/com/waz/zclient/KotlinServices.kt
> +    private val backUpViewModel: BackUpViewModel by lazy { get<BackUpViewModel>() }
`private val backUpViewModel: BackUpViewModel by viewModel`

2020-08-28 10:20 UTC, mejdoo commented on app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
> +/*            .flatMap { file ->
avoid commenting code. Add TODO instead

2020-08-28 10:20 UTC, mejdoo commented on app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
> +/*        encryptionHandler.decrypt(params.file, params.userId, params.password).flatMap { file ->
same here

2020-08-28 10:20 UTC, mejdoo commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
> +/*    @Test
same thing for tests

2020-08-28 10:20 UTC, mejdoo commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
> +           // verify(encryptionHandler).encrypt(any(), any(), anyString())
here as well

2020-08-28 10:20 UTC, mejdoo commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
> +/*            `when`(it.encrypt(any(), any(), anyString())).thenReturn(
and here

2020-08-28 10:20 UTC, mejdoo commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
> +            //verify(encryptionHandler).decrypt(encryptedFile, userId, password)
and everywhere :)

2020-08-28 11:08 UTC, makingthematrix commented on app/src/main/java/com/waz/zclient/KotlinServices.kt
> +    private val backUpViewModel: BackUpViewModel by lazy { get<BackUpViewModel>() }
> `private val backUpViewModel: BackUpViewModel by viewModel`

This is not possible here. `KotlinServices` is not a fragment or an activity.

2020-08-28 14:41 UTC, makingthematrix commented on app/build.gradle
> -    implementation BuildDependencies.kotlin.coroutinesCore
I think we don't need to remove it, but in the same time it's not necessary, right?

2020-08-31 07:48 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/appentry/fragments/FirstLaunchAfterLoginFragment.scala
> +          displayError(R.string.backup_import_error_unknown, R.string.backup_import_error_unknown)
are the title and message same?

2020-08-31 07:48 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/utils/package.scala
> +    implicit def f0Unit(f: () => Unit): Function1[kotlin.Unit, kotlin.Unit] = new Function1[kotlin.Unit, kotlin.Unit]() {
where is this used?

2020-08-31 10:07 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/utils/package.scala
> +    implicit def f0Unit(f: () => Unit): Function1[kotlin.Unit, kotlin.Unit] = new Function1[kotlin.Unit, kotlin.Unit]() {
Turns out it isn't. I think in the middle of writing the code I must have changed the function signature. Now the standard `f0` function works.

2020-08-31 10:09 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/appentry/fragments/FirstLaunchAfterLoginFragment.scala
> +          displayError(R.string.backup_import_error_unknown, R.string.backup_import_error_unknown)
it should be `backup_import_error_unknown_title`. Changed.

2020-08-31 18:01 UTC, mejdoo commented on app/build.gradle
> -    implementation BuildDependencies.kotlin.coroutinesCore
It's required for Kotlin Coroutines, but somehow it's generated by an other dependency. I checked the external libraries and found there is `coroutines-core:1.3.0` and  `coroutines-core:1.3.7`.

2020-08-31 18:05 UTC, mejdoo commented on app/build.gradle
> -    implementation BuildDependencies.kotlin.coroutinesCore
![dep](https://user-images.githubusercontent.com/43655743/91751514-2a5c5400-ebc5-11ea-9e50-064ae33d1bc9.png)

2020-09-01 10:43 UTC, mejdoo requested changes

2020-09-01 10:43 UTC, mejdoo commented on app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
> +/*            .flatMap { file ->
Are you going to keep the commented code here and everywhere in this PR? Please use TODOs instead

2020-09-01 10:50 UTC, gizemb commented on app/build.gradle
> -    implementation BuildDependencies.kotlin.coroutinesCore
to see the dependency tree you can run this command: 
`./gradlew :app:dependencies`
there, you can see which dependency transitively brings kotlinx-coroutines-core:**1.3.0**

then you can exclude coroutines 1.3.0 from the main dependency

```
implementation(BuildDependencies.DependencyThatBringsOldCoroutines) {
        exclude(group = "org.jetbrains.kotlinx" module = "kotlinx-coroutines-core")
}
```

2020-09-01 10:52 UTC, gizemb approved these changes

2020-09-01 12:35 UTC, gizemb approved these changes

2020-09-01 12:51 UTC, mejdoo approved these changes

2020-09-01 12:58 UTC, merged