Add dialog for new backup warning
wireapp/wire-android pull request #3006
Opened 2020-09-02 16:14 UTC by gizemb

## What's new in this PR?

https://wearezeta.atlassian.net/browse/AN-7076

**We're still waiting for Product team to hand over the exact text. The PR is only open for general reviews.**

### Issues

With 3.55 version, we're going to release new back up functionality. However, new back ups aren't backward compatible. Therefore, we need to warn users beforehand about this update.

### Testing

Manually tested.

## Notes

- The pop up display is disabled for `internal` and `candidate` builds for easier QA automation tests. Once the RC package gets a green light, the `candidate` flag will be enabled for manual QA tests.
- This dialog is going to be removed in the next release. An [issue](https://wearezeta.atlassian.net/browse/AN-7079) is created for that purpose.

2020-09-03 07:04 UTC, BradleyWire approved these changes

2020-09-03 07:26 UTC, mejdoo requested changes

2020-09-03 07:26 UTC, mejdoo commented on app/build.gradle
> +            buildConfigField 'boolean', 'SHOW_BACK_UP_INCOMPATIBILITY_DIALOG', 'false'
Is this a request from QA? if not I think maybe we can get rid of `SHOW_BACK_UP_INCOMPATIBILITY_DIALOG`

2020-09-03 07:26 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/MainActivity.scala
> -  // TODO: remove after release 3.53
you can keep a todo 
`// TODO: remove after release 3.54`

2020-09-03 08:01 UTC, gizemb commented on app/build.gradle
> +            buildConfigField 'boolean', 'SHOW_BACK_UP_INCOMPATIBILITY_DIALOG', 'false'
I explained in the PR description that this is a QA request.

2020-09-03 08:05 UTC, mejdoo approved these changes

2020-09-04 06:32 UTC, makingthematrix approved these changes

2020-09-04 09:28 UTC, mejdoo requested changes

2020-09-04 09:28 UTC, mejdoo commented on app/src/main/res/values/strings.xml
> +    <string name="back_up_incompatibility_message">The next version of Wire (3.54) will contain a redesigned backup system. You will not be able to restore an existing backup file, so make sure to re
should b 3.55

2020-09-04 09:33 UTC, gizemb commented on app/src/main/res/values/strings.xml
> +    <string name="back_up_incompatibility_message">The next version of Wire (3.54) will contain a redesigned backup system. You will not be able to restore an existing backup file, so make sure to re
updated

2020-09-04 09:34 UTC, mejdoo approved these changes

2020-09-04 09:57 UTC, gizemb commented
build again

2020-09-04 10:20 UTC, gizemb commented
build again

2020-09-04 10:55 UTC, merged