Rewriting encryption/decryption back to Sodium v1
wireapp/wire-android pull request #3007
Opened 2020-09-03 08:12 UTC by makingthematrix

Work in progress.

After encrypting a backup, decryption fails.  For now I think that the problem is with a nonce (which we don't use and maybe we should). But that's only a theory. If you want to help, please checkout this PR, build it, install the apk on your phone, try encrypting and decrypting, and look through the code while you do it. Maybe you will find something. 
I made an extension method `ByteArray.describe` that displays a byte array in a human-friendly way.

2020-09-03 08:37 UTC, BradleyWire requested changes
Unit testing is lacking in this PR, I don't believe they all are passing in its current state

2020-09-03 08:37 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/core/extension/String.kt
> +fun ByteArray.describe(splitAt: Int = 4): String {
Would be good to unit test this

2020-09-03 08:37 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
> +        return when (crypto.decrypt(decrypted, cipherText, key)) {
Does this not break unit tests?

2020-09-03 08:37 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncryptionHeader.kt
> +            Logger.verbose(TAG, "android magic number: ${ANDROID_MAGIC_NUMBER.contentToString()}")
Is this log needed?

2020-09-03 08:37 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> -    internal fun initEncryptState(initKey: ByteArray, initHeader: ByteArray) =
You need to remove the test cases for these changes

2020-09-04 13:30 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
> +        return when (crypto.decrypt(decrypted, cipherText, key)) {
Yes. I fixed the tests.

2020-09-04 13:33 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> -    internal fun initEncryptState(initKey: ByteArray, initHeader: ByteArray) =
done

2020-09-04 13:35 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncryptionHeader.kt
> +            Logger.verbose(TAG, "android magic number: ${ANDROID_MAGIC_NUMBER.contentToString()}")
No. Removed.

2020-09-07 08:22 UTC, franziskuskiefer requested changes
Generally looks good.
A couple places need tests and there's one issue in encrypt and decrypt that needs fixing.

2020-09-07 08:22 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            intArrayOf(1),
This creates a signed 32-bit integer array. But we need a pointer to an unsigned 64-bit integer.

2020-09-07 08:22 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            byteArrayOf(),
We should add some associated data here... But let's skip for now.

2020-09-07 08:22 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
> +        val backupLength = backupFile.length() - TOTAL_HEADER_LENGTH
What happens if `backupFile.length() < TOTAL_HEADER_LENGTH`?

2020-09-07 08:22 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
> +        val decrypted = ByteArray(cipherText.size - crypto.aBytesLength())
What if `cipherText.size < crypto.aBytesLength()`?

2020-09-07 08:22 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncryptionHeader.kt
> +const val TOTAL_HEADER_LENGTH = ANDROID_MAGIC_NUMBER_LENGTH + 1 + 2 + SALT_LENGTH + UUID_HASH_LENGTH + 4 + 4 + NONCE_LENGTH
So I figured out why this isn't in the spec. iOS implements v1 and appears to actually use the streaming API, though that's not actually specified in v1. Let's go with this. All this needs to be cleaned up at some point though.

2020-09-07 14:15 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            intArrayOf(1),
Ok, then this appears to be an issue in the JNI wrapper of libsodium.

2020-09-07 14:19 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            intArrayOf(1),
What JNI bindings do we use here? This should be filed to get it fixed.

2020-09-07 15:20 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/core/extension/String.kt
> +fun ByteArray.describe(splitAt: Int = 4): String {
ok

2020-09-07 15:22 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
> +            intArrayOf(1),
@franziskuskiefer : `com.github.joshjdevl.libsodiumjni:libsodium-jni-aar:2.0.2`

2020-09-07 15:23 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
> +        val backupLength = backupFile.length() - TOTAL_HEADER_LENGTH
Right. I changed this code a bit and now it returns `Either.Left(DecryptionFailed)` if the file is too short. I also added a try/catch block for reading from the file.

2020-09-07 15:23 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
> +        val decrypted = ByteArray(cipherText.size - crypto.aBytesLength())
Changed similar as above.

2020-09-08 07:47 UTC, franziskuskiefer approved these changes
Thanks. lgtm now.
I filed https://github.com/joshjdevl/libsodium-jni/issues/142 to see if we can get the JNI issue fixed. It's nothing critical (we'll run out of memory before we run into an issue here ;).

2020-09-08 07:47 UTC, franziskuskiefer commented on app/src/main/kotlin/com/waz/zclient/core/extension/String.kt
> +            val tail = drop(size - splitAt).map { it.toInt() }.joinToString(", ")
Did you find this with the test you added?

2020-09-08 09:00 UTC, gizemb requested changes
I think structurally it's ok, but I request changes for the wrong `assert` usage in unit tests.

2020-09-08 09:00 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
> +        return pushMessage.takeIf { it == 0 }?.let { Either.Right(output) } ?: Either.Left(HashingFailed)
i'd prefer if/else here

2020-09-08 09:00 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncryptionHeader.kt
> +const val TOTAL_HEADER_LENGTH = ANDROID_MAGIC_NUMBER_LENGTH + 1 + 2 + SALT_LENGTH + UUID_HASH_LENGTH + 4 + 4 + NONCE_LENGTH
should we put TODOs for such things?

2020-09-08 09:00 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/core/extension/StringTest.kt
> +class StringTest : UnitTest() {
ByteArrayExtensionsTest

2020-09-08 09:00 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/CryptoTest.kt
>      fun `given hash size is same as expected size, then propagate success`() {
"when `checkExpectedKeySize` is called, "

2020-09-08 09:00 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/CryptoTest.kt
>      fun `given hash size is not the same as expected size, then propagate HashWrongSize error`() {
same here

2020-09-08 09:00 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/encryption/EncryptionHandlerTest.kt
> +            .onFailure { it shouldEqual HashWrongSize }
we can use assertLeft/assertRight now for convenience. Bradley added them.

2020-09-08 09:00 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
>              assert(result.isRight)
it should be changed to junit's `assertEquals`. could you also check if there are any other usages of this `assert`?

2020-09-08 09:23 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/core/extension/String.kt
> +            val tail = drop(size - splitAt).map { it.toInt() }.joinToString(", ")
@franziskuskiefer : It's not a bug. It's just a matter of what we want to see in the log statements. I thought that the `splitAt` argument may be understood as "I want this many bytes visible in the front and as well at the back". So now for `splitAt=4` the result will be `[1, 2, 3, 4, ..., 11, 12, 13, 14]`. Previously, `11` was be invisible.

2020-09-08 09:36 UTC, mejdoo requested changes

2020-09-08 09:36 UTC, mejdoo commented on app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
> +            File.createTempFile("wire_backup", ".zip").apply {
Avoid hardcoding. Create constants inside the companion object.

```
const val TMP_FILE_NAME = "wire_backup"
const val TMP_FILE_EXTENSION = ".zip"
```

2020-09-08 09:36 UTC, mejdoo commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCaseTest.kt
> +    private val zipFile = File("file_zipped.zip")
same for the tests

2020-09-08 09:46 UTC, makingthematrix commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
>              assert(result.isRight)
@gizemb : Quite a lot in various unit tests. I don't want to change them all now. I just fixed one more in the backups unit tests.

2020-09-08 10:03 UTC, gizemb commented on app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
>              assert(result.isRight)
@makingthematrix that's fair, no problem :)

2020-09-08 10:26 UTC, mejdoo approved these changes

2020-09-08 10:49 UTC, gizemb approved these changes

2020-09-08 11:36 UTC, merged