[Conference Calling] : Change mute/unmute icons in call overlay
wireapp/wire-android pull request #3014
Opened 2020-09-09 13:42 UTC by mejdoo

## What's new in this PR?

This PR addresses  a request from design to change mute/unmute icons in call overlay

UI spec https://app.zeplin.io/project/5eea48707411bb43f0f26711/screen/5f1ed25a0b1c6035c602d614

2020-09-09 13:49 UTC, mejdoo commented on app/src/main/java/com/waz/zclient/paintcode/WireStyleKit.java
> -        RectF bezierRect = CacheForMute.bezierRect;
The old code was drawing a vector drawable programmatically 😮 I simplified this by using `drawBitmap`

2020-09-09 13:49 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
> +    Signal(controller.isVideoCall, controller.isMuted, themeController.currentTheme).onUi {
Any suggestions how to optimize this duplication of `button.set(WireStyleKit...`? @makingthematrix

2020-09-09 15:15 UTC, makingthematrix requested changes

2020-09-09 15:15 UTC, makingthematrix commented on app/src/main/java/com/waz/zclient/paintcode/WireStyleKit.java
> -        RectF bezierRect = CacheForMute.bezierRect;
`WireStyleKit.java` is a file generated by a program used by our former designer. We still use some of the icons drawn this way instead of gettingthem from resources. 
Please leave this file as it is - even if we will never make any changes to it again.
Instead, you can create a new one in the same package and put `drawBitmap` in there together with new methods for drawing new icons.

2020-09-09 15:15 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
> +    Signal(controller.isVideoCall, controller.isMuted, themeController.currentTheme).onUi {
You can map it first:
```
    Signal(controller.isVideoCall, controller.isMuted, themeController.currentTheme).map {
      case (true, true, _) => Some(WireStyleKit.drawMuteDark _)
      case (true, false, _) => Some(WireStyleKit.drawUnmuteDark _)
      case (false, true, Theme.Dark) => Some(WireStyleKit.drawMuteDark _)
      case (false, true, Theme.Light) => Some(WireStyleKit.drawMuteLight _)
      case (false, false, Theme.Dark) => Some(WireStyleKit.drawUnmuteDark _)
      case (false, false, Theme.Light) => Some(WireStyleKit.drawUnmuteLight _) 
      case _ => None
    }.onUi {
      case Some(drawFunction) => button.set(drawFunction, R.string.incoming__controls__ongoing__mute, mute)
      case _ =>
    }
```

Mapping signals has an additional advantage that if the original signals change, but the mapped one stays the same (as here we use `drawMuteDark` etc. in two cases each), the `.onUi` will not be called.

2020-09-15 07:44 UTC, makingthematrix requested changes

2020-09-15 07:44 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
> +  private def drawBitmap(canvas: Canvas, targetFrame: RectF, color: Int, resourceId: Int, theme: Resources#Theme): Unit = {
Just a stylistic thing: You can user the `returning(...) { ... }` macro the same way you would use `.also { ... }` in Kotlin. This helps to initialize values close to their declarations. 
```
val paint = returning(new Paint){ p =>
  p.reset()
  ...
}
```
and so on.

2020-09-15 07:44 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
> +  def lightTheme: Resources#Theme = {
These two themes don't ever change, right? And are they used only in this class? If so, they can be `private lazy val` and you cal also use `returning` to initialize them.

2020-09-15 07:53 UTC, gizemb approved these changes

2020-09-15 13:11 UTC, BradleyWire approved these changes

2020-09-15 14:25 UTC, makingthematrix requested changes

2020-09-15 14:25 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
> +    val drawable = ContextUtils.getStyledDrawable(resourceId, theme).get
Don't use `.get` on an option, you can get a NullPointerException. Instead, put the code depending on `drawable` in `drawable.map { d => ... }`.

2020-09-15 14:58 UTC, makingthematrix approved these changes

2020-09-15 15:37 UTC, merged