Bump Android SDK 29
wireapp/wire-android pull request #3023
Opened 2020-09-15 15:06 UTC by makingthematrix

Work in progress.

Two main functionalities that were broken by this bump are sharing assets and the camera. The camera can probably be rewritten using the new API and we just need some time. The assets are a bit more tricky. Until now we relied on URIs to direct files. The proper way in SDK 29 would be to use `FileDescriptor`s instead, but that would mean a cascade of changes in many other places in our code. And I think we would still need to use the old way for older Androids. I'm tryin to find a middle solution.

## What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues. (Optional)_

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Testing

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

## Notes

_Specify here any other facts that you think are important for this issue. (Optional)_

2020-09-23 07:28 UTC, mejdoo requested changes

2020-09-23 07:28 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/ShareActivity.scala
> +      else if (WireApplication.ensureInitialized())
The name of the function is confusing. What do you mean by `ensureInitialized()`

2020-09-23 07:28 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/ShareActivity.scala
> +              if ("primary".equalsIgnoreCase(split(0))) Some(parse(dir + "/" + split(1)))
"primary" and "row" could be declared as constants

2020-09-28 11:17 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/ShareActivity.scala
> +      else if (WireApplication.ensureInitialized())
@mejdoo : It ensures that the Wire application is initialized. If it is, the method returns true. If it isn't, it tries to initialize the app - returns true if it's successful or false otherwise. It's used in situations when we want to access the app from outside - a notification, an Android service, etc. - and we don't know if Wire is already working in the background.

2020-09-29 13:51 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/ShareActivity.scala
> +              if ("primary".equalsIgnoreCase(split(0))) Some(parse(dir + "/" + split(1)))
ok, done

2020-10-09 08:07 UTC, mejdoo approved these changes

2020-10-12 15:51 UTC, gizemb approved these changes

2020-10-13 11:07 UTC, makingthematrix commented
build again

2020-10-13 12:37 UTC, makingthematrix commented
build again

2020-10-13 12:54 UTC, BradleyWire approved these changes

2020-10-13 12:54 UTC, BradleyWire commented on app/src/main/java/com/waz/zclient/utils/DeprecationUtils.java
> +        DownloadManager manager = (DownloadManager)context.getSystemService(Context.DOWNLOAD_SERVICE);
Formatting is off here

2020-10-13 12:54 UTC, BradleyWire commented on app/src/main/kotlin/com/waz/zclient/core/extension/Activity.kt
> +    val cf = currentFocus
`currentFocus?.let {}` would be better here

2020-10-14 08:05 UTC, makingthematrix commented
build again

2020-10-14 09:07 UTC, merged