Add Analytics For Pro Users
wireapp/wire-android pull request #3024
Opened 2020-09-15 22:17 UTC by CalumMcCall

## What's new in this PR?

### Issues

This PR reintroduces analytics for pro users. The existing analytics code is reused mostly, with most of the logic split between `GlobalTrackingController` and `TrackingService`. The PR is split between two commits, the first implemented the required functionality, and the second removes all of the now obsolete tracking code.

Issues AN-7074, AN-7070 and AN-7067 are addressed by this PR. This is mostly because the latter two tickets are quite small, especially 7067 is just a single line change(adding the pref in `UserPreferences`).

This PR does not handle multiple accounts. This has been left for future work. The analytics preference has been moved from `GlobalPreferences` to `UserPreferences`, to facilitate per-account analytics. Countly can be switched between user IDs by using the methods [here](https://support.count.ly/hc/en-us/articles/360037754031-Android-SDK#changing-a-device-id)

### Testing

Testing was done manually by logging into Countly and checking that the various event segments are being reported correctly.

2020-09-15 22:18 UTC, AndroidBob commented
Can one of the admins verify this patch?

2020-09-16 08:54 UTC, BradleyWire commented
ok to test

2020-09-16 08:56 UTC, mejdoo requested changes

2020-09-16 08:56 UTC, mejdoo commented on app/src/main/res/values/strings.xml
> +    <string name="pref_advanced_send_analytics_data_title">Telemetry sharing</string>
I found this copy in the design spec https://zpl.io/V03nNXo . Could you please double check with product.

title :  **Send anonymous usage data**
summary : **Usage data allows Wire to understand how the app is being used and how it can be improved. The data is anonymous and does not include the content of your communications (such as messages, files or calls).**

2020-09-16 10:55 UTC, CalumMcCall commented on app/src/main/res/values/strings.xml
> +    <string name="pref_advanced_send_analytics_data_title">Telemetry sharing</string>
Hey, so I can't access this link because I don't have an account. Is that from the spec there? Because that is the final version we should be using.

2020-09-16 11:15 UTC, mejdoo commented on app/src/main/res/values/strings.xml
> +    <string name="pref_advanced_send_analytics_data_title">Telemetry sharing</string>
yes that's it

2020-09-16 12:08 UTC, CalumMcCall commented on app/src/main/res/values/strings.xml
> +    <string name="pref_advanced_send_analytics_data_title">Telemetry sharing</string>
Great ok I'm waiting to hear back now. I'll keep you posted.

Can you confirm that the only copy on that page is the one you posted? There isn't one about analytics?

2020-09-16 12:26 UTC, mejdoo commented on app/src/main/res/values/strings.xml
> +    <string name="pref_advanced_send_analytics_data_title">Telemetry sharing</string>
**1st toggle :** 
**title** : Send anonymous crash reports 
**summary** : Send anonymous crash reports and basic data like version number and operating system to help Wire identify and solve issues in the app.

**2nd toggle :** 
**title**: Send anonymous usage data
**summary**: Usage data allows Wire to understand how the app is being used and how it can be improved. The data is anonymous and does not include the content of your communications (such as messages, files or calls).

**3rd toggle:** 
**title**: Receive newsletter
**summary**: Receive news and product updates from Wire via email.

2020-09-16 12:54 UTC, gizemb requested changes
I added some "suggestions" which are optional to do, or can be handled in a later PR. I'd like to see others fixed/replied in this PR :)

2020-09-16 12:54 UTC, gizemb commented on wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/tracking/TrackingService.scala
> +      case Some(z) => z.userPrefs(AnalyticsEnabled).signal
shouldn't we also check `AnalyticsEnabledCheck` here?

2020-09-16 12:54 UTC, gizemb commented on wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/tracking/TrackingService.scala
> +  override def msgDecryptionFailed(rConvId: RConvId, userId: UserId): Future[Unit] = isTrackingEnabled.head.flatMap {
suggestion: i'd create a `TrackingServiceProvider` which checks this `isTrackingEnabled`, and provides either `CountlyTrackingService` or `DisabledTrackingService`. then this "real" tracker doesn't have to check whether the tracking is enabled in every public method. Applying the Strategy Pattern, in essence.

in that scenario the consumers would always have to access the trackingService via provider. such as: `trackingServiceProvider.provide.msgDecryptionFailed()`

2020-09-16 12:54 UTC, gizemb commented on wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/MathUtils.java
> +    }
can we unit test these?

2020-09-16 12:54 UTC, gizemb commented on wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Preferences.scala
> +  lazy val AnalyticsEnabledCheck = PrefKey[Boolean]("analytics_enabled_checked", customDefault = false)
maybe we can rename these to `TrackingEnabled..` since the naming resembles the key of another preference.

2020-09-16 13:13 UTC, CalumMcCall commented on wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/tracking/TrackingService.scala
> +      case Some(z) => z.userPrefs(AnalyticsEnabled).signal
`AnalyticsEnabledCheck` is only used to perform a one time check to see if the preference should be set or not. So We don't need to check it here. I'll change the name, I think it could be clearer.

2020-09-16 13:20 UTC, CalumMcCall commented on default.json
> +  "countly_app_key": "9927e629a9302b8c800fc60055723362b0608f19"
Good question! The Countly docs don't mention having to keep it secret. We simply use it to identify the wire client to the Countly backend. It's analogous to a firebase api key(except with Countly, no data access is possible, only reporting), and those are exposed as described [here](https://stackoverflow.com/a/37484053/158703)

2020-09-16 16:57 UTC, CalumMcCall commented on wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/tracking/TrackingService.scala
> +  override def msgDecryptionFailed(rConvId: RConvId, userId: UserId): Future[Unit] = isTrackingEnabled.head.flatMap {
I really like this idea, thanks for the suggestion! I have tried doing it and I'm running into some issues with the injection. I think it would be best to wait and do this in a future PR. Since I think we could also maybe merge `TrackingService` and `GlobalTrackingController` at the same time and simplify things.

2020-09-16 17:29 UTC, CalumMcCall commented on wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/MathUtils.java
> +    }
done :)

2020-09-16 17:30 UTC, CalumMcCall commented
Thanks for the feedback @gizemb. I think I've addressed everything now except the suggestion to create a `TrackingServiceProvider`, which I propose we do at a later date(see comment above). The PR is now ready for re-review.

2020-09-16 17:37 UTC, CalumMcCall commented
build again

2020-09-17 11:13 UTC, gizemb approved these changes

2020-09-17 15:41 UTC, CalumMcCall commented
build again

2020-09-17 16:01 UTC, mejdoo approved these changes
Thanks @CalumMcCall for your support. I added DO NOT MERGE status to this PR. We will merge it and release this feature as soon as all analytics related tickets are done. Please branch from **add-bi** if you want to open more PRs.

2020-09-18 10:09 UTC, CalumMcCall commented
Ok great, sounds good!

2020-09-18 12:11 UTC, CalumMcCall commented
I've pushed a new commit as the spec was updated yesterday to add a new event. It's a quite minor change though.

2020-09-18 14:31 UTC, gizemb approved these changes

2020-09-18 21:24 UTC, mejdoo commented
build again

2020-09-30 15:59 UTC, merged