Camera to Camera2 - Part 1 - Migrate Individual Camera class.
wireapp/wire-android pull request #3034
Opened 2020-09-24 14:49 UTC by BradleyWire

## What's new in this PR?

### Issues

In order for us to overcome deprecation issues when we bump to android 29, we need to ensure that we have properly migrated those deprecated classes. 

### Causes

One of the larger deprecations is the use of the Camera API to allow the user to send images to each other. This means we need to migrate it over to the newer Camera2 API. 

### Solutions

In this PR you'll see that for every individual camera device there is a "WireCamera" implementation attached to it. I have migrated the larger part of the Camera device specifics in this PR. In Part 2 i'll be looking at integrating this Camera class into the current implementation and fixing any issues that arise from it.

2020-09-28 10:34 UTC, makingthematrix requested changes

2020-09-28 10:34 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +  private var cameraRequest: CaptureRequest.Builder = _
Avoid using uninitialized `var`s. Almost always it's better to use `Option` instead and set it to `None` initially. Like here.

2020-09-28 10:34 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +    cameraRequest.addTarget(surface)
Here - this can be moved to inside of `cameraRequest = returning(new CameraRequest.Builder) { ... }`

2020-09-28 10:34 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +        cameraRequest.set(CaptureRequest.CONTROL_MODE.asInstanceOf[CaptureRequest.Key[Any]], CameraMetadata.CONTROL_MODE_AUTO)
These three calls to `.set` can be as well moved to the inside of `cameraRequest = returning(new CameraRequest.Builder) { ... }` - note that they don't need any data computed in `onConfigured`.
And I think you don't need to use `asInstanceOf` here?...

2020-09-28 10:34 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +    cameraRequest = null
If `cameraRequest` is an `Option` you should set it to `None` instead.

2020-09-28 10:34 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +  private var previewSize: Option[PreviewSize] = None
I think something's wrong here. `previewSize` never changes from `None` to anything.

2020-09-28 10:34 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +  private var cameraSession: CameraCaptureSession = _
Please change it to `Option[CameraCaptureSession]` and set it to `None`. Then, when you use it, you can call `cameraSession.foreach { ... }`.

2020-09-28 10:34 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +  private var imageReader: ImageReader = _
It looks like `imageReader` can be `lazy val`. In `createCameraSession` all data used to create it is already known during the initialization.

2020-09-28 10:34 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +    camera.foreach {
Just a small trick: Instead of `Future.foreach` you can use `Future.collect` and inside define only the `case` you are interested in. So, `case None => // Do nothing` will not be necessary.

2020-09-28 10:34 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +  class CompareSizesByArea extends Comparator[Size] {
Is this used anywhere? (And even if it is, I think there should be a simpler way).

2020-10-01 11:07 UTC, makingthematrix requested changes

2020-10-01 11:07 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +      case session: CameraCaptureSession =>
This should be simply `cameraSession.foreach { session => ... }`. Better readability.

2020-10-01 11:07 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +      case device: CameraDevice =>
This should be `camera.foreach { device => ... }`

2020-10-01 11:07 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +      case session: CameraCaptureSession =>
`cameraSession.foreach { session => ... }`. And you can remove the outside `{}`.

2020-10-01 11:07 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/views/CameraPreviewTextureView.scala
> -  val orientationListener = returning {
I think this has to be assigned to a reference, because otherwise GC may destroy it at any moment...

2020-10-01 12:50 UTC, BradleyWire commented on app/src/main/scala/com/waz/zclient/camera/views/CameraPreviewTextureView.scala
> -  val orientationListener = returning {
Oh of course, that makes sense!

2020-10-01 13:17 UTC, BradleyWire commented on app/src/main/scala/com/waz/zclient/camera/controllers/GlobalCameraController.scala
> +      if (capabilities != null) {
I think this could work, what do you think? 

```
Option(characteristics.get(CameraCharacteristics.REQUEST_AVAILABLE_CAPABILITIES))
        .exists(_.contains(CameraMetadata.REQUEST_AVAILABLE_CAPABILITIES_BACKWARD_COMPATIBLE))
```

2020-10-02 13:28 UTC, makingthematrix approved these changes

2020-10-06 13:31 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +    }
more Scala-idiomatic way:

```
    def isBigEnough(size: Size) : Boolean { ... }

    val comparator = new CompareSizesByArea()
    val size = choices.filter(isBigEnough)
      .reduceOption((a, b) => comparator.min(a, b))
      .getOrElse(choices.head)
```

2020-10-06 13:31 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +    val largest = Collections.max(map.getOutputSizes(ImageFormat.JPEG).toList.asJava, new CompareSizesByArea)
can't we compute this without using Java lists and `Collections`?

2020-10-07 15:30 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +  private var orientation: Orientation = Orientation(0)
Bradley works now on the Android11 bug so I'm taking over this one.
I'll change this `0` here to a constant.

2020-10-07 15:31 UTC, makingthematrix commented on app/src/main/java/com/waz/zclient/camera/FlashMode.java
>          }
ok

2020-10-07 15:31 UTC, makingthematrix commented on app/src/main/java/com/waz/zclient/camera/FlashMode.java
>       */
ok

2020-10-07 15:48 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +    }
We can even do away without `CompareSizesByArea` - it can be turned into a fuction which we gives as an argument to `.maxBy` and `.minBy`.

2020-10-08 09:15 UTC, gizemb reviewed
looks good! can we test at least some of it?

2020-10-08 09:15 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +    val chosenSize = if (bigEnough.nonEmpty) bigEnough.minBy(bySizeComparison) else choices.head
nice!

2020-10-08 09:16 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
> +  private var orientation: Orientation = Orientation(0)
something like vertical or horizontal would be easier to read, but that's also ok

2020-10-13 08:17 UTC, BradleyWire commented
build agin

2020-10-13 09:25 UTC, BradleyWire commented
build again

2020-10-13 09:43 UTC, merged