Allow for custom HTTP Proxy settings in AndroidManifest.xml
wireapp/wire-android pull request #3037
Opened 2020-09-30 15:12 UTC by makingthematrix

fixes https://wearezeta.atlassian.net/browse/AN-7096

Our customer wants to be able to change the proxy settings in an already compiled APK.
Currently the proxy settings are hardcoded (taken from default.json or custom.json and put as constants in the BuildConfig class). However, the customer is able to open the APK, edit AndroidManifest.xml, and put it back. Then, when launching the application, we need to check if there are valid proxy details in AndroidManifest.xml, and if yes, use them instead of the ones from BuildConfig.

I did my best to make the code look good, but this is all pretty hacky from the very start. On top of the hackiness, we have two implementations of the proxy details: one in Scala, one i Kotlin. I decided not to connect them, but rather write the code twice. The proxy details are set early in the initialization and I feared that trying to make Scala use Kotlin at this point, or vice versa, may lead to unreadable code and even introduce some bugs.

On the other hand, I tried to make both implementations as similar as possible. This should help with readability.

2020-09-30 15:15 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/WireApplication.scala
> +      ProxyDetails(BuildConfig.HTTP_PROXY_URL, BuildConfig.HTTP_PROXY_PORT)
It's not possible to access BuildConfig from ZMessaging, so default url and port have to be given like this.

2020-10-02 13:21 UTC, gizemb requested changes

2020-10-02 13:21 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/WireApplication.scala
> +      ProxyDetails(BuildConfig.HTTP_PROXY_URL, BuildConfig.HTTP_PROXY_PORT)
what if we had an interface in `zmessaging`, and a concrete class implementing it `app`. and then we could just pass the concrete class in `app` module level without duplicating this `BuildConfig` or `HttpProxy` logic here. something like this:

in `zmessaging`:

```
interface ProxyParser {
    fun parseProxySettings() : Pair<String, Int>
}


class ZMessaging( ..., proxyParser: ProxyParser) {
   val globalModule = GlobalModuleImpl(..., proxyParser)
}


class GlobalModuleImpl {
   lazy val httpProxy = proxyParser.parseProxySettings()
}
```

in `app`:

```
class WireProxyParser(context: Context) : ProxyParser {
  override fun parseProxySettings() {
    //if we have in manifest, return it,
    //else BuilConfig.blabla
  }
}
```
and pass it to `ZMessaging.onCreate` here

2020-10-02 13:31 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/core/network/proxy/HttpProxy.kt
> +class HttpProxy(private val context: Context? = null, private val proxyDetails: ProxyDetails? = null) {
@gizemb : They're not supposed to be updated at runtime. Only at init.

2020-10-02 13:51 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/core/network/proxy/HttpProxy.kt
> +class HttpProxy(private val context: Context? = null, private val proxyDetails: ProxyDetails? = null) {
As I understand, there's always only one instance of proxy settings. A "factory" suggests for me that proxy settings are created one after another.

2020-10-02 13:52 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/core/network/proxy/HttpProxy.kt
> +class HttpProxy(private val context: Context? = null, private val proxyDetails: ProxyDetails? = null) {
Yeah, I admit this is clumsy... In unit tests, we can't provide the Android context, so instead we provide `proxyDetails` - the other argument. But this means that this class is made this way only because of unit tests.

2020-10-02 13:53 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/core/network/proxy/HttpProxy.kt
> +        }
But isn't it less readable?

2020-10-02 13:57 UTC, makingthematrix commented on wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/HttpProxy.scala
> +class HttpProxy(defaultProxyDetails: ProxyDetails, context: Option[Context] = None, proxyDetails: Option[ProxyDetails] = None) extends DerivedLogTag {
I thought that duplication of code here is okay, because otherwise the code would have to be more complicated than I wanted it to be.

2020-10-02 14:02 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/core/network/proxy/HttpProxy.kt
> +class HttpProxy(private val context: Context? = null, private val proxyDetails: ProxyDetails? = null) {
oh, ok. so in install time. I thought it was more dynamic, ok then :)

2020-10-02 14:03 UTC, gizemb commented on wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/HttpProxy.scala
> +class HttpProxy(defaultProxyDetails: ProxyDetails, context: Option[Context] = None, proxyDetails: Option[ProxyDetails] = None) extends DerivedLogTag {
but then imagine you change something here and forget to do it in the Kotlin side

2020-10-05 09:16 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/core/network/proxy/HttpProxy.kt
> +class HttpProxy(private val context: Context? = null, private val proxyDetails: ProxyDetails? = null) {
Changing the production code for testing purposes is most of the times not a good idea. It means either you're testing it wrongly, or you should change your implementation to be more testable. Here for example, we're not testing whether this class can read the proxy details from AndroidManifest file, so this class is not fully tested. The options I see are: 1. make it an integration test, 2. keep it as a unit test but use robolectric (I don't know if that works but worth a try) 3. change the class so that it gets a non-android-dependent parameter (we'd still have to test the other class that extracts the metadata though)

2020-10-05 09:16 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/core/network/proxy/HttpProxy.kt
> +        }
well, I would extract the middle part to a separate method to make it more readable
```
proxyDetails 
    ?: context?.let { extractMetadata(it) } 
    ?: DefaultProxyDetails
```

but if you don't like it, you don't have to do it :) it was a suggestion.

2020-10-05 09:16 UTC, gizemb commented on app/src/main/kotlin/com/waz/zclient/core/network/proxy/HttpProxy.kt
> +class HttpProxy(private val context: Context? = null, private val proxyDetails: ProxyDetails? = null) {
Changing the production code for testing purposes is most of the times not a good idea. It means either you're testing it wrongly, or you should change your implementation to be more testable. Here for example, we're not testing whether this class can read the proxy details from AndroidManifest file, so this class is not fully tested. The options I see are: 1. make it an integration test, 2. keep it as a unit test but use robolectric (I don't know if that works but worth a try) 3. change the class so that it gets a non-android-dependent parameter (we'd still have to test the other class that extracts the metadata though)

2020-10-06 15:52 UTC, gizemb approved these changes

2020-10-06 15:52 UTC, gizemb commented on wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/HttpProxySpec.scala
> +    val proxy = HttpProxy(metaDataService, customProxyDetails).proxy
I'm a bit confused by customProxyDetails and defaultProxyDetails. how do they differ?

2020-10-06 16:16 UTC, mejdoo requested changes

2020-10-06 16:16 UTC, mejdoo commented on app/src/main/java/com/waz/zclient/KotlinServices.kt
> +    fun setProxy(proxy: Proxy) {
you can get rid of this setter

2020-10-06 16:16 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/WireApplication.scala
> +      global.httpProxy.foreach(KotlinServices.INSTANCE.setProxy)
and call directly here `KotlinServices.INSTANCE.setHttpProxy`

2020-10-07 16:06 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/WireApplication.scala
> +      global.httpProxy.foreach(KotlinServices.INSTANCE.setProxy)
ok, done

2020-10-07 16:08 UTC, makingthematrix commented on wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/HttpProxySpec.scala
> +    val proxy = HttpProxy(metaDataService, customProxyDetails).proxy
I changed the name to `noProxyDetails` and in `customProxyDetails` I used different url and port to make sure they are used, not the ones which are set in metadata in other tests.

2020-10-08 08:34 UTC, mejdoo approved these changes

2020-10-08 08:43 UTC, merged