fix: make learn more links clickable for automation v2 [WPB-5888]
wireapp/wire-android pull request #3044
Opened 2024-05-28 10:28 UTC by saleniuk

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

This is a next approach to fix this issue: https://wearezeta.atlassian.net/browse/WPB-5888

### Issues

Previous fix, although looking fine on devices and layout inspector, was not working for automation, because it can't use `testTags` and it can't find inline content text composable.

### Solutions

In this PR, link text composable is extracted out of the inline content of the main text - inline content only contains a placeholder box to position the link correctly inside the text and to get valid size and position of that link to create the proper link text composable. Inline content is still used to make it work for all locales, no matter if the link is inside the text or at the end or if it's LTR or RTL. 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-05-28 10:36 UTC, yamilmedina approved these changes

2024-05-28 12:14 UTC, AndroidBob commented
Build [5042](https://10.10.124.134/job/AR-build-pipeline/5042/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9792735)(9792735)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9792735)(9792735)-staging-compat.apk)

2024-05-29 17:04 UTC, MohamadJaara requested changes
can you please make this change in develop only

2024-06-03 12:07 UTC, saleniuk commented
Closing as it's not meant to be merged into 4.7, PR for 4.8 is here: https://github.com/wireapp/wire-android/pull/3064

2024-06-03 12:07 UTC, closed without merging