Refactor avs versionning
wireapp/wire-android pull request #3054
Opened 2020-10-13 16:40 UTC by mejdoo

## What's new in this PR?

The current AVS versioning is messy. I did some refactoring to allow changing custom and public AVS versions from a single place `avs.gradle`. I couldn't move forward with Kotlin DSL due to the limitation of the Gradle Scala plugin.

**Please review during my absence  but don't merge it. I need to carry on some tests before merging**

2020-10-14 08:09 UTC, BradleyWire requested changes

2020-10-14 08:09 UTC, BradleyWire commented on wire-android-sync-engine/zmessaging/build.gradle
> +    testImplementation  "${rootProject.ext.avsGroup}:${rootProject.ext.avsName}:${rootProject.ext.avsVersion}"
Can we not just get the whole string directly from the project root ext closure? Rather than accessing three different values? Atleast then if we change anything in that file, we don't have to change every instance that uses it

2020-10-14 09:06 UTC, makingthematrix commented
I'm not able to access `androidx.room:room-migration:2.2.2` with these changes:

```
Could not determine the dependencies of task ':storage:kaptDebugKotlin'.
> Could not resolve all task dependencies for configuration ':storage:kapt'.
   > Could not resolve androidx.room:room-migration:[2.2.2].
     Required by:
         project :storage > androidx.room:room-compiler:2.2.2
      > Failed to list versions for androidx.room:room-migration.
         > Unable to load Maven meta-data from http://10.10.124.11:8081/nexus/content/groups/public/androidx/room/room-migration/maven-metadata.xml.
            > Could not get resource 'http://10.10.124.11:8081/nexus/content/groups/public/androidx/room/room-migration/maven-metadata.xml'.
               > Could not GET 'http://10.10.124.11:8081/nexus/content/groups/public/androidx/room/room-migration/maven-metadata.xml'.
                  > Connect to 10.10.124.11:8081 [/10.10.124.11] failed: connect timed out

```

2020-10-14 09:12 UTC, gizemb requested changes

2020-10-14 09:12 UTC, gizemb commented on build.gradle
> +        maven { url "http://10.10.124.11:8081/nexus/content/groups/public" }
AFAIK, that's a url that cannot be accessed outside our company VPN. Do we have plans to open it to public access? Otherwise, users outside the company would have to modify avs dependency declaration in order to build a successful Prod build.

2020-10-14 09:12 UTC, gizemb commented on wire-android-sync-engine/zmessaging/build.gradle
> +    implementation "${rootProject.ext.avsGroup}:${rootProject.ext.avsName}:${rootProject.ext.avsVersion}"
why did we change this to `implementation`? Was `compileOnly` not enough?

2020-10-19 12:33 UTC, mejdoo commented on wire-android-sync-engine/zmessaging/build.gradle
> +    testImplementation  "${rootProject.ext.avsGroup}:${rootProject.ext.avsName}:${rootProject.ext.avsVersion}"
Good idea. Will do it

2020-10-19 13:46 UTC, mejdoo commented on wire-android-sync-engine/zmessaging/build.gradle
> +    implementation "${rootProject.ext.avsGroup}:${rootProject.ext.avsName}:${rootProject.ext.avsVersion}"
I changed it back to `compileOnly`. It's enough.

2020-10-19 15:53 UTC, mejdoo commented on build.gradle
> +        maven { url "http://10.10.124.11:8081/nexus/content/groups/public" }
I think a fallback on failure mechanism can solve this issue. I'm investigating the possible options...

2020-10-20 16:28 UTC, mejdoo commented on avs/avs.gradle
> +def isConnected = !"curl -i -m 3 $nexusUrl".execute().err.text.contains("timed out")
This checks if someone has access to nexus repository or not (connected to wire VPN or not)

2020-10-20 16:29 UTC, mejdoo commented on build.gradle
> +        maven { url "http://10.10.124.11:8081/nexus/content/groups/public" }
Please review again, I updated the logic to enable GitHub users to build a successful Prod build.

2020-10-20 22:05 UTC, Gardosen requested changes
i left two comments which i think we need to take care off.

2020-10-20 22:05 UTC, Gardosen commented on avs/avs.gradle
> +if (shouldUseCustomAvs) {
i think this is incorrect?

on the old logic Prod Candidate and aPR received the public AVS Version and Internal, Experimental and Dev the internal avs version, as the check was looking for the taskname and decided by this
this logic turns the dice around on our jenkins as it first checks for the nexus connection (which is on our jenkins always true) and then checks the taskname but different then the old logic, the flag get's set to true, instead of false.
prod, candidate and aPR would received avsCustomVersion and Experimental Internal and Debug would received avsPublic Version.

2020-10-20 22:06 UTC, BradleyWire requested changes

2020-10-20 22:06 UTC, BradleyWire commented on avs/avs.gradle
> +String nexusUrl = "http://10.10.124.11:8081/nexus/content/groups/public"
I have some security concerns around exposing the private repo url publicly like this. With the `user.gradle` the identity was securely tucked away from the public eye. Let's run this past the security team.

2020-10-20 22:06 UTC, BradleyWire commented on avs/avs.gradle
> +def isConnected = !"curl -i -m 3 $nexusUrl".execute().err.text.contains("timed out")
This really seems like a hack. I'm sure we can find a more Gradle centric approach to achieving the same thing without executing a curl request everytime we need to define this repository.

2020-10-20 22:06 UTC, BradleyWire commented on avs/avs.gradle
> +            shouldUseCustomAvs = true
Do we not only want to use the custom version internally? So, this would need to be `false` if it's `prod` / `candidate` or `aPR`?

2020-10-21 06:02 UTC, Gardosen commented on avs/avs.gradle
> +String nexusUrl = "http://10.10.124.11:8081/nexus/content/groups/public"
i agree on this, we should stick to the file provided by jenkins when it comes to the nexus url implementation

2020-10-21 07:31 UTC, mejdoo commented on avs/avs.gradle
> +def isConnected = !"curl -i -m 3 $nexusUrl".execute().err.text.contains("timed out")
Suggestions are more than welcome. I tried with Gradle dependency substitution concept but it didn't fit with this case.

2020-10-21 07:34 UTC, mejdoo commented on avs/avs.gradle
> +String nexusUrl = "http://10.10.124.11:8081/nexus/content/groups/public"
Good catch! I will create an environment variable in Jenkins for nexusUrl.

2020-10-21 07:36 UTC, mejdoo commented on avs/avs.gradle
> +String nexusUrl = "http://10.10.124.11:8081/nexus/content/groups/public"
I will create an environment variable in Jenkins for `nexusUrl` to hide it from the public eye.

2020-10-21 07:55 UTC, mejdoo commented on avs/avs.gradle
> +            shouldUseCustomAvs = true
I think there is a confusion regarding the custom version because the old implementation is really clear. In fact, mostly the open source version is outdated and the custom version is up to date. So we have to use the custom version for production code (Prod and Candidate). If we want to use the custom avs versions locally, you have add this `user.gradle `file and connected to the vpn. In this PR, I want to get rid of the manual process caused by `user.gradle`.

2020-10-21 07:58 UTC, mejdoo commented on avs/avs.gradle
> +if (shouldUseCustomAvs) {
This is exactly the old implementation. I think there is a confusion regarding the custom version because the old implementation is not really clear. In fact, mostly the open source version is outdated and the custom version is up to date. So we have to use the custom version for production code (Prod and Candidate). If we want to use the custom avs versions locally, you have add user.gradle file and connected to the vpn. In this PR, I want to get rid of the manual process caused by this file.

2020-10-21 08:50 UTC, BradleyWire commented on avs/avs.gradle
> +            shouldUseCustomAvs = true
This is something that most certainly needs documenting.

2020-10-21 08:50 UTC, mejdoo commented
@Gardosen @BradleyWire @gizemb @android10 

I'm going to refactor the solution again to follow this approach : 

- VPN connected -> fetch always the custom version (Wire developers need just to connect to a VPN to make a build with a custom AVS version. No additional config is required)

- VPN not connected -> fetch always the open source version (Github users can compile the project without issues)

Note : Jenkins is part of the VPN network => It will use always the custom version for all the builds (Prod, Candidate, Internal, Dev...)

2020-10-21 08:51 UTC, mejdoo commented on avs/avs.gradle
> +            shouldUseCustomAvs = true
I have an other idea to get rid of this weird implementation...Please read my comment below.

2020-10-21 08:53 UTC, android10 commented
@mejdoo I think it is a ok workaround for the time being. Especially for this version of the app and given the current state of the codebase.

2020-10-21 10:36 UTC, gizemb commented on app/build.gradle
> +        exclude group: 'com.wearezeta.avs', module: 'avs'
can we do `exclude group: avsGroup, module: avsName` instead?

2020-10-21 11:27 UTC, mejdoo commented on app/build.gradle
> +        exclude group: 'com.wearezeta.avs', module: 'avs'
yes possible, I need in this case to define them inside `ext { }`

2020-10-21 13:46 UTC, mejdoo commented on avs/avs.gradle
> +String nexusUrl = "http://10.10.124.11:8081/nexus/content/groups/public"
ok.  After hiding nexusUrl  inside an environment variable in Jenkins, we need to add one manual step to create a build with a custom AVS version locally. Documentation will follow up...

2020-10-21 14:24 UTC, mejdoo commented
> @Gardosen @BradleyWire @gizemb @android10
> 
> I'm going to refactor the solution again to follow this approach :
> 
> * VPN connected -> fetch always the custom version (Wire developers need just to connect to a VPN to make a build with a custom AVS version. No additional config is required)
> * VPN not connected -> fetch always the open source version (Github users can compile the project without issues)
> 
> Note : Jenkins is part of the VPN network => It will use always the custom version for all the builds (Prod, Candidate, Internal, Dev...)

I adjusted this solution as we have to hide nexus url in Jenkins so it's no more possible to check whether we are connected to a VPN or not in the local machine (dev environment). Please follow the documentation provided in the PR's description.

2020-10-21 14:33 UTC, mejdoo commented on avs/avs.gradle
> +def isConnected = !"curl -i -m 3 $nexusUrl".execute().err.text.contains("timed out")
I did some updates...no more need to use `curl`...

2020-10-21 14:44 UTC, gizemb approved these changes

2020-10-21 16:14 UTC, Gardosen approved these changes
the changes looks really nice. 
i also like the local file implementation.

LGTM Approved 👍

2020-10-22 08:29 UTC, BradleyWire approved these changes
Love the gradle centric approach! Much cleaner 💪

2020-10-22 08:43 UTC, merged