Build System Improvement - Part 1 : Refactor the main build.gradle file
wireapp/wire-android pull request #3073
Opened 2020-10-27 16:23 UTC by mejdoo

## What's new in this PR?

This PR comes with a refactoring solution to improve the readability the current build system which is very complicated and hard to understand.

## Main improvements
- Move the gradle tasks and configurations to a different scripts
- Manage the versioning from a single place : `Dependencies.kt`

2020-10-27 16:26 UTC, mejdoo commented on build.gradle
> -// FIXME: License header is disabled because it breaks compilation
I will try to solve this in future PRs. I coudn't find a quick solution.

2020-10-27 16:27 UTC, mejdoo commented on scripts/license.gradle
> +//TODO fix compilation issue for the license plugin
I will try to solve this in future PRs. I coudn't find a quick solution.

2020-10-27 16:35 UTC, android10 approved these changes
:+1:

2020-10-28 12:22 UTC, mejdoo commented on zmessaging/build.gradle
> +apply plugin: 'kotlin-android-extensions'
@gizemb here is the fix for the warning.

```
> Configure project :zmessaging
Kotlin plugin should be enabled before 'kotlin-android-extensions'
```

2020-10-28 13:48 UTC, gizemb requested changes
I love how organized this looks! just had a couple of comments

2020-10-28 13:48 UTC, gizemb commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val SCALA = "1.6"
`const val SCALA_BUILD_PLUGIN`

the version of the Scala language that we use is 2.12 and `SCALA = 1.6` seems misleading here

2020-10-28 13:48 UTC, gizemb commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val GRADLE = "3.2.1"
`const val ANDROID_GRADLE_PLUGIN`

build plugin version and Gradle version itself are separate things https://developer.android.com/studio/releases/gradle-plugin#updating-gradle

2020-10-28 13:48 UTC, gizemb commented on scripts/ci.gradle
> +task clean(type: Delete) {
this is not necessarily related to ci

2020-10-28 13:48 UTC, gizemb commented on zmessaging/build.gradle
> -    maven { url "https://dl.bintray.com/wire-android/third-party/" }
if these repos are only needed for this module, I think it's better to keep them here. if you apply this to `allProjects`, then let's say `app` module will go through these directories too when looking for its dependencies, which might add up to total build time.

2020-10-28 14:13 UTC, mejdoo commented on scripts/ci.gradle
> +task clean(type: Delete) {
where do you suggest to move this?

2020-10-28 14:22 UTC, BradleyWire requested changes

2020-10-28 14:22 UTC, BradleyWire commented on build.gradle
> +apply from: "./scripts/customization.gradle"
What is customisation?

2020-10-28 14:22 UTC, BradleyWire commented on build.gradle
> +apply from: "./scripts/detekt.gradle"
`detekt` and `jacoco` could in theory be merged into one script called quality

2020-10-28 14:22 UTC, BradleyWire commented on scripts/customization.gradle
> +import groovy.json.JsonOutput
I don't think customisation is meaningful enough name to tell us what it does, is there not a terminology wire uses for this process at all?

2020-10-28 14:22 UTC, BradleyWire commented on scripts/license.gradle
> +license {
the name would read better as `licensing.gradle`, this reads that this is a license

2020-10-28 14:22 UTC, BradleyWire commented on custom-checkstyle/build.gradle
> +targetCompatibility =  Versions.TARGET_COMPATIBILITY_VERSION
extra space before `Versions`

2020-10-28 14:29 UTC, mejdoo commented on zmessaging/build.gradle
> -    maven { url "https://dl.bintray.com/wire-android/third-party/" }
Good catch! I Will keep only those repositories below `zmessaging`

```
 maven { url "https://oss.sonatype.org/content/repositories/releases" }
 maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
```

The rest are already fetched in `allprojects`

2020-10-28 14:32 UTC, mejdoo commented on build.gradle
> +apply from: "./scripts/detekt.gradle"
There is a `quality.gradle`  file below `app/config` containing lint configuration. I will merge them all in the next PR.

2020-10-28 15:22 UTC, mejdoo commented on scripts/customization.gradle
> +import groovy.json.JsonOutput
All the code here is about custom configuration. What do you suggest as name?

2020-10-28 15:41 UTC, gizemb commented on scripts/ci.gradle
> +task clean(type: Delete) {
i don't know. maybe directly into build.gradle? it's not very important though, it can stay here as well

2020-10-28 15:42 UTC, gizemb approved these changes

2020-10-28 15:48 UTC, BradleyWire commented on scripts/customization.gradle
> +import groovy.json.JsonOutput
custombuild maybe?

2020-10-28 15:49 UTC, BradleyWire approved these changes

2020-10-28 16:29 UTC, mejdoo commented
build again

2020-10-28 17:04 UTC, merged

2020-10-29 13:56 UTC, mejdoo commented on scripts/customization.gradle
> +import groovy.json.JsonOutput
I will rename it to `whitelabel`. I think we use this term at wire.

https://wearezeta.atlassian.net/wiki/spaces/PROD/pages/1704675/Custom+versions+and+whitelabel