Build System Improvement - Part2
wireapp/wire-android pull request #3083
Opened 2020-11-04 12:34 UTC by mejdoo

## What's new in this PR?

This is a follow up of #3073 

### Main improvements

- Merge quality related stuff in one gradle file `quality.gradle` and move all the configs below `/config` folder
- Improve versioning
- Manage FeatureFlags from Kotlin DSL.

2020-11-04 12:53 UTC, mejdoo commented
build again

2020-11-04 13:29 UTC, gizemb requested changes

2020-11-04 13:29 UTC, gizemb commented on buildSrc/src/main/kotlin/FeatureFlags.kt
> +    const val REGITRATION = false
typo

2020-11-04 13:29 UTC, gizemb commented on scripts/quality.gradle
> +    if (project.plugins.hasPlugin('com.android.application')) {
what about library projects? storage, zmessaging, etc?

2020-11-04 13:29 UTC, gizemb commented on scripts/quality.gradle
> +                // set to true to turn off analysis progress reporting by lint
we can get rid of those comments IMO. isn't there a lint task documentation somewhere?

2020-11-04 13:29 UTC, gizemb commented on scripts/quality.gradle
> +
a little formatting would be nice

2020-11-04 13:29 UTC, gizemb commented on scripts/quality.gradle
> +
I think we can break this thing down even more into their own files and add
```
apply from checkstyle
apply from pmd
...
```
here

2020-11-04 13:29 UTC, gizemb commented on app/config/lint-config.xml
> -<?xml version="1.0" encoding="UTF-8"?>
what was the difference between this config and `lint-config-with-unused.xml` exactly?

2020-11-04 14:25 UTC, mejdoo commented on scripts/quality.gradle
> +
I started by doing a single gradle file for each section in #3073 `detekt.gradle` and `jacoco.gradle`. Then, @BradleyWire suggested to do it in a single place `quality.gadle`. It's not a requirement but think it's better to follow the same approach of `wire-android-reloaded`.

2020-11-04 14:34 UTC, mejdoo commented on scripts/quality.gradle
> +                // set to true to turn off analysis progress reporting by lint
No idea about the documentation, but I'm fine with deleting those comments.

2020-11-04 14:35 UTC, BradleyWire commented on scripts/quality.gradle
> +
Yes, we can still do a single quality.gradle file and apply that but the quality.gradle file can have its own plugins

2020-11-05 09:43 UTC, android10 approved these changes
:+1: I'm approving but I would definitely like to start a discussion or have an answer to my comments.

2020-11-05 09:43 UTC, android10 commented on build.gradle
> +apply from: "./scripts/whitelabel.gradle"
:+1:

2020-11-05 09:43 UTC, android10 commented on scripts/licensing.gradle
> +subprojects {
We have to be careful with this, because we do not want to get ownership over code taken from other projects. For Example there are some files that were taken from my project...I do not mind to be honest, but changing the author could bring even legal problems and as far as I understand, that will apply to all files right?

2020-11-05 09:43 UTC, android10 commented on scripts/quality.gradle
> +
I jump in here, because I was the one putting everything inside the ```quality``` file. 
At the time being, the file is not big and perfectly understandable. Personally I found this the best way of organizing scripts by ```aspects```. If we start creating these tiny scripts, we are loosing consistency, since there are aspects and technologies mixed up. 

We have 2 options, either we put everything in one file as soon as the file does not grow until it turns into a God Script or we change our strategy and organization related to scripts. 
If you feel like the second option, please drop your suggestions.

2020-11-05 10:00 UTC, mejdoo commented on scripts/licensing.gradle
> +subprojects {
Good point, I totally agree with you opinion regarding copyright. This will apply to all files in the all the modules with the following extensions `.java .scala, gradle,xml.` `.kt` is missing btw. What do you suggest then? Should we ignore some specific files or disable completely the licensing plugin to stay in the safe side?

2020-11-05 10:24 UTC, android10 commented on scripts/licensing.gradle
> +subprojects {
I would suggest a way to check whether this header exist first. If does not, then add it. 
I do not know the plugin and I do it manually in my projects, actually the IDE does it for me within new files.

In any case, we have to be responsible if we are copying code from other projects. It is a commitment. 
So just make sure we are taking any ownership from code that does not belong to us.

2020-11-05 10:25 UTC, android10 commented on scripts/licensing.gradle
> +subprojects {
I guess we have to investigate a bit here, Unless someone else has experience on this topic. 
cc @makingthematrix @gizemb @BradleyWire

2020-11-05 12:33 UTC, makingthematrix commented on scripts/licensing.gradle
> +subprojects {
As far as I understand, every source code file should start with the header. If the code contains a snipped taken from elsewhere, that code should additionally be preceded by a comment about who is the author and where was it taken from. We should copy-paste whole files from other projects.

2020-11-06 13:06 UTC, gizemb commented on scripts/quality.gradle
> +
I personally find it big, but I don't mind if it stays as it is. the main reason why I requested changes was the [typo](https://github.com/wireapp/wire-android/pull/3083#discussion_r517330115) and [this](https://github.com/wireapp/wire-android/pull/3083#discussion_r517336875) comment. the typo has been fixed but I still don't have an answer for the other question. As soon as I get an answer to it I can revoke my CR.

2020-11-08 21:33 UTC, mejdoo commented on scripts/quality.gradle
> +    if (project.plugins.hasPlugin('com.android.application')) {
lint was enabled only for the `app` module, if that makes sense we can enabled as well for the other modules.

2020-11-09 09:19 UTC, gizemb commented on scripts/quality.gradle
> +    if (project.plugins.hasPlugin('com.android.application')) {
hmm, ok. I saw that there is another configuration ready for library modules, but didn't know that it was disabled for them.

2020-11-09 09:19 UTC, gizemb approved these changes

2021-01-15 09:18 UTC, mejdoo commented
I'm closing this deprecated  PR. The job was failing due to a lint config problem. I don't want to invest more time on it. We have other priorities.

2021-01-15 09:18 UTC, closed without merging