feat: Shared tracking id
wireapp/wire-android pull request #3092
Opened 2020-11-12 11:35 UTC by makingthematrix

implements https://wearezeta.atlassian.net/browse/SQCORE-121

The tracking ids are already present in the client code, but now every device has its own tracking id and they are not connected. This PR introduces sharing tracking ids among devices belonging to the same user. The general idea is that every time a new device is added to the user, that device generates a new tracking id and sends it to all other devices. This happens also when the device updates for the first time to the version containing this feature. We are aware there is a risk of race condition when two devices send their tracking ids in the same time, but we decided it's small enough and we can ignore it.

The change requires an update in generic-message-proto. The new version is 1.27.1. It contains a new field called DataTransfer and inside it there's a field trackingIdentifier which is the trackingId that should replace the local tracking id. In the future, DataTransfer might contain more fields, but for now it's only this one, so in the Scala code I made a shortcut that let us easier unpack the tracking id from the incoming message.

I also added a new button to the Dev Settings that can be used to generate a new tracking id without the need to remove and re-add a device. This can help in testing.

2020-11-12 11:46 UTC, BradleyWire requested changes

2020-11-12 11:46 UTC, BradleyWire commented on app/src/main/res/values/strings_no_translate.xml
> +    <string translatable="false" name="pref_dev_random_tracking_id_summary">Generate a new, random value for the CountlyTrackingId preference. Use it to test history loss.</string>
I know this is only a developer's button, but, I don't think this should be so tightly coupled to Countly, atleast if we change the analytics service we use we don't have to worry about changing strings with it

2020-11-12 11:46 UTC, BradleyWire commented on zmessaging/src/main/scala/com/waz/sync/handler/TrackingSyncHandler.scala
> +class TrackingSyncHandler(selfUserId: UserId, otrSync: OtrSyncHandler) {
Are we able to test this?

2020-11-12 11:46 UTC, BradleyWire commented on app/src/main/scala/com/waz/zclient/tracking/GlobalTrackingController.scala
> +      _             =  if (isNew) am.storage.userPrefs(CountlyTrackingId) := Some(id)
Again, I don't think we should be sharing implementation details here around `CountlyTrackingId` incase we change the service in the future. This can be something like `CurrentTrackingId`. 

Obviously, if the value of `CountlyTrackingId` has `Countly` in the key name, we can't avoid that change without migrating data but the variable name is still fine to change.

2020-11-12 11:46 UTC, BradleyWire commented on app/src/main/scala/com/waz/zclient/MainActivity.scala
> +      _                <- if(analyticsEnabled && isProUser) trackingCtrl.init() else Future.successful(())
Formatting is off here with `if(` rather than `if ( ` (and above)

2020-11-12 13:31 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/sync/handler/TrackingSyncHandler.scala
> +class TrackingSyncHandler(selfUserId: UserId, otrSync: OtrSyncHandler) {
@BradleyWire : Rught now, this handler has only one trivial method that only calls `OtrSyncHandler.postOtrMessage`. We have unit tests for `OtrSyncHandler`.

2020-11-12 13:31 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/tracking/GlobalTrackingController.scala
> +      _             =  if (isNew) am.storage.userPrefs(CountlyTrackingId) := Some(id)
ok

2020-11-12 13:32 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/MainActivity.scala
> +      _                <- if(analyticsEnabled && isProUser) trackingCtrl.init() else Future.successful(())
ok

2020-11-12 13:32 UTC, makingthematrix commented on app/src/main/res/values/strings_no_translate.xml
> +    <string translatable="false" name="pref_dev_random_tracking_id_summary">Generate a new, random value for the CountlyTrackingId preference. Use it to test history loss.</string>
ok

2020-11-12 13:52 UTC, makingthematrix commented
build again

2020-11-13 09:38 UTC, BradleyWire approved these changes

2020-11-13 13:21 UTC, mejdoo approved these changes

2020-11-13 13:24 UTC, merged