[Calling]: Feature : Maximize/Minimize video/screen share on double click
wireapp/wire-android pull request #3097
Opened 2020-11-19 16:56 UTC by mejdoo

## What's new in this PR?

Once this PR is merged, it will be possible during a call to maximise a video or screen share of any user just by a double click.

https://wearezeta.atlassian.net/browse/SQCALL-9

2020-11-19 17:08 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +  def clearVideoGrid(): Unit = {
The VideoGrid should be cleared and reloaded otherwise AVS native lib will be crashing. There is a limitation right now, we can't use `com.waz.avs.VideoRenderer` with same parameters in different views, at the same time.

2020-11-20 08:13 UTC, BradleyWire requested changes

2020-11-20 08:13 UTC, BradleyWire commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +    val fragment = new FullScreenVideoFragment
You can use the `returning(new FullScreenVideoFragment) { fragment =>  }` here to clean it up a little

2020-11-20 08:13 UTC, BradleyWire commented on app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
> +    case (true, false, 0 | 1 | 2) => View.GONE
formatting here the => need to line up

2020-11-20 08:13 UTC, BradleyWire commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +  val Tag = classOf[FullScreenVideoFragment].getName
Do we want this like this? In case of obfuscation this may not display the correct tag

2020-11-20 08:13 UTC, BradleyWire commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +        .map(_.getOrElse(participant, VideoState.Unknown)).onUi {
Is this formatted properly? the indentation looks off for the `case` values

2020-11-20 08:13 UTC, BradleyWire commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +  private lazy val controller = inject[CallController]
If we're grouping these values together, we normally align the `=`

2020-11-20 08:13 UTC, BradleyWire commented on app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
> +      case _                 => view.fadeIn()
formatting here too

2020-11-20 10:26 UTC, gizemb approved these changes

2020-11-20 10:26 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +      else userVideoView = new OtherVideoView(getContext, participant)
this doesn't need to be a `var` I guess?
`val userVideoView = if (...) SelfVideoView() else OtherVideoView()`

2020-11-20 10:26 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +  }
there's a really tight coupling between this fragment and CallingFragment. don't we have any other way to communicate?

2020-11-20 12:57 UTC, makingthematrix requested changes

2020-11-20 12:57 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +  private val maxVideoPreviews = 12
Constants should be defined in the companion object, and the name should start with the capital letter.

2020-11-20 12:57 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +    controller.theme.map(themeController.getTheme).onUi(theme => videoGrid.foreach(_.setBackgroundColor(getStyledColor(R.attr.wireBackgroundColor, theme))))
Instead of subscribing to the signal here, put it in the `videoGrid` definition:
```
private lazy val videoGrid = returning(view[GridLayout](R.id.video_grid)) { vh =>
  controller.theme.map(themeController.getTheme).onUi { theme =>
    vh.foreach { ... }
  }
}
```

Tak a look at other places this pattern is used.

2020-11-20 12:57 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +          v.onDoubleClick.onUi { _ =>
Subscribing to a signal or an event stream inside a method may sometimes lead to unclear behaviour. It's more readable if `v.onDoubleClick.onUi { _ => ... }` is defined on the main level and then, inside the `onUi{ _ => ... }` the app checks what should happen because of the click. But I'm not sure yet how to do it in this particular case. I can look more into it on Monday.

2020-11-20 12:57 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +      videoGrid.foreach { v =>
This can also be moved to the definition of `videoGrid`.

2020-11-20 12:57 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +      else userVideoView = new OtherVideoView(getContext, participant)
I think in general `userVideoView` should be a lazy val defined on the class level and in its initialization block we can check the bundle for info what should it be and should it subscribe to any signal.

2020-11-20 12:57 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +      controller.allVideoReceiveStates
This subscription to the signal should also be on the class level. Generally, if for some reason it's not to difficult, the logic should be inverted: First subscribe, then inside the subscription decide what to do. Or, even better, you can use `.filter`, `.map`, `.flatMap`, and `.collect` to build the logic into the signal or event stream.

2020-11-20 12:57 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
> +    case (true, false, 0 | 1 | 2) => View.GONE
And also either please put all three original signals in one line, or each in a separate line.

2020-11-20 12:57 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
> +        controller.allVideoReceiveStates.map(_.getOrElse(participant, VideoState.Unknown)).onUi {
Same issue as before - it would be better to have a subscription to a signal on the class level, and logic what to do when the signal changes implmeneted inside the subscription, or through map, filter, etc.

2020-11-20 12:57 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
> +  case class Participant(userId: UserId, clientId: ClientId, muted: Boolean = false) extends Serializable
Do you really need to extend Serializable? (btw, I'm not sure, but a case class should do it already, I think...)

2020-11-20 15:11 UTC, mejdoo commented on app/build.gradle
> +        buildConfigField 'boolean', 'CALLING_VVM_MAXIMIZE_MINIMIZE_VIDEO', "$rootProject.ext.callingVvmMaximizeMinimizeVideo"
I wanted to specify the squad and the parent feature name. Anyway, `MAXIMIZE_MINIMIZE_VIDEO` would be enough.

2020-11-20 15:35 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +    val fragment = new FullScreenVideoFragment
ok done

2020-11-20 15:43 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +  val Tag = classOf[FullScreenVideoFragment].getName
I just followed what it was done in other fragments.

2020-11-20 15:46 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +  private lazy val controller = inject[CallController]
Is there anyway to define auto formatting rule for Scala in Android studio? Those classed are mostly auto formatted... @makingthematrix any idea?

2020-11-20 15:48 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +  private val maxVideoPreviews = 12
so not all the name should be capitalised like Java or Kotlin style?

2020-11-20 16:02 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +  private val maxVideoPreviews = 12
@mejdoo : You can see `CONSTANT_LIKE_THIS` too, but at least for me this style means this is aconstant that should be resolved at compile time, and `ConstantLikeThis` is just a magic number, a default string, etc. I agree it's not consistent.

2020-11-20 16:04 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +  private val maxVideoPreviews = 12
ok anyway, I changed this to `MaxVideoPreviews` in the companion object.

2020-11-23 09:05 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +  }
An event stream defined in a controller connecting the two fragments could help:
```
val initVideo = EventStream[Unit]() // in CallingController, for example
initVideo.foreach(callingFragment.initVideoGrid)
...
callingController.initVideo ! (()) // here in FullScreenVideoFragment
```

2020-11-23 09:06 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +  val Tag = classOf[FullScreenVideoFragment].getName
There was never a problem with this, to be honest. I'm fine with this.

2020-11-23 09:07 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +  private lazy val controller = inject[CallController]
This alignment is not automatic. It's just for readability and it's up to the person writing the code. If I see that something can be easier to write with some small changes in alignment then I do it, but it's not a requirement.

2020-11-23 09:51 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +  val Tag = classOf[FullScreenVideoFragment].getName
we don't obfuscate the code

2020-11-23 09:56 UTC, BradleyWire approved these changes

2020-11-23 14:25 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +      else userVideoView = new OtherVideoView(getContext, participant)
@makingthematrix  I didn't get how you wanna refactor this. 

I think @gizemb proposal looks fine.

2020-11-23 15:04 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +  }
ok done!

2020-11-23 15:14 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +      videoGrid.foreach { v =>
I moved this block outside of the videoGrid lazy loading declaration because I need to clear and initialize the videoGrid multiple times when I maximize/minimize any idea. Otherwise, AVS lib will crash.

2020-11-23 15:33 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +      controller.allVideoReceiveStates
Not sure how to do it in this case, as I need to call `minimizeVideo(container, userVideoView)` with the parameter  `userVideoView` created inside `showMaximizedVideo(..)`.

2020-11-23 15:41 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
> +        controller.allVideoReceiveStates.map(_.getOrElse(participant, VideoState.Unknown)).onUi {
This is an old implementation, I just moved the classes to separate files. Could you provide a code snippet for the refactoring.  In this case,`registerHandler()` is called from the classes `SelfVideoView` and `OtherVideoView` which extends from `UserVideoView`.

2020-11-23 16:04 UTC, mejdoo commented on zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
> +  case class Participant(userId: UserId, clientId: ClientId, muted: Boolean = false) extends Serializable
right! not needed :)

2020-11-25 14:45 UTC, makingthematrix commented
I pushed a commit with changes. My main issue was with this very big and complicated method, `initVideoGrid` which created a signal and subscribed to it - that could potentially lead to memory leaks. I tried to split the signal into a few smaller ones and connect them only later, and also move the subscription to the videoGrid `ViewHolder`. This way, the subscription can be managed automatically and for sure there will be only one at the time.

I still don't like that we subscribe to double clicks inside the method, but I think there's no risk in that.

2020-11-25 14:50 UTC, mejdoo commented
> I pushed a commit with changes. My main issue was with this very big and complicated method, `initVideoGrid` which created a signal and subscribed to it - that could potentially lead to memory leaks. I tried to split the signal into a few smaller ones and connect them only later, and also move the subscription to the videoGrid `ViewHolder`. This way, the subscription can be managed automatically and for sure there will be only one at the time.
> 
> I still don't like that we subscribe to double clicks inside the method, but now I think about it, there shouldn't be any risk in that...
> 
> I also changed a few things in `CallController`. Many signals there are initialized at once even if they are never used because there's no video call. I added `lazy` to their declarations.

Ok thank you. Let me test again the feature before merging...

2020-11-26 12:44 UTC, makingthematrix requested changes

2020-11-26 12:44 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +    fullScreenVideoContainer.foreach { container =>
Similar to the issue in `CallingFragment`:
If you make subscriptions like this inside methods, you risk memory leaks and unpredicted behaviour. Every call to the method will create a new subscription and they all will be called next time the signal refreshes, so the same logic will be executed many times when it should be executed only once.

Instead, make subscriptions to signals on the class level (or, in this case, inside `returning(view[FrameLayout](R.id.full_screen_video_container)) { ... }`), and let the method call update some data which in turn will make the signal refresh. 

For example, as I understand, we can have only one participant with maximized video. You can then create a source signal:
```
val maximizedParticipant = Signal[Option[Participant]]()
```
And `selfParticipant` is already a signal in the controller: `controller.selfParticipant`.
So, inside that `returning` clause you can zip together all three:
```
Signal.zip(
  maximizedParticipant,
  controller.selfParticipant,
  controller.allVideoReceiveStates
).foreach { ... }
```
And there you can choose to minimize and maximize views.

2020-11-26 12:44 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +      else new OtherVideoView(getContext, participant)
I'd suggest you create a var `Map[Participant, UserVideoView]` and create new views only if they're not already there.

Also, I'm not sure about comparisons of the whole `Participant` case class. Aren't we only interested in user ids of participants?

2020-11-26 12:44 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +        initGridLayout()
`initGridLayout()` creates a new subscription every time it's called. I don't think this is what you want here. Instead, only one subscription to the signal should be made, in line 54, and here you only refresh the grid once. That means, you take `userGridInfo.head` and call `refreshGridLayout` with its data. 
So, something like this:
```
videoGridInfo.head.foreach { case (selfParticipant, videoUsers, infos, participants, isVideoBeingSent) =>
  controller.isFullScreenEnabled.head.collect { false =>
    vh.foreach { grid =>
      refreshVideoGrid(grid, selfParticipant, videoUsers, infos, participants, isVideoBeingSent)
     }
  }
}
```
It looks similar to `initGridLayout`, but the calls to `.head` make all the difference.

2020-11-26 12:44 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +          val isFullScreenEnabled = controller.isFullScreenEnabled.currentValue.getOrElse(false)
Don't access the value of the signal like this. Here you can zip those two signals instead: 
```
Signal.zip(videoGrodInfo, controller.isFullScreenEnabled).foreach {
  case ((sp, vu, info, ps, is), false) => ...
  case _ => 
}
```

2020-11-30 13:09 UTC, makingthematrix approved these changes

2020-11-30 14:11 UTC, merged