SSO password lock
wireapp/wire-android pull request #3101
Opened 2020-11-24 19:53 UTC by makingthematrix

fixes https://wearezeta.atlassian.net/browse/SQCORE-170

An SSO user does not have a login password, and so they can't use the app lock functionality. This PR solves it by introducing a special password, only for SSO users, which is stored - hashed - in user preferences. There is a new dialog which opens after the login if the app lock is enabled and the password is not set. Later on, that password is used in all places where for a standard user the login password would be used. The password can be cleared only by deleting local data.
The "passcode" switch in the Options was changed to a new view which now contains the switch and a new button that the SSO user can use to change their password. For a standard user this button is invisible.

I use the Sodium library for hashing. I decided to move around the code for this so I will be able to write unit tests with "dummy" hashing implementation.

I still work on the UI of the new password dialog as well. The logic should stay the same and you can already review it.

2020-12-01 12:03 UTC, mejdoo requested changes

2020-12-01 12:22 UTC, franziskuskiefer requested changes
Is the encryption of the password done in a different PR? I only see the password being hashed here.

2020-12-01 12:22 UTC, franziskuskiefer commented on app/src/main/scala/com/waz/zclient/common/controllers/global/SodiumHandler.scala
> +    val outputSize = Sodium.crypto_aead_chacha20poly1305_keybytes()
Why do you get output size for ChachaPoly? I though we were using AES GCM?

2020-12-01 12:22 UTC, franziskuskiefer commented on app/src/main/scala/com/waz/zclient/common/controllers/global/PasswordController.scala
> +      encryptedPwd <- hash(pwd.str)
This is only hashed. Not encrypted.

2020-12-02 18:55 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/common/controllers/global/SodiumHandler.scala
> +    val outputSize = Sodium.crypto_aead_chacha20poly1305_keybytes()
It should be the same. This is how we also use it in backup encryption.

2020-12-02 20:08 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/common/controllers/global/PasswordController.scala
> +      encryptedPwd <- hash(pwd.str)
fixed

2020-12-02 20:09 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/preferences/dialogs/NewPasswordDialog.scala
> +    val builder = new AlertDialog.Builder(getActivity)
Ok. It didn't really make the code shorter. I had to introduce two more utility methods in `ViewUtils`. But it's more consistent now.

2020-12-02 20:09 UTC, makingthematrix commented on app/src/main/res/layout/new_password_dialog.xml
> +            android:layout_width="match_parent"
ok, done

2020-12-03 10:23 UTC, makingthematrix commented
build again

2020-12-03 10:41 UTC, franziskuskiefer requested changes
Thanks for the update.
Tthere's a lot here in `AESUtils` that really needs to go away 😬 . But that's unrelated to this PR.
I added comments to the encryption. I think there are a couple issues.

2020-12-03 10:41 UTC, franziskuskiefer commented on zmessaging/src/main/scala/com/waz/model/AESKey.scala
> +  def bytes: Array[Byte] = AESUtils.base64(str)
Unrelated to this really. But why is the input base64 encoded before hashed? This really mustn't happen. Or do I misunderstand what's happening here?

2020-12-03 10:41 UTC, franziskuskiefer commented on zmessaging/src/main/scala/com/waz/utils/crypto/AESUtils.scala
> +    returning(Cipher.getInstance("AES/CBC/PKCS5Padding")) {
Do we use this function anywhere? If so, we have to stop.

2020-12-03 10:41 UTC, franziskuskiefer commented on zmessaging/src/main/scala/com/waz/utils/crypto/AESUtils.scala
> +    val iv = cipher.getIV
According to the [docs](https://developer.android.com/reference/javax/crypto/Cipher#getIV()) this returns nothing because you didn't set an IV before. From what I understand how the API works you have to generate your own random IV and pass it in through the `GCMParameterSpec`.

2020-12-03 10:41 UTC, franziskuskiefer commented on zmessaging/src/main/scala/com/waz/utils/crypto/AESUtils.scala
> +    val encrypted = cipher.doFinal(AESUtils.base64(textToEncrypt))
Don't use `base64` anywhere please.

2020-12-03 10:41 UTC, franziskuskiefer commented on app/src/main/scala/com/waz/zclient/common/controllers/global/SodiumHandler.scala
> +    val outputSize = Sodium.crypto_aead_chacha20poly1305_keybytes()
It's a very different use case here. But it doesn't really matter. It's just a little odd to take this for the output size.

2020-12-03 12:10 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/utils/crypto/AESUtils.scala
> +    val iv = cipher.getIV
@franziskuskiefer :
This generates a random IV. Look at the "Default value" chapter in here: https://proandroiddev.com/secure-data-in-android-initialization-vector-6ca1c659762c

2020-12-03 12:22 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/utils/crypto/AESUtils.scala
> +    returning(Cipher.getInstance("AES/CBC/PKCS5Padding")) {
Yes. We use it a lot for encrypting and decrypting messages.

2020-12-03 13:04 UTC, franziskuskiefer commented on zmessaging/src/main/scala/com/waz/utils/crypto/AESUtils.scala
> +    val iv = cipher.getIV
Yeah, the docs don't actually say if this is set or not... Did you check what the IV is here?

2020-12-03 13:08 UTC, franziskuskiefer commented on zmessaging/src/main/scala/com/waz/utils/crypto/AESUtils.scala
> +    returning(Cipher.getInstance("AES/CBC/PKCS5Padding")) {
I filed https://wearezeta.atlassian.net/browse/SQCORE-266 to look into this.

2020-12-03 16:48 UTC, gizemb requested changes

2020-12-03 16:48 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/preferences/dialogs/NewPasswordDialog.scala
> +      clicked = ! clicked
if you're just toggling the state, maybe it would be easier to use a `CheckBox`. 
Then you wouldn't have to keep track of the clicked state here and instead just check `isChecked` property or use an `OnCheckedChangeListener`. 
Also, you could use a `StateListDrawable` for the icon as well, to let the system change the background image, depending on `state_checked`. This would make the `showHide()` logic much easier. https://developer.android.com/guide/topics/resources/drawable-resource#StateList


or in any ways, I think an `ImageButton` would be more appropriate instead of an `ImageView` here.

2020-12-03 16:48 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/preferences/dialogs/NewPasswordDialog.scala
> +    ViewUtils.showAlertDialog(
I think you should only create and return the dialog here, not show it 🤔

2020-12-03 16:48 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/preferences/dialogs/RequestPasswordDialog.scala
> +    val dialog = ViewUtils.showAlertDialog(
again, `showAlertDialog` method shows the dialog. but I feel like we just want to create it here. is that what we want?

2020-12-03 16:48 UTC, gizemb commented on zmessaging/src/main/scala/com/waz/content/Preferences.scala
> +  lazy val SSOPasswordIv = PrefKey[Option[String]]("sso_password_iv", customDefault = None)
what does iv stand for?

2020-12-03 16:48 UTC, gizemb commented on zmessaging/src/main/scala/com/waz/service/AccountsService.scala
> +  def isActiveAccountSSO:   Signal[Boolean] = Signal.const(true) // activeAccount.map(_.exists(_.ssoId.isDefined))
I think this is left from debugging?

2020-12-03 19:22 UTC, makingthematrix commented on app/src/main/java/com/waz/zclient/utils/ViewUtils.java
> +                                              boolean shouldUseNegativeButton) {
@gizemb : About this one and your other comments on `ViewUtils.showAlertDialog` - Ok. I'm already rewriting quite a lot so I can also rewrite this class completely, so it will be easier to use for all alert dialogs.

2020-12-03 19:23 UTC, makingthematrix commented on app/src/main/res/layout/app_lock_layout.xml
> +        android:layout_height="match_parent">
Because It was always like that :) I'll remove it.

2020-12-03 19:24 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/preferences/dialogs/NewPasswordDialog.scala
> +      clicked = ! clicked
I will try, but isn't it basically the same thing?

2020-12-03 19:27 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/content/Preferences.scala
> +  lazy val SSOPasswordIv = PrefKey[Option[String]]("sso_password_iv", customDefault = None)
Initialization Vector. It's a 12-bytes-long array. Every time a new password is encrypted, we need to generate an IV, use it in encryption, and then store it. Then the IV needs to be used for decryption. In a way it's like a part of the encrypted password - which is also an array of bytes - but the encryption functionality treats them as separate entities, so I decided to store them separately too.

2020-12-03 19:27 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/AccountsService.scala
> +  def isActiveAccountSSO:   Signal[Boolean] = Signal.const(true) // activeAccount.map(_.exists(_.ssoId.isDefined))
Whoops.

2020-12-03 22:36 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/preferences/dialogs/RequestPasswordDialog.scala
> +    val dialog = ViewUtils.showAlertDialog(
We want both. And this happens so often in the app that this shortcut method was created. `ViewUtils.showAlertDialog` creates a dialog and displays it immediately.

2020-12-04 09:52 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/preferences/dialogs/NewPasswordDialog.scala
> +    ViewUtils.showAlertDialog(
Will do it in the next PR.

2020-12-04 09:53 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/preferences/dialogs/RequestPasswordDialog.scala
> +    val dialog = ViewUtils.showAlertDialog(
Ok, but I'd like to do it in the separate PR.

2020-12-04 09:53 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/preferences/dialogs/NewPasswordDialog.scala
> +      clicked = ! clicked
done

2020-12-04 09:54 UTC, makingthematrix commented on app/src/main/res/layout/app_lock_layout.xml
> +        android:layout_height="match_parent">
done

2020-12-04 09:54 UTC, makingthematrix commented on app/src/main/java/com/waz/zclient/utils/ViewUtils.java
> +                                              boolean shouldUseNegativeButton) {
next PR

2020-12-04 09:54 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/utils/crypto/AESUtils.scala
> +    val encrypted = cipher.doFinal(AESUtils.base64(textToEncrypt))
ok, changed.

2020-12-04 09:55 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/utils/crypto/AESUtils.scala
> +    val iv = cipher.getIV
Yes. All looks good.

2020-12-04 09:57 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/model/AESKey.scala
> +  def bytes: Array[Byte] = AESUtils.base64(str)
Base64 proved to me to be the simplest way to convert byte arrays to strings and back. Many other methods fail for non-Latin characters or... or just fail. The Java standard library clearly didn't do a good job in this regard.

2020-12-04 10:09 UTC, android10 commented on zmessaging/src/main/scala/com/waz/content/Preferences.scala
> +  lazy val SSOPasswordIv = PrefKey[Option[String]]("sso_password_iv", customDefault = None)
I'm with @gizemb and make clear the intention of the variable with its name. 
Maybe `SSOPasswordInitVector`? or if that is too long `SSOPassInitVector`?

2020-12-04 10:11 UTC, android10 reviewed
Hard one for me. No request changes from my side since I rely on the experts here.

2020-12-04 10:13 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/preferences/dialogs/NewPasswordDialog.scala
> +    val builder = new AlertDialog.Builder(getActivity)
I reverted this. I'll do it in another PR.

2020-12-04 10:41 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/content/Preferences.scala
> +  lazy val SSOPasswordIv = PrefKey[Option[String]]("sso_password_iv", customDefault = None)
@android10 : IV is the standard short name for it in the encryption functionality and in Android. Up there we have `val iv = cipher.getIV`. I'd prefer to keep it. It's just for consistency.

2020-12-04 12:58 UTC, mejdoo approved these changes
I approved to unblock you. Looking forward to see the next PR for alertDialog refactoring.

2020-12-04 12:58 UTC, mejdoo commented on app/src/main/java/com/waz/zclient/utils/ViewUtils.java
> +                                              boolean shouldUseNegativeButton) {
maybe you can just remove those methods if they are unused now

2020-12-04 15:10 UTC, gizemb requested changes

2020-12-04 15:10 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/preferences/dialogs/NewPasswordDialog.scala
> +        (isDarkTheme, isClicked) match {
if you use the StateListDrawable as I mentioned, you can simplify it here.
Create a drawable xml under res/drawable (let's say `drawable_white.xml`):

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_checked="true" android:drawable="@drawable/ic_visibility_off_white_18dp"/>
    <item android:drawable="@drawable/ic_visibility_white_18dp"/>
</selector>
```

You should do another one for black icons - `drawable_black.xml`

And then all you have to do is set the checkbox background once:

```
private lazy val showHideButton = returning(findById[CheckBox](root, R.id.new_password_showhide)) { checkbox => 
    checkbox.setButtonDrawable(if (isDarkTheme) R.drawable.drawable_white else R.drawable.drawable_black)
    checkbox.setOnCheckedChangeListener {
         //you don't need to worry about the drawable here anymore
    }
}
```

2020-12-04 16:51 UTC, gizemb approved these changes

2020-12-04 17:14 UTC, merged