[Calling] Feature : Active speaker - part 1
wireapp/wire-android pull request #3106
Opened 2020-12-01 14:56 UTC by mejdoo

This PR introduces a new calling feature **Active Speaker Detection**:

## What's new ?

- Colored and pulsing microphone for the active speakers in participants list.
- Colored and pulsing microphone for the active speakers in the gridView.

## WIP

- Colored frame around the active speakers in the video grid.

Design spec : https://zpl.io/bAoEQeP

2020-12-04 10:17 UTC, android10 approved these changes
:+1: I understand no tests due to first the codebase state and second much UI stuff. Good job anyway, the functionality looks promising.

2020-12-04 10:27 UTC, makingthematrix requested changes

2020-12-04 10:27 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
> +  val activeSpeakers                  = currentCall.map(_.activeSpeakers)
Keeping all those fields as `lazy val`s may help a bit with initialization of a call on weaker phones. Or just to keep it consistent.

2020-12-04 10:27 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
> +    activeSpeakers.map(_.find { activeSpeaker =>
Instead of map/find you can use `activeSpeakers.contains`.

2020-12-04 10:27 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
> +      isActiveSpeaker ! isActive
Instead of `callController.isActiveSpeaker(user.id, user.clientId).foreach { isActive =>` what you probably want here is `callController.isActiveSpeaker(user.id, user.clientId).head.foreach { isActive =>`. The `.head` here (or `.future` now in wire-signals) will work only once. If you call `.foreach` on the signal, you will create a subscription.

2020-12-04 10:27 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/call/Avs.scala
> +            val activeSpeakers = activeSpeakersChange.audio_levels.map(m => ActiveSpeaker(m.userid, m.clientid, m.audio_level)).toSet
isn't this `.fold(()) { activeSpeakersChange => ... }` here the same as `.foreach { activeSpeakersChange => ... }`?

2020-12-04 16:04 UTC, mejdoo commented on zmessaging/src/main/scala/com/waz/service/call/Avs.scala
> +            val activeSpeakers = activeSpeakersChange.audio_levels.map(m => ActiveSpeaker(m.userid, m.clientid, m.audio_level)).toSet
Sorry, I didn't get what you mean here :)

2020-12-04 16:38 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
> +      isActiveSpeaker ! isActive
I need a subscription in this case, otherwise the microphone state won't behave as excepted.

2020-12-07 09:01 UTC, makingthematrix requested changes

2020-12-07 09:01 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/call/Avs.scala
> +            val activeSpeakers = activeSpeakersChange.audio_levels.map(m => ActiveSpeaker(m.userid, m.clientid, m.audio_level)).toSet
`ActiveSpeakerChangeDecoder.decode(data)` returns an option, and you want to do something only if that option contains `activeSpeakersChange`. You do nothing if the option is empty, and you also don't want to return any result. So, you can replace `.fold(())` with simpler `.foreach`.

2020-12-07 10:23 UTC, makingthematrix approved these changes

2020-12-07 17:38 UTC, merged