feat: Allow session reset from the decryption error message
wireapp/wire-android pull request #3118
Opened 2020-12-14 16:46 UTC by makingthematrix

see https://wearezeta.atlassian.net/browse/SQCORE-30

When the user sees an error message that the decryption failed, they should be able to fix that simply by clicking on it, instead of having to go the other user's profile and reset the session manually from there to every device of that other user.

This is the first part of the feature. It consists of a changed error message, the functionality that triggers session reset, and
a new "fixed error" system message which replaces the original error message. The other part of the feature consists of the error dialog, the spinner which appears inside the error message instead of the centre of the screen, and a change to MessageData and its Dao which will makes us able to reset the session only to the device from which the error message came from. (Now we reset sessions to all devices of the given user).
To change the error into the fixed error I made a change in how MessageViewPart accesses MessageData. It would be good to check if the new way doesn't slow down the app too much. If yes, I have an idea how to fix it.

I also used this opportunity to refactor the code a bit. Message view parts are old code - I wante to improve its readibility.
And I found that there is some unused code left after the recent changes in audio/video functionality.

2021-01-13 13:54 UTC, mejdoo requested changes

2021-01-13 13:54 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
> -  protected val nameTextView = returning(findById[TextView](R.id.name_text_view)) { view =>
I wonder why did you remove this? It' not related to sessions reset and also will broke the calling experience. Could you please address Scala styling issue outside of this PR?

2021-01-13 13:54 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
> +  this.onClick(() => callController.controlsClick(true), () => onDoubleClick ! {})
is this exactly equivalent to ?

```
this.onClick({
     callController.controlsClick(true)
   }, {
     onDoubleClick ! {}
   })
```

2021-01-13 13:59 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
> -  protected val nameTextView = returning(findById[TextView](R.id.name_text_view)) { view =>
It could be refactored by we shouldn't remove this, otherwise the name of the users won't be shown correctly in the gridView.

2021-01-13 14:00 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
> -  private val pictureId: Signal[Picture] = for {
right, this one is no more used 👍

2021-01-13 14:03 UTC, mejdoo requested changes

2021-01-13 14:03 UTC, mejdoo commented on build.gradle
> +    activeSpeakers = false
please keep it true for testing purposes...

2021-01-13 14:08 UTC, mejdoo requested changes

2021-01-13 14:08 UTC, mejdoo commented on storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
> +            USER_DATABASE_MIGRATION_126_TO_127,
I think you can rid of 👍 
```
USER_DATABASE_MIGRATION_126_TO_127,
USER_DATABASE_MIGRATION_127_TO_128,
USER_DATABASE_MIGRATION_128_TO_129
```

just keep  `USER_DATABASE_MIGRATION_129_TO_130`

2021-01-13 15:01 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
> -  protected val nameTextView = returning(findById[TextView](R.id.name_text_view)) { view =>
Right. This is the case.

I think I remember when, in another place in the code, I wondered what to do with a field that wasn't used anywhere in the code, but was necessary to initialize the layout. Android Studio claims such fields are unused and it's easy to make a mistake and delete them. I'll bring it back.

2021-01-13 16:24 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
> +  this.onClick(() => callController.controlsClick(true), () => onDoubleClick ! {})
Yes. It's just a cosmetic change. I thought the new version is easier to read. It shows right away that we pass a function as an argument. The older version could be understood as if we were passing the results of those two operations.

2021-01-13 16:58 UTC, makingthematrix commented on storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
> +            USER_DATABASE_MIGRATION_126_TO_127,
I will do this later, in https://wearezeta.atlassian.net/browse/SQCORE-371 .

2021-01-14 09:02 UTC, mejdoo approved these changes

2021-01-19 08:18 UTC, makingthematrix commented
build again

2021-01-19 08:44 UTC, merged