Feature/active speakers part 2
wireapp/wire-android pull request #3122
Opened 2020-12-17 09:13 UTC by mejdoo

This is a follow up for the calling feature **Active Speaker Detection** introduced in #3106 

## What's new ?

- Highlight the top 4 active speakers having their video enabled during a conference call.
- Switching between All participants and active speakers using the toggle in call controls.
- Manage the case when there is no active speakers

Design spec : https://zpl.io/bAoEQeP

2020-12-17 11:13 UTC, makingthematrix requested changes

2020-12-17 11:13 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
> +        activeParticipantsWithVideo.toSeq
Try this instead:
```
videoUsers.filter { participant => 
  activeSpeakers.exists { speaker => 
    participant.clientId == speaker.clientId && participant.userId == speaker.userId
  }
}
```

2020-12-17 11:13 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +
You can turn this `var` into a val and assign the result of if/else to it:
```
val gridViews = 
  if (showTopSpeakers) 
    views.sortWith {
      ..
    }.take(MaxTopSpeakerVideoPreviews)
  else 
    views.filter {
      ...
    }.sortWith {
      ...
    }.take(MaxAllVideoPreviews)
```

2020-12-17 11:13 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +    videoGrid.foreach (_.removeAllViews())
Usually it's `.foreach(...)` without a whitespace and `.foreach { ... }` with a whitespace.

2020-12-17 11:13 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
> +    Signal.zip(controller.isCallEstablished, controller.isGroupCall){
This should be `Signal.zip(controller.isCallEstablished, controller.isGroupCall).foreach {`.
If you write it without `.foreach` it means you are using the `apply` method instead and it works a bit differently... although there shouldn't be any difference in this case (the `apply` method subscribes to the signal without specifying the execution context, but here we use `Threading.Ui` as the execution context everywhere so there's no risk to mix it up). 

I think I will remove this `apply` from `wire-signals` soon :)

2020-12-17 14:52 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
> +    Signal.zip(controller.isCallEstablished, controller.isGroupCall){
ok done

2020-12-17 16:35 UTC, mejdoo commented on app/src/main/res/values/strings.xml
> +    <string name="calling_no_active_speaker">No active speakers…</string>
Sorry, I didn't get what you mean here.

2020-12-17 17:02 UTC, makingthematrix approved these changes

2020-12-18 09:42 UTC, makingthematrix approved these changes

2020-12-18 14:15 UTC, gizemb approved these changes

2020-12-18 14:16 UTC, mejdoo commented on app/src/main/res/layout/fragment_calling_controls.xml
> +        android:textOn="SPEAKERS"
right, I forgot to do it. Thanks for the heads up!

2020-12-18 15:00 UTC, merged