[Calling] : Show only the top active speaker in participants list
wireapp/wire-android pull request #3126
Opened 2020-12-21 09:45 UTC by mejdoo

## What's new in this PR?

As a follow up of #3122, there was a request to show only 1 active speaker in participants list instead of many active speaker. This does not apply for the gridView.

https://wearezeta.atlassian.net/browse/SQCALL-43

2020-12-21 11:10 UTC, makingthematrix requested changes

2020-12-21 11:10 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
> +    isActive                 <- callController.isTopSpeaker(userId, clientId)
Please change the name `isActive` to `topSpeaker`.

2020-12-21 11:25 UTC, gizemb commented on zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
> +  def canOthersDialogue: Boolean = allParticipants.size > 1
doesn't the logic change here? (though I'm not sure what `canOthersDialogue` means)

2020-12-21 11:25 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
> +  private lazy val otherUser = Signal.zip(isGroupCall, userStorage, allParticipants.map(_.toSeq.headOption)).flatMap {
this doesn't break anything, right? the variable name is `otherUser`, so I got suspicious

2020-12-21 11:26 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
> +  private lazy val otherUser = Signal.zip(isGroupCall, userStorage, allParticipants.map(_.toSeq.headOption)).flatMap {
Right. I always thought that `otherParticipants` here don't contain the self user. If they do, there is a risk that `otherUser` will be the same as the self user. @mejdoo , could you check it?

2020-12-21 11:35 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
> +    isActive                 <- callController.isTopSpeaker(userId, clientId)
ok done

2020-12-21 11:38 UTC, mejdoo commented on zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
> +  def canOthersDialogue: Boolean = allParticipants.size > 1
No change for the logic here. I changed the name because it's reflecting a wrong thing. `other` means `allParticipants` except `selfParticipant`.

2020-12-21 11:41 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
> +  private lazy val otherUser = Signal.zip(isGroupCall, userStorage, allParticipants.map(_.toSeq.headOption)).flatMap {
Let me double check again and give you some results of AVS api

2020-12-21 12:58 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
> +  private lazy val otherUser = Signal.zip(isGroupCall, userStorage, allParticipants.map(_.toSeq.headOption)).flatMap {
I can confirm it contains the self user after checking the logs of AVS (tested with group calls of 3 participants)

2020-12-21 16:40 UTC, makingthematrix requested changes

2020-12-21 16:40 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
> +  private lazy val otherUser = Signal.zip(isGroupCall, userStorage, allParticipants.map(_.toSeq.headOption)).flatMap {
Okay, so that means we have a possible bug here. Just to be on the safe side, please filter the self user out:
```
private lazy val otherUser = Signal.zip(isGroupCall, userStorage, allParticipants, selfParticipant).flatMap {
  case (false, usersStorage, participants, self) => 
      participants.find(_.userId != self.userId) match {
        case Some(participant) => usersStorage.optSignal(participant.userId)
        case None              => Signal.const[Option[UserData]](None)
      }
  case _ => Signal.const[Option[UserData]](None)
}
```

2020-12-21 17:05 UTC, gizemb commented
@mejdoo does `otherUser` work properly with this change in **everywhere** it is used?
if yes, then we should simply change the name from `otherUser` to something else, like "user".

Because when talking about participants, "other" refers to any participant who is not the self user. This naming could create confusion for people who don't check how it's computed.

2020-12-21 17:21 UTC, makingthematrix commented
> @makingthematrix filtering the self user may make the calling features working improperly. The self user will not be displayed in participants list + `videoGrid` and `previewCardView` won't behave properly.

I mean only filtering the self user out for the `otherUser` signal. In other cases, the self user should stay.

2020-12-22 09:02 UTC, mejdoo commented
> any participant who

@gizemb yes, I changed this everywhere to `AllParticipants` instead of `otherParticipants`

2020-12-22 09:07 UTC, mejdoo commented
@makingthematrix @gizemb Sorry I misunderstood you in my previous comments. I got you meant, I will change the code as @makingthematrix requested.

2020-12-22 09:08 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
> +  private lazy val otherUser = Signal.zip(isGroupCall, userStorage, allParticipants.map(_.toSeq.headOption)).flatMap {
Good catch @makingthematrix 👍

2020-12-22 15:34 UTC, mejdoo commented
> @mejdoo does `otherUser` work properly with this change in **everywhere** it is used?
> if yes, then we should simply change the name from `otherUser` to something else, like "user".
> 
> Because when talking about participants, "other" refers to any participant who is not the self user. This naming could create confusion for people who don't check how it's computed.

@gizemb sorry for the misunderstood. For this specific signal, `otherUser` refers to any participant who is not the self user.

2020-12-22 15:59 UTC, makingthematrix approved these changes

2020-12-22 16:03 UTC, gizemb approved these changes
I approved but had a question

2020-12-22 16:03 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
> +  private val topSpeakerData = Signal(Option.empty[(UserId, ClientId)])
shouldn't this stay as `activeSpeakerData`? I agree with `isTopSpeaker` change because it performs a check for top speaker, but seems like this signal emits values regardless of whether they're top speaker or not

2020-12-22 16:17 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
> +  private val topSpeakerData = Signal(Option.empty[(UserId, ClientId)])
I'm fine with reverting variable names if @makingthematrix agrees as well.

2021-01-04 08:50 UTC, merged