refactor: Use new protobuf 1.28.1
wireapp/wire-android pull request #3193
Opened 2021-03-01 20:02 UTC by makingthematrix

I know this is huge.

The old protobuf implementation used the now obsolete "nano" mode which created very small Java classes which had to be accessed and modified directly, i.e. every field was public and it was up to us to ensure we use it in the right way. "nano" is no longer used in protobuf, so when I updated protobuf, I hade to change to the more standard "lite" implementation. "lite" uses getters and for modification it has builder classes. That changed a lot how
the protobuf classes need to be handled in our `com.waz.model._` classes, esp. `GenericMessage` and `GenericContent`. On top of that, we recently merged two protobuf libraries: generic-message-proto and backend-api-proto. I had to make so many changes that instead of trying to contain them and change as little as possible (not possible) I decided to refactor also the code which touched those classes, so that it all works better together.

Before, we used a lot of implicit objects with `apply` and `unapply` methods for convertions. In many places it meant that we converted the proto data into logic case classes, used them for checking something, then dismissed them, and then we made convertions again when we needed them again. I removed those implicit objects and introduced "newtypes" - wrapper case classes around proto data. Each of them has a `lazy val unpack`, equivalent to the previous `unapply`, but this time after the first convertion, the converted ("unpacked") version is remembered so we don't get the performance
penalty when we need to mae another convertion. Instead, I guess the app will now need a bit more memory. We need to test it.

Also, I made some performance optimizations in `GenericMessageService`. Until now with every new event we created and then left for garbage collection a lot of intermediate collections. I decided it happens so often that it might make sense to use one mutable cache instead. This too needs to be tested. Fortunately, both `unpack` and this can be easily converted to versions which will be slower but maybe safer, so if we find a bug in this implementation, we may try it.

2021-03-02 09:33 UTC, makingthematrix commented
build again

2021-03-19 11:24 UTC, gizemb requested changes
I couldn't review all of it but here are some of my findings so far

2021-03-19 11:24 UTC, gizemb commented on zmessaging/src/main/scala/com/waz/service/GenericMessageService.scala
> +          cleared += c.unpack
is `if userId == selfUserId` check missing here?

2021-03-19 11:24 UTC, gizemb commented on zmessaging/src/main/scala/com/waz/sync/client/MessagesClient.scala
> +    val msg = builder.build()
doesn't builder allow method chaining?

2021-03-19 11:24 UTC, gizemb commented on zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
> +                GAsset(uploadAssetOriginal, Some(previewAsset), expectsReadConfirmation = false)
what's `GAsset`?

2021-03-19 11:24 UTC, gizemb commented on zmessaging/src/test/scala/com/waz/sync/handler/UsersSyncHandlerSpec.scala
> +          }
we can write a utility method for that

2021-03-19 13:10 UTC, makingthematrix commented
build again

2021-03-19 13:44 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/tracking/GlobalTrackingController.scala
> +          .setLoggingEnabled(false)
Right. I think I changed it at some point because I thought `logsEnabled` is always false, but actually it's not.

2021-03-19 15:57 UTC, makingthematrix commented
build again

2021-03-19 16:24 UTC, gizemb approved these changes

2021-03-19 16:34 UTC, merged