[Calling] Feature : zooming on video and screenshare
wireapp/wire-android pull request #3202
Opened 2021-03-15 10:54 UTC by mejdoo

## What's new in this PR?

### Issues

This PR comes up with a new calling feature : zooming.

https://wearezeta.atlassian.net/browse/SQCALL-136

2021-03-15 11:23 UTC, gizemb requested changes

2021-03-15 11:23 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
> +  private lazy val fullScreenVideoZoomLayout = returning(view[ZoomLayout](R.id.full_screen_video_zoom_layout)) { vh =>
I think for readability purposes we should initialize `zoomLayout` and `containerLayout` separately.

2021-03-16 10:12 UTC, gizemb approved these changes

2021-03-16 10:29 UTC, mejdoo commented
build again

2021-03-16 10:58 UTC, merged