Feature: Legal Hold - Indicate legal hold in conversation list
wireapp/wire-android pull request #3211
Opened 2021-03-23 15:25 UTC by gizemb

## What's new in this PR?

### Issues

Jira: [SQSERVICES-337](https://wearezeta.atlassian.net/browse/SQSERVICES-337)

When the user is under legal hold, we want to show an indicator in the main page,  on top of conversation list.

### Solutions

<img src="https://user-images.githubusercontent.com/2143283/112171627-49b7de80-8bf4-11eb-945e-657e07218c05.png" width="350px" />

### Testing

Tested manually w/ mock data.

2021-03-23 17:21 UTC, makingthematrix requested changes

2021-03-23 17:21 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListTopToolbar.scala
> +  })
You can import `ContextUtils`:
```
import com.waz.zclient.utils.ContextUtils._
```
and then simplify the last lines here to:
```
} yield legalHoldActive).onUi(legalHoldIndicatorButton.setVisible)
```

By the way, maybe it would be useful to create a method in `LegalHoldController` to ask for the legal hold of the self user. (Do we ever ask for the elegal hold of another user?)

2021-03-24 09:05 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListTopToolbar.scala
> +  })
`setVisible` makes the view `GONE`, bu here I need it to be `INVISIBLE`. When it's invisible it keeps occupying space, which helps username stay centered on the screen.

For other users, I think we'll need to check legal hold for User Search page, but I'm not sure 🤔 I'd prefer not to introduce this logic into `LegalHoldController` for now, maybe if self user's state is frequently needed I can add it later.

2021-03-24 11:06 UTC, makingthematrix approved these changes

2021-03-24 11:07 UTC, merged