Feature: Legal Hold - Legal hold details screen for self user
wireapp/wire-android pull request #3212
Opened 2021-03-23 15:47 UTC by gizemb

## What's new in this PR?

### Issues

Jira: [SQSERVICES-345](SQSERVICES-345)

Given that I'm under legal hold, when I click on legal hold indicator on top of conversation list page ( #3211 ), then I should see a detail screen which explains what legal hold means.

### Solutions

| Light Theme | Dark Theme |
|-------------|--------------|
| <img src="https://user-images.githubusercontent.com/2143283/112174090-6bb26080-8bf6-11eb-8b4e-25b3d7c8e154.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/2143283/112174151-766cf580-8bf6-11eb-97c5-8f328b8406b8.png" width="300px"/> |

### Testing

Tested manually w/ mock data.

## Notes

A similar screen will be implemented for participants of a conversation, so some values are parameterized.

2021-03-23 15:48 UTC, gizemb commented on app/src/main/AndroidManifest.xml
> +            android:screenOrientation="portrait" />
only change here is this activity. the rest is just formatting

2021-03-29 09:48 UTC, makingthematrix requested changes

2021-03-29 09:48 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListTopToolbar.scala
> +        legalHoldIndicatorClick ! Unit
Cosmetic: You don't need `{ ... }` here, and an idiomatic way to send a unit value is with `()` instead of `Unit`.

2021-03-29 09:48 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
> +}
Cosmetic: The external `{ ... }` are not necessary.

2021-03-29 09:48 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/legalhold/SelfUserLegalHoldInfoActivity.scala
> +  }
And here too, `{...}` are not necessary.

2021-03-29 09:48 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
> +  private lazy val adapter = new LegalHoldUsersAdapter(users, MAX_PARTICIPANTS)
Do we ever use `LegalHoldUsersAdapter` for a different number of participants than `MAX_PARTICIPANTS`? If not, maybe we don't need it as an argument?

2021-03-29 12:34 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
> +  private lazy val adapter = new LegalHoldUsersAdapter(users, MAX_PARTICIPANTS)
yes, for now it has only 1 value but 3 PRs later, I'll convert it to optional.

2021-03-29 12:35 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListTopToolbar.scala
> +        legalHoldIndicatorClick ! Unit
compiler didn't like () so I changed it to (())
I also used onClick {} from RichView

2021-03-29 13:24 UTC, makingthematrix approved these changes

2021-03-29 13:56 UTC, merged