Feature: Legal Hold - Legal hold details screen for conversation
wireapp/wire-android pull request #3213
Opened 2021-03-26 16:28 UTC by gizemb

## What's new in this PR?

### Issues

Jira: [SQSERVICES-343](https://wearezeta.atlassian.net/browse/SQSERVICES-343), [SQSERVICES-345](https://wearezeta.atlassian.net/browse/SQSERVICES-345)

Given there's a conversation with at least one participant who is subject to legal hold, 
when I click on legal hold indicator on top of conversation details title ( #3206 ), 
then I should see a detail screen which explains what legal hold means, 
and see list of participants who are subject to legal hold.

### Solutions

The UI is same as #3212 

### Testing

Tested manually with mock data.

2021-03-29 10:49 UTC, makingthematrix requested changes

2021-03-29 10:49 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/legalhold/BaseLegalHoldInfoActivity.scala
> +abstract class BaseLegalHoldInfoActivity extends BaseActivity with LegalHoldInfoFragment.Container {
Why is this an activity? Everywhere starting from the conversation list view, then a single conversation, the participants view, etc., we use fragments. Why not use a fragment in this case as well?

2021-03-29 14:37 UTC, gizemb commented
build again

2021-04-07 15:39 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
> +  val TAG = "LegalHoldInfoFragment"
afaik from our Scala coding style, this constant name would be `Tag` not `TAG`, @makingthematrix  correct me if I'm wrong.

2021-04-07 15:48 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
> +  val TAG = "LegalHoldInfoFragment"
I've seen both usages actually, but I can change it if former is more common.

2021-04-07 15:50 UTC, mejdoo approved these changes

2021-04-07 16:01 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
> +  val TAG = "LegalHoldInfoFragment"
ok, the general convention seems to be camel case: https://docs.scala-lang.org/style/naming-conventions.html#constants-values-variable-and-methods

I updated it in the next commit in order to not to wait rebasing builds in Jenkins

2021-04-07 16:04 UTC, merged