Feature: Legal Hold - Legal hold details screen for conversation - Show user's device list
wireapp/wire-android pull request #3214
Opened 2021-03-26 16:42 UTC by gizemb

## What's new in this PR?

### Issues

Jira: [SQSERVICES-345](https://wearezeta.atlassian.net/browse/SQSERVICES-345)

Given that I am on legal hold details screen for a conversation, 
when I click one of the users on legal hold subjects list,
then I should see user's device list

### Solutions

For 1-1 conversation details, it is sufficient to switch to devices tab on previous screen.
For Group conversation details, we open user details screen with devices tab on by default.

2021-04-07 15:35 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
> +          import SingleParticipantFragment._
out of curiosity, why you imported this class here, not in top?

2021-04-07 15:47 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
> +          import SingleParticipantFragment._
no particular reason. it also works if I move it to the top but that way it is consistent with other `case` blocks. this usage also creates a "scope" I believe (i.e. if you need this import outside this `case` block, you need to import it again), which doesn't matter for us now.

2021-04-07 15:49 UTC, mejdoo approved these changes

2021-04-07 17:19 UTC, makingthematrix requested changes

2021-04-07 17:19 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
> +    def onLegalHoldSubjectClick(userId: UserId): Unit = {}
I know that we use "container" traits in some places in Scala code, so this is not an unknown pattern, but I wonder if it's not simpler here to just access the signal with legal hold users directly, and have an event stream for clicks as well. I wil ltry to write more about it tomorrow.

2021-04-08 16:15 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
> +    def onLegalHoldSubjectClick(userId: UserId): Unit = {}
@mejdoo we couldn't come up with a mutual decision here. can you help us decide? we can align via chat.

2021-04-09 08:02 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
> +    def onLegalHoldSubjectClick(userId: UserId): Unit = {}
I never used this "container" traits in wire-android but I think it ok to introduce to the Scala codebase new approaches for handling click events. This solution looks to me less decoupled and it's very similar to how click listeners works in Android.

2021-04-12 08:19 UTC, makingthematrix approved these changes

2021-04-12 08:19 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
> +    def onLegalHoldSubjectClick(userId: UserId): Unit = {}
Okay. Approved.

2021-04-14 11:45 UTC, mejdoo commented
@gizemb you can merge this PR :)

2021-04-21 14:43 UTC, gizemb commented
> @gizemb you can merge this PR :)

I will make a small change :)

2021-04-22 13:55 UTC, merged