Define legal hold request
wireapp/wire-android pull request #3217
Opened 2021-03-30 09:33 UTC by johnxnguyen

## What's new in this PR?

### Issues

JIRA: [SQSERVICES-348](https://wearezeta.atlassian.net/browse/SQSERVICES-348)

The legal hold request (that will be eventually receive from the backend) should be stored locally so it can be processed by the self user at an appropriate time. 

### Solutions

Define request model. Instances of the legal hold request are intended to be stored in the properties table, so we also add encoding and decoding functionality.

### Testing

Added tests for encoding to and decoding from JSON objects.

2021-03-30 10:09 UTC, gizemb requested changes

2021-03-30 10:09 UTC, gizemb commented on zmessaging/src/main/scala/com/waz/model/LegalHoldRequest.scala
> +object LegalHoldRequest {
I guess you can use already existing data types (`ClientId` and `PreKey`) and make something very similar to `ClientDecoder` in `OtrClient.scala`. I don't know if `PreKey` type makes it hard to store it in db, but seems like you can at least use `ClientId` and its encoder/decoder instead of creating a new `Client` type here. we also have `PreKeyDecoder`/`PreKeyEncoder`

2021-03-30 12:54 UTC, johnxnguyen commented on zmessaging/src/main/scala/com/waz/model/LegalHoldRequest.scala
> +object LegalHoldRequest {
Done

2021-03-31 08:21 UTC, gizemb approved these changes

2021-03-31 08:28 UTC, merged