Migrating robotest
wireapp/wire-android pull request #3222
Opened 2021-03-31 12:33 UTC by makingthematrix

Robotest is our very old wrapper on Robolectric, which by itself is our very old dependency. Due to some weird hack, the code in our tests depended on that we use Robolectric 2.4, but the robotest wrapper used Robolectric 3.0. Don't ask me how it worked before, but when I recompiled robotest to be able to publish it to Sonatype, it stopped working. To fix it, I had to remove a lot of code from wire-android - luckily, it was used only in a handful tests. 
I made a ticket to remove it all (https://wearezeta.atlassian.net/browse/SQCORE-579) and rewrite tests as proper unit tests, Robolectric-free, but for now this is enough.

2021-04-12 15:59 UTC, mejdoo requested changes

2021-04-12 15:59 UTC, mejdoo commented on zmessaging/src/test/scala/com/waz/service/EventSchedulerSpec.scala
> +/*    scenario("Order of execution")(withFixture { env => import env._
I think it would be better to fix this this test or delete it rather than commenting it.

2021-04-12 15:59 UTC, mejdoo commented on zmessaging/src/test/scala/com/waz/service/EventSchedulerSpec.scala
> +/*    scenario("Failing stages")(withFixture { env => import env._
same here and everywhere else.

2021-04-13 12:53 UTC, makingthematrix commented on zmessaging/src/test/scala/com/waz/service/EventSchedulerSpec.scala
> +/*    scenario("Failing stages")(withFixture { env => import env._
@mejdoo : ok, done. Only EventSchedulerSpec had commented out code

2021-04-14 07:44 UTC, gizemb commented on zmessaging/src/test/scala/com/waz/db/MigrationsSpec.scala
> +@Config(sdk=Array(21))
this means that all the tests will run based on Android 5. why exactly do we need this config? I'm a bit concerned because min Android version we support is 7.

> By default, Robolectric will run your code against the targetSdkVersion specified in your manifest. If you want to test your code under a different SDK, you can specify the SDK using the sdk, minSdk and maxSdk config properties

2021-04-14 07:48 UTC, gizemb commented on zmessaging/src/test/scala/com/waz/db/MigrationsSpec.scala
> +  lazy val testDaoDb = new DaoDB(RuntimeEnvironment.application, "test", 1, Seq.empty[BaseDao[_]], Seq.empty[Migration]) {
suggestion: 
we can create a `def application` in `RobolectricTests` and use this method in overriding classes. It is less verbose and will create less change next time the API changes

2021-04-14 07:49 UTC, gizemb commented on zmessaging/src/test/scala/com/waz/service/EventSchedulerSpec.scala
> -  feature("Executing schedules") {
are these test cases not effective?

2021-04-15 11:08 UTC, makingthematrix commented on zmessaging/src/test/scala/com/waz/db/MigrationsSpec.scala
> +@Config(sdk=Array(21))
@gizemb : With our current (outdated) wire-android setup, SDK 21 is the *highest* number available for Robolectric. I'm actually thinking that we should rewrite our Robolectric tests to AndroidFreeSpec and remove Robolectric altogether. So, this is just a temporary solution so that the tests compile and run.

2021-04-16 08:58 UTC, makingthematrix commented
This PR will be followed by https://wearezeta.atlassian.net/browse/SQCORE-579

2021-04-21 10:51 UTC, gizemb approved these changes
since we're planning to erase `Robolectric`, we can go with testing on sdk 21 for now and handle this problem later..

2021-04-21 11:00 UTC, mejdoo approved these changes

2021-04-21 11:01 UTC, merged