Bugfix : Hide call controls overlay after zooming
wireapp/wire-android pull request #3241
Opened 2021-04-12 16:24 UTC by mejdoo

## What's new in this PR?

### Issues

The call controls overlay is always appearing after zooming. I couldn't find a solution to fix this without including the zooming library directly in the project and doing some refactoring to add a missing callback `ZoomLayoutGestureListener.onSingleTap()`. 

https://wearezeta.atlassian.net/browse/SQCALL-203

2021-04-13 09:39 UTC, makingthematrix requested changes
Please either include this library as a dependency or rewrite the code in Scala and add a header that it is based on the original Java code. Let's not include new Java code into the codebase.

2021-04-14 08:28 UTC, mejdoo commented
> Please either include this library as a dependency or rewrite the code in Scala and add a header that it is based on the original Java code. Let's not include new Java code into the codebase.

@makingthematrix done, please review again.

2021-04-14 08:38 UTC, gizemb commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    val zooming = "com.wire.zoom:zoomlayout:${Versions.ZOOMING}"
it should be **com.wire**:zoomlayout: (at least that's what I intended to do :D)

2021-04-14 09:23 UTC, mejdoo commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    val zooming = "com.wire.zoom:zoomlayout:${Versions.ZOOMING}"
I'm not sure exactly why it's **com.wire.zoom**, maybe because @Gardosen published it with the script that he did not with the gradle task.

2021-04-14 10:36 UTC, makingthematrix commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    val zooming = "com.wire.zoom:zoomlayout:${Versions.ZOOMING}"
Yes, it needs to be comwire:zoomlayout for Sonatype. All our libraries there are under com.wire

2021-04-14 10:36 UTC, makingthematrix approved these changes

2021-04-14 10:41 UTC, merged