Feature: Legal hold acceptance - Part 3 - Show approval pop up
wireapp/wire-android pull request #3246
Opened 2021-04-14 10:57 UTC by gizemb

## What's new in this PR?

### Issues

[SQSERVICES-351](https://wearezeta.atlassian.net/browse/SQSERVICES-351)
Given there's a pending legal hold request for the self user,
When app comes to foreground,
Then a pop up should be displayed prompting the user to accept legal hold

[SQSERVICES-340](https://wearezeta.atlassian.net/browse/SQSERVICES-340)
Given LH pop up is displayed,
When I enter a wrong password,
Then I should see an error message saying "Wrong password"

[SQSERVICES-341](https://wearezeta.atlassian.net/browse/SQSERVICES-341)
Given LH pop up is displayed,
And I entered a password
And I click "Accept"
When some error is received,
Then I should see a new pop up with generic error message

### Solutions

Modifies `ShowLegalHoldApprovalAction` for given scenarios

### Testing

Tested manually

2021-04-19 11:39 UTC, makingthematrix requested changes

2021-04-19 11:39 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/security/actions/ShowLegalHoldApprovalAction.scala
> +    legalHoldController.approveRequest(password).map {
Just to be consistent: if you return an `Unit`, use `.foreach` instead of `.map`.

2021-04-19 11:39 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/security/actions/ShowLegalHoldApprovalAction.scala
> +      returning(LegalHoldRequestDialog.newInstance(isSso = false, "...", showError = showError)) { dialog =>
Instead of hardcoded "...", can it be an id to `R.string.(...)`?

2021-04-21 11:05 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/security/actions/ShowLegalHoldApprovalAction.scala
> +    legalHoldController.approveRequest(password).map {
done 👍

2021-04-21 11:06 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/security/actions/ShowLegalHoldApprovalAction.scala
> +      returning(LegalHoldRequestDialog.newInstance(isSso = false, "...", showError = showError)) { dialog =>
I'm going to pass a proper string here, this is not the final version. I put a TODO on line 27 for that.

2021-04-21 12:43 UTC, gizemb commented
build again

2021-04-21 13:08 UTC, makingthematrix approved these changes

2021-04-21 13:09 UTC, merged