version code improvements
wireapp/wire-android pull request #3248
Opened 2021-04-14 14:42 UTC by Gardosen

- changed the versionCode to a representive of the unix timestamp div 1000 (possible values until June 2036)
- added a variable called patchVersion to be used for the versionName, which represents the given BUILD_NUMBER, PATCH_VERSION or per default 99999 which was earlier used for the versionCode
- removed the static definitions from the defs getDate, buildSuffixForVersion and getUnixTimestamp

## What's new in this PR?

wire-android is currently bound to the BUILD_NUMBER of the Jenkinsbuilder is is build on, or reflects the usage of a static number on the local machine stated as 99999.
this causes the issue that a client can not be installed over another one on several test scenarios, as the versionCode would be lower or incorrect. 

in order to fix this, this PR is changing the way the versionCode is defined.
instead of using the BUILD_NUMBER from Jenkins, the unix timestamp is used for the calculation.
the logic will work for the next 15 years until the 18th of June 2036.

in addition to not cryptorize the name of the apk file, a seprate "patchVersion" variable has been introduced for using it for the versionName which is also represented in the filename of the generated APK file.

2021-04-15 09:10 UTC, mejdoo requested changes

2021-04-15 09:10 UTC, mejdoo commented on app/build.gradle
> +        versionCode getUnixTimestamp() as Integer
Even if 2036 it's too far (2100000000 is the max version code allowed) , I don't like the idea of using timestamp for production builds.  Can we use this solution only for non-production builds to facilitate testing and for the production builds just increment the version code **+1**  when we publish to Google Play?

2021-04-15 12:29 UTC, Gardosen commented on app/build.gradle
> +        versionCode getUnixTimestamp() as Integer
if you transform the timestamp 2100000000 to a date, you get the 8th of June 2036. 
So googles playstore will accept every build from us with this method until this date without any issues.

as i also stated, for the next algorithm the logic is finetuned and the version code would be compatible until 8th of June 2536. 

to manually adjust the VersionCode or link it to a build_number of a ci/cd system is never a good idea as it always is risked to cause human error and problems if the build_system changes, get's reset.
in order to ensure a valid "growing" versionCode per build, it needs a fixed point in time. which makes a timestamp a great candidate for it.

2021-04-15 12:35 UTC, mejdoo commented on app/build.gradle
> +        versionCode getUnixTimestamp() as Integer
@makingthematrix @vitorhugods @ohassine @gizemb  what do you think about this topic?

2021-04-15 12:41 UTC, makingthematrix commented on app/build.gradle
> +        versionCode getUnixTimestamp() as Integer
Unfortunately, this would mean a lot of trouble for us when we track bugs and need to communicate about them. Right now we use those last numbers all the time to make sure we test the right build. Depending on the type of the build they're either three or four ciphers long and when we have two that differ but 1, we know for sure there was never a build between them. Numbers made of many more ciphers are just not friendly. I'd much prefer to keep the current format.

2021-04-20 13:53 UTC, AndroidBob commented
the code has been adjusted to allow builds for the next 614 years

2021-04-21 08:26 UTC, vitorhugods approved these changes

2021-05-04 10:03 UTC, makingthematrix approved these changes

2021-05-05 11:50 UTC, ohassine approved these changes

2021-05-05 13:20 UTC, merged