[Calling] Enable zooming for videos on 1:1
wireapp/wire-android pull request #3253
Opened 2021-04-16 14:32 UTC by mejdoo

## What's new in this PR?

In #3251 we introduced zooming for 1:1 calls for screen sharing, the calling squad decided to allow zooming for videos in 1:1 calls as well.

2021-04-16 15:51 UTC, makingthematrix requested changes

2021-04-16 15:51 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +      case 2 =>
Please turn it into a constant in 
```
object CallingFragment { 
  val ConstantName: Int = ...
}
```

2021-04-16 22:46 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
> +      case 2 =>
done 👍

2021-04-19 13:32 UTC, makingthematrix approved these changes

2021-04-19 13:41 UTC, merged