[Fix] Explicitly pass in deserializer
wireapp/wire-android pull request #3255
Opened 2021-04-19 09:15 UTC by johnxnguyen

## What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues. (Optional)_

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Testing

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

## Notes

_Specify here any other facts that you think are important for this issue. (Optional)_

2021-04-19 12:48 UTC, makingthematrix requested changes
I have some code change requests about the legal hold that go beyond that one PR you opened. One of the things is that I'd suggest to create case class that models exactly the json and then from that case class you can create LegalHoldRequest and this way avoid all the ugly explicit deserializer calls - if we later add another method to LegalHoldClient, it's possible this explicit call will bite us again.
But there are more: You should use UserProperties instead of PropertiesStorage and LegalHoldRequestKey should be defined in UserProperties. And the flow for SyncLegalHoldRequest is wrong - the handler shouldn't return a future but call a method in the service.

2021-04-20 13:09 UTC, johnxnguyen commented
> One of the things is that I'd suggest to create case class that models exactly the json

@makingthematrix  I had a go at this but it got quite time consuming so I put it to the side for now. I would revisit this at a later point because I have some other more important things to focus on at the moment.

> You should use UserProperties instead of PropertiesStorage

Done in https://github.com/wireapp/wire-android/pull/3258

> And the flow for SyncLegalHoldRequest is wrong

Fixed in https://github.com/wireapp/wire-android/pull/3257

2021-04-22 13:53 UTC, gizemb approved these changes

2021-04-23 08:56 UTC, makingthematrix approved these changes

2021-04-23 08:57 UTC, merged