[Feature] Legal hold status calculation
wireapp/wire-android pull request #3260
Opened 2021-04-21 09:11 UTC by johnxnguyen

## What's new in this PR?

This PR introduces legal hold status calculation for conversations. It reacts to changes in user clients and conversation membership by checking if any of the participants at that point are legal hold subjects or not, and updates the legal hold status accordingly.

In future PRs we will build on this to make use of the legal hold status such as appending system messages.

### Testing

Added tests to assert that it calculates the status and transitions to various states.

2021-04-21 12:12 UTC, johnxnguyen commented
@gizemb the build is failing due to detekt. Do you know where I can see the issues reported by detekt?

2021-04-23 08:47 UTC, johnxnguyen commented
There are some more changes coming don't review it just yet.

2021-04-27 12:40 UTC, johnxnguyen commented
This is ready for review now.

2021-04-28 09:12 UTC, gizemb approved these changes

2021-04-28 09:12 UTC, gizemb commented on zmessaging/src/main/scala/com/waz/service/LegalHoldStatusUpdater.scala
> +    } yield ()
maybe you can achieve this in a single line:
`Future.traverse(convIds.distinct)(updateLegalHoldStatus).map(_ => ())`

2021-04-28 09:25 UTC, johnxnguyen commented
@makingthematrix , do I need to change anything regarding the backup version?

2021-04-30 10:23 UTC, makingthematrix requested changes

2021-04-30 10:23 UTC, makingthematrix commented on app/src/main/kotlin/com/waz/zclient/feature/backup/conversations/ConversationsBackupDataSource.kt
> +        legalHoldStatus = model.legalHoldStatus
Please also add a similar line to `fromEntity`, and in the test class `ConversationBackupMapperTest`.

2021-04-30 10:23 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/LegalHoldStatusUpdater.scala
> +  }
Just a cosmetic thing, but this can be `clientsStorage.onChanged.foreach(onClientsChanged)`.
And similarly in all the other event streams in this class.
I'm working on an update to `wire-signals` where `.foreach` will be mandatory in these cases. I know here it looks good, but in more complicated cases the syntax without `.foreach` starts to look as if the event stream was actually a method call, and it can be confusing.

2021-04-30 10:23 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/LegalHoldStatusUpdater.scala
> +
So, here: `membersStorage.onAdded.foreach(members => updateLegalHoldStatus(members.map(_.convId)))`.

2021-04-30 10:23 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/LegalHoldStatusUpdater.scala
> +  }
And here too.

2021-04-30 10:23 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/LegalHoldStatusUpdater.scala
> +  def update(conv: ConversationData, detectedLegalHoldDevice: Boolean): ConversationData = {
The name is a bit misleading - we're not updating ConversationData, we're creating a new one. And I think you could move this method to ConversationData, something like:
```
def withNewLegalHold(detectedLegalHoldDevice: Boolean): ConversationData = { ... } 
```

2021-04-30 10:23 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/sync/otr/OtrClientsSyncHandler.scala
> +  def syncAllClients(userIds: Seq[UserId]): Future[Option[ErrorResponse]]
Ha, I can help you with that! :)

Please look into https://github.com/wireapp/wire-android/pull/3278/files into OtrClientsSyncHandler. I already implemented there `def syncClients(users: Set[QualifiedId]): Future[SyncResult]`. So, good that this one is a placeholder. If you review my code, we can merge them.

2021-04-30 10:25 UTC, johnxnguyen commented on zmessaging/src/main/scala/com/waz/service/LegalHoldStatusUpdater.scala
> +
Fixed in 7069ce792bd4d09e469f9e88133a091c3424da34

2021-04-30 16:20 UTC, makingthematrix approved these changes
Okay, one more thing :)
I merged my PR. Please rebase and use syncClients from that PR instead of syncAllClients from here.

2021-05-03 08:43 UTC, merged