Feature: Legal Hold Approval - Display pending icon
wireapp/wire-android pull request #3269
Opened 2021-04-23 15:30 UTC by gizemb

## What's new in this PR?

### Issues

Jira issues:
[SQSERVICES-342](https://wearezeta.atlassian.net/browse/SQSERVICES-342)
[SQSERVICES-352](https://wearezeta.atlassian.net/browse/SQSERVICES-352)

Display a "pending" icon on top of conversation list when there's a legal hold request waiting for approval from user.
Tapping this icon should open approval popup

### Solutions

Modified legal hold indicator check in `NormalTopToolbar`
Added a `hasPendingRequest` method to `LegalHoldController` for convenience.

### Testing

Manually tested.

2021-04-26 09:37 UTC, makingthematrix requested changes

2021-04-26 09:37 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/conversationlist/ConversationListFragment.scala
> +      }
this can be done with cases:
```
toolbar.legalHoldIndicatorClick.onUi {
  case true  => showLegalHoldApprovalAction()
  case false => showLegalHoldInfo()
}
```

2021-04-26 09:37 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/conversationlist/ConversationListFragment.scala
> +  }
curly braces are unnecessary here

2021-04-26 09:37 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListTopToolbar.scala
> +      implicit val executionContext: ExecutionContext = Threading.Ui
Instead of creating a a new val here, just `import Threading.Implicits.Ui`

2021-04-26 09:37 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
> +  def hasPendingRequest: Signal[Boolean] = legalHoldRequest.map(_.isDefined)
`hasPendingRequest` and `legalHoldRequest` can be `val` instead of `def` - they don't have any arguments so you don't need to create a new signal every time you access them.

2021-04-27 11:42 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/conversationlist/ConversationListFragment.scala
> +      }
done

2021-04-27 11:42 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/conversationlist/ConversationListFragment.scala
> +  }
done

2021-04-27 11:42 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListTopToolbar.scala
> +      implicit val executionContext: ExecutionContext = Threading.Ui
done, thanks for the tip!

2021-04-27 11:42 UTC, gizemb commented on app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
> +  def hasPendingRequest: Signal[Boolean] = legalHoldRequest.map(_.isDefined)
done

2021-04-27 12:38 UTC, makingthematrix approved these changes

2021-04-27 12:45 UTC, merged