[Feature] Legal hold controller implementation
wireapp/wire-android pull request #3270
Opened 2021-04-26 10:26 UTC by johnxnguyen

## What's new in this PR?

This PR fills in the `LegalHoldController` stubs to provide functionally to

- determine if legal hold is active for a particular user
- determine if legal hold is active in a particular conversation
- get a sequence  of all legal hold subjects in a particular conversation

2021-04-26 10:36 UTC, makingthematrix requested changes
I'd propose that instead of injecting `Signal[*Storage]` here directly, and then working on those signals in a complicated way, you put that logic in `OtrClientsService`, `ConversationService`, and `UserService` respectively. There, you will be able to work on just `*Storage` instead of `Signal[*Storage]`, and here, in the controller, you will just access `Signal[*Service]` and `flatMap` it to a respective method.

In general, if a lot of work in a controller is done on signals of storages, it's a good hint that it should be moved to the service layer.

2021-04-26 11:22 UTC, gizemb commented
> I'd propose that instead of injecting `Signal[*Storage]` here directly, and then working on those signals in a complicated way, you put that logic in `OtrClientsService`, `ConversationService`, and `UserService` respectively. There, you will be able to work on just `*Storage` instead of `Signal[*Storage]`, and here, in the controller, you will just access `Signal[*Service]` and `flatMap` it to a respective method.
> 
> In general, if a lot of work in a controller is done on signals of storages, it's a good hint that it should be moved to the service layer.

I agree that we should move all this logic to the Service layer. We can directly handle this in `LegalHoldService`, in order to keep all the LH logic in a single place.

2021-04-26 13:28 UTC, johnxnguyen commented
@makingthematrix and @gizemb I moved the logic out of the controller as requested, and additionally added tests.

2021-04-27 07:01 UTC, gizemb commented on zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
> +    scenario("that contains legal hold subjects") {
what about "that does not contain any legal hold subjects" case?

2021-04-27 08:09 UTC, johnxnguyen commented on zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
> +  def expectation(userId: UserId, deviceTypes: Seq[OtrClientType]): Unit = {
Fixed in a3a8a5bf1331237019ac4a445bbde8cef748bea9

2021-04-27 08:09 UTC, johnxnguyen commented on zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
> +  def expectation(convId: ConvId, legalHoldStatus: LegalHoldStatus): Unit =
Fixed in a3a8a5bf1331237019ac4a445bbde8cef748bea9

2021-04-27 08:13 UTC, johnxnguyen commented on zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
> +    scenario("that contains legal hold subjects") {
Added in 671b99308ee6c8011aa20b146bc468725507f4d6

2021-04-27 08:55 UTC, gizemb approved these changes

2021-04-27 12:31 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
> +    legalHoldSubjects = usersAndStatus.filter(_._2).map(_._1)
Maybe something like this?
```
usersAndStatus    <- Signal.sequence(users.map(userId => isLegalHoldActive(userId).map(active => userId -> active)))
legalHoldSubjects =  usersAndStatus.collect { case (userId, true) => userId }
```

2021-04-27 12:33 UTC, makingthematrix approved these changes

2021-05-03 09:45 UTC, merged