[Feature] Update legal hold status from generic message hint
wireapp/wire-android pull request #3288
Opened 2021-05-04 07:46 UTC by johnxnguyen

## What's new in this PR?

There are several ways to discover legal hold clients in a conversation, such as when backend reports missing clients when trying to send a message, or through an explicit sync of users clients. However, it could be that the user is acts as an observer in the conversation and rarely posts a message, if at all. 

To help the self client discover other legal hold clIents in the conversation, all messages received will contain a flag to indicate whether the sender believes their message was sent to a legal hold client. The self client uses this as a hint, first updating their local legal hold status for the conversation and subsequently triggering a sync of all clients in the conversation for verification of the hint.

### Testing

Added unit tests that:

- the conversation is updated and the sync is triggered, if needed
- generic message events are processed for the hints.

2021-05-04 09:21 UTC, gizemb commented on zmessaging/src/main/scala/com/waz/service/LegalHoldStatusUpdater.scala
> +  }
this looks a little hard to read. can we improve it by indenting second `match` further, or maybe using `fold`?

2021-05-04 09:21 UTC, gizemb commented on zmessaging/src/test/scala/com/waz/service/LegalHoldStatusUpdaterSpec.scala
> +      val messageStatus = Messages.LegalHoldStatus.ENABLED
would be nice to check the other case as well when status is Enabled, and message has Disabled

2021-05-10 13:59 UTC, makingthematrix requested changes

2021-05-10 13:59 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/LegalHoldStatusUpdater.scala
> +  }
`for/yield` notation could also make it looks simpler.

2021-05-12 06:18 UTC, johnxnguyen commented on zmessaging/src/test/scala/com/waz/service/LegalHoldStatusUpdaterSpec.scala
> +      val messageStatus = Messages.LegalHoldStatus.ENABLED
I added this in the refactoring.

2021-05-12 06:19 UTC, johnxnguyen commented on zmessaging/src/main/scala/com/waz/service/LegalHoldStatusUpdater.scala
> +  }
I went with the `for yield`.

2021-05-12 06:22 UTC, johnxnguyen commented
@gizemb @makingthematrix I needed to do some major refactoring of the initial implementation, namely to post a client discovery message before doing the sync and to trigger the verification sync through the `SyncServiceHandle`.

2021-05-12 07:49 UTC, makingthematrix requested changes
Let's talk about it later, ok?
I believe this could be done using what we already have. But I need to know more.

2021-05-20 10:58 UTC, makingthematrix approved these changes

2021-05-20 10:59 UTC, merged