[Calling] Feature : Large video conference calls - Display profile picture for participants with audio only
wireapp/wire-android pull request #3310
Opened 2021-05-18 15:39 UTC by mejdoo

## What's new in this PR?

Particiants tiles are always shown, also if none has video enabled. If a participant has their camera off, the users profile picture is shown instead.

2021-05-19 08:43 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
> +class NewCallingFragment extends FragmentHelper {
This fragment is replacing `CallingFragment` when `BuildConfig.LARGE_VIDEO_CONFERENCE_CALLS` is set to `true`. Once the feature is released `CallingFragment` will be deleted.

2021-05-26 14:58 UTC, makingthematrix requested changes

2021-05-26 14:58 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingActivity.scala
> +    else fragment = CallingFragment()
It looks like `fragment` can be a lazy val:
```
private lazy val fragment = 
  if (BuildConfig.LARGE_VIDEO_CONFERENCE_CALLS) NewCallingFragment() 
  else CallingFragment()
```
and initilized in `onCreate` simply by calling it:
```
  override def onCreate(savedInstanceState: Bundle): Unit = {
    ...
    fragment
  }
```

2021-05-26 14:58 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
> +        => refreshVideoGrid(grid, selfParticipant, activeParticipants, participantsInfo, participants, true)
Indentation: please put`=>` at the end of the line with `case`

2021-05-26 14:58 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
> +    videoPreview = new VideoPreview(getContext)
It looks like `videoPreview` could also be a lazy val:
```
private lazy val videoPreview = initVideoPreview()
```
and then you don't need to call initVideoPreview directly

2021-05-26 14:58 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
> +        stopVideoPreview()
I think `stopVideoPreview()` is not needed here?

2021-05-26 14:58 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
> +      else Signal.const(false)
Indentation: Please align `else` with `if` from the line above

2021-05-26 14:58 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
> +    callController.controlsVisible.map { it => !it }.onUi(participantInfoCardView.setVisible)
In Scala, you can write it as `.map(!_)` :)

2021-05-26 15:22 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/CallingActivity.scala
> +    else fragment = CallingFragment()
is the  initialisation still needed as I'm calling later ?

```
  getSupportFragmentManager
      .beginTransaction()
      .replace(R.id.calling_layout, fragment, fragment.getTag)
      .commit
```

2021-05-26 15:23 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
> +        => refreshVideoGrid(grid, selfParticipant, activeParticipants, participantsInfo, participants, true)
Done

2021-05-26 15:26 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
> +        stopVideoPreview()
it's needed, we should force `callController.setVideoPreview(null)` before  `startVideoPreview()` otherwise this would generate a bug and the video will freeze on the remote side.

2021-05-27 09:59 UTC, makingthematrix approved these changes

2021-05-27 10:01 UTC, merged