Fix by @kongpf8848: UTF-16 encoding for chinese characters
wireapp/wire-android pull request #3356
Opened 2021-06-03 11:07 UTC by gizemb

## What's new in this PR?

### Issues

A duplicate of PR #3052 since original PR is no longer maintained by its author.

### Solutions

Same as original PR

### Testing

Unit tests are added for received mentions, with new cases for Chinese text. Also manually tested. You may see the bug in the first line of the image. Other lines are tests after applying the fix:

<img src="https://user-images.githubusercontent.com/2143283/120635137-69794780-c46c-11eb-8e83-554ad606031c.png" width="400px" />

2021-06-03 12:12 UTC, makingthematrix requested changes

2021-06-03 12:12 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/model/MessageData.scala
> +    if (text == null) {
The text should never be null so this part should not be necessary. Or should it be `if (text.isEmpty)`?

2021-06-03 12:45 UTC, gizemb commented on zmessaging/src/main/scala/com/waz/model/MessageData.scala
> +    if (text == null) {
I couldn't find a scenario where this could receive null or empty text in practice. also looks like `slice` function does check the length and is a safe operation, so I decided to erase this check.

2021-06-04 12:59 UTC, makingthematrix approved these changes

2021-06-04 13:04 UTC, merged