[Calling] Feature : Large video conference calls - Pagination - part 1
wireapp/wire-android pull request #3373
Opened 2021-06-15 21:15 UTC by mejdoo

## What's new in this PR?

This PR introduces the pagination for large video conference calls, now it's possible to swipe from page to page when the number of participants is more than 8 in mobile devices.

### TODO in the next PR

- Add pagination indicator

2021-06-17 09:26 UTC, makingthematrix requested changes

2021-06-17 09:26 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingGridAdapter.scala
> +  private lazy val callController = inject[CallController]
`callController` does not need to be lazy since you start using it right away

2021-06-17 09:26 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingGridAdapter.scala
> +  var numberOfParticipants : Int = callController.allParticipants.map(_.size).currentValue.getOrElse(0)
Please change to `private var numberOfParticipants: Int = 0`. It will be updated in a moment by a signal. Or, if this small delay can result in something going wrong, please add the initial number of participants as an argument in the `CallingGridAdapter` constructor.

2021-06-17 09:26 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingGridAdapter.scala
> +  }
`callController.allParticipants.map(_.size).foreach { numberOfParticipants = _ }`

2021-06-17 09:26 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
> +    }
Just a cosmetic change to avoid using `null`: 
```
Option(getArguments).foreach { bundle =>
  pageNumber = bundle.getInt(PAGINATION_BUNDLE_KEY)
}
```

2021-06-17 09:26 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
> +  }
Unnecessary outside parentheses `{ ... }`

2021-06-17 09:26 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
> +  }
Unnecessary outside parentheses `{ ... }`

2021-06-17 09:26 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
> +      userView.onDoubleClick.onUi { _ =>
It would be cleaner to keep the subscriptions created by `.onUi` here, and destroy them when the `userView` is removed. But I guess we can live without it if it's difficult to do.

2021-06-17 09:26 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
> +
Please remove one empty line

2021-06-17 09:26 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
> +
Please remove one empty line

2021-06-17 20:30 UTC, makingthematrix requested changes

2021-06-17 20:30 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
> +  }
1. It looks like you don't need `callController.allParticipants.map(_.size)` as you don't use it anywhere later. Maybe it's sufficient to just use 
```
callController.showTopSpeakers.onUi {
  case false => ...
  case true  => ...
}
```
?

2. Besides, do you need to create a new adapter every time? What if there two adapters only, one of each type, and you could keep them in `lazy val` and switch between them when `callController.showTopSpeakers` switches from `false` to `true` and back?

2021-06-18 08:57 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
> +  }
1- I need to call `notifyDataSetChanged()` when the number of participants is changing.
2- DONE

2021-06-21 16:01 UTC, makingthematrix approved these changes

2021-06-22 10:06 UTC, merged