[Calling]: Large conference calls - UI improvements - part 3
wireapp/wire-android pull request #3399
Opened 2021-07-05 15:42 UTC by mejdoo

## What's new in this PR?

This PR includes an UI improvement for large conference calls: 
- fix : overlay has no dark transparent background https://wearezeta.atlassian.net/browse/SQCALL-344

2021-07-06 09:54 UTC, ohassine approved these changes

2021-07-06 14:09 UTC, makingthematrix requested changes

2021-07-06 14:09 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
> +      else getView.setBackgroundColor(Color.TRANSPARENT)
Please fix indentation :)

2021-07-08 15:24 UTC, makingthematrix approved these changes

2021-07-09 08:38 UTC, merged