[Calling]: Large conference calls - Bugfix : Extra self tile in 1:1 calls
wireapp/wire-android pull request #3410
Opened 2021-07-13 20:46 UTC by mejdoo

## What's new in this PR?

This PR fixes an UI caused by large video conference calls implementation :  I mute myself, on 1-1 call, an extra tile appears.

https://wearezeta.atlassian.net/browse/SQCALL-346

2021-07-14 07:58 UTC, makingthematrix requested changes

2021-07-14 07:58 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
> +            .filter(_.clientId != selfParticipant.clientId)
Try this:
```
val participantsToShow = (participants.slice(startIndex, endIndex), size) match {
  case (ps, 2) => ps.filter(_.userId != selfParticipant.userId)
  case (ps, _) => ps
}.toSeq
```
The second filter shouldn't be necessary - only `selfParticipant` can have a client device with an id belonging to `selfParticipant`.

2021-07-14 15:26 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
> +            .filter(_.clientId != selfParticipant.clientId)
![not found](https://user-images.githubusercontent.com/43655743/125648566-b67e8a5d-a15e-40f7-b107-7a867938354c.png)
`toSeq` is not found

2021-07-15 07:26 UTC, mejdoo commented on app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
> +            .filter(_.clientId != selfParticipant.clientId)
it's not compiling

2021-07-15 09:41 UTC, makingthematrix approved these changes

2021-07-15 10:44 UTC, merged