fix: Read receipts not generated when responding from notification (WPB-8756)
wireapp/wire-android pull request #3420
Opened 2024-09-05 14:51 UTC by ohassine

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When we reply from head up notification, we don't mark older messages as read

### Solutions

Call `updateConversationReadDateUseCase` when replying from notifications

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-09-06 08:02 UTC, MohamadJaara requested changes

2024-09-06 08:02 UTC, MohamadJaara commented on app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/NotificationReplyReceiver.kt
> +                        conversations.updateConversationReadDateUseCase(
`updateConversationReadDateUseCase` will only send last read event to self clients and not send any read receipt

2024-09-06 08:12 UTC, MohamadJaara commented on app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/NotificationReplyReceiver.kt
> +                        conversations.updateConversationReadDateUseCase(
my bad it does send it, it was just not clear

2024-09-06 08:12 UTC, MohamadJaara approved these changes

2024-09-06 08:19 UTC, MohamadJaara requested changes
the goeal is to "mark only the last x number of messages that are displayed currently in the notification as read but leave the conversation as not read?" and `updateConversationReadDateUseCase` will also mark the conversation as read for self user

2024-09-09 13:15 UTC, ohassine commented
> the goeal is to "mark only the last x number of messages that are displayed currently in the notification as read but leave the conversation as not read?" and `updateConversationReadDateUseCase` will also mark the conversation as read for self user

But why ? if it's marked as read for others users why we keep it unread for self users ? it will be somehow confusing

2024-09-11 11:50 UTC, borichellow approved these changes

2024-09-11 13:37 UTC, yamilmedina approved these changes

2024-09-13 16:26 UTC, MohamadJaara approved these changes

2024-09-16 17:07 UTC, merged