File sharing restrictions (part 7)
wireapp/wire-android pull request #3428
Opened 2021-08-12 16:09 UTC by johnxnguyen

## What's new in this PR?

**Jira:** https://wearezeta.atlassian.net/browse/SQSERVICES-612

In this PR we restrict image content in both the reply view (in the input cursor) and reply message view (in the conversation content). For the former, this means to hide the little image preview, and for the latter, to replace the preview with a restriction label (see screenshot).

Additionally, I fixed the some layout from the previous PR (I forgot to set the typeface of a text view). 

### Testing

Manually tested.

## Notes

![Wire 2021-08-12 at 6 03 PM](https://user-images.githubusercontent.com/28632506/129230625-7517c176-89c5-4d37-8e56-d593f26d2496.png)

#### APK
[Download build #3771](http://10.10.124.11:8080/job/Pull%20Request%20Builder/3771/artifact/build/artifact/wire-dev-PR3428-3771.apk)
[Download build #3783](http://10.10.124.11:8080/job/Pull%20Request%20Builder/3783/artifact/build/artifact/wire-dev-PR3428-3783.apk)

2021-08-16 12:27 UTC, makingthematrix requested changes

2021-08-16 12:27 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/conversation/ReplyView.scala
> +    isFileSharingRestricted.head.foreach { isRestricted =>
If you want to use the preference only once, then instead of having a signal as a val, just write here something like :
```
(for {
      prefs <- inject[Signal[UserPreferences]].head
      isFileSharingEnabled <- prefs(UserPreferences.UserPreferences.FileSharingFeatureEnabled).apply()
} yield isFileSharingEnabled).foreach { isFileSharingEnabled => 
 ...
}
```

2021-08-16 14:17 UTC, johnxnguyen commented on app/src/main/scala/com/waz/zclient/conversation/ReplyView.scala
> +    isFileSharingRestricted.head.foreach { isRestricted =>
I will use it also in the another place (coming in a future PR), but it's true it doesn't need to be a signal so I'll change that.

2021-08-16 15:13 UTC, johnxnguyen commented on app/src/main/scala/com/waz/zclient/conversation/ReplyView.scala
> +    isFileSharingRestricted.head.foreach { isRestricted =>
Done

2021-08-17 10:54 UTC, makingthematrix approved these changes

2021-08-17 11:56 UTC, merged