File sharing restrictions (part 10)
wireapp/wire-android pull request #3435
Opened 2021-08-16 14:47 UTC by johnxnguyen

## What's new in this PR?

**Jira:** https://wearezeta.atlassian.net/browse/SQSERVICES-612

In this PR we add restriction views for file messages (see screen shot).

### Testing

Manually tested

## Notes

![Wire 2021-08-16 at 4 46 PM](https://user-images.githubusercontent.com/28632506/129582787-4b5c2ff2-7e4c-413b-9c95-cf5e1c7c2c26.png)

2021-08-16 16:31 UTC, makingthematrix requested changes

2021-08-16 16:31 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/conversation/ReplyView.scala
> +          set(assetName, bold = true, Some(if (isRestricted) StyleKitMethods().drawFileBlocked else WireStyleKit.drawFile), None)
Since `isRestricted` is used only here, not for any other type of an asset, can we check if `isFileSharingRestricted` only here? 
Also, I think instead of having `isFileSharingRestricted`  as a signal, and then calling `.head`, you can check the property directly.

2021-08-17 13:52 UTC, johnxnguyen commented on app/src/main/scala/com/waz/zclient/conversation/ReplyView.scala
> +          set(assetName, bold = true, Some(if (isRestricted) StyleKitMethods().drawFileBlocked else WireStyleKit.drawFile), None)
I've updated this: there is no long the signal, and I moved minimized the scope of `isRestricted`.

2021-08-17 14:05 UTC, makingthematrix approved these changes

2021-08-17 15:11 UTC, merged