Feature: Enforce ephemeral messages (part 5)
wireapp/wire-android pull request #3478
Opened 2021-08-31 19:53 UTC by vitorhugods

Continuation of #3445

## What's new in this PR?

Put in place the team settings enforcing. When the feature is disabled, the messages will not be self deleting. When the feature is enabled and there's and enforced timeout, this timeout will be considered above all else.

## Testing

Covered the altered logic inside the method `MessagesContentUpdater$addLocalMessage` with tests in `MessagesContentUpdaterSpec`.

#### APK
[Download build #3896](http://10.10.124.11:8080/job/Pull%20Request%20Builder/3896/artifact/build/artifact/wire-dev-PR3478-3896.apk)
[Download build #3901](http://10.10.124.11:8080/job/Pull%20Request%20Builder/3901/artifact/build/artifact/wire-dev-PR3478-3901.apk)
[Download build #3905](http://10.10.124.11:8080/job/Pull%20Request%20Builder/3905/artifact/build/artifact/wire-dev-PR3478-3905.apk)

2021-09-01 14:28 UTC, johnxnguyen requested changes
It would be good to add a test to assert the precedence of the different expirations, at least that the team setting has highest priority.

2021-09-01 17:32 UTC, vitorhugods commented
@johnxnguyen I've added the 

> It would be good to add a test to assert the precedence of the different expirations, at least that the team setting has highest priority.

I've covered the changes with tests in `MessagesContentUpdaterSpec.scala`.

2021-09-01 19:25 UTC, vitorhugods commented
build again

2021-09-02 06:17 UTC, johnxnguyen approved these changes

2021-09-02 10:04 UTC, merged