feat: Add debug button send FCM token #WPB-9476
wireapp/wire-android pull request #3482
Opened 2024-10-04 07:20 UTC by damian-kaczmarek

# What's new in this PR?

### Issues

Add button in debug settings that sends FCM push token to the API. If it fails error is displayed.

Needs releases with:

- [ ] https://github.com/wireapp/kalium/pull/3050

### Testing

#### How to Test

In debug settings there should be new button at the bottom of the screen. It sends the FCM push token to the API

### Attachments (Optional)

| Before | After |
|----------|----------|
| ![image](https://github.com/user-attachments/assets/a61f2106-317a-4f77-b48a-12f8d479afb8)  | ![image](https://github.com/user-attachments/assets/27db0c2c-fe6d-4402-86a4-727b7044a073)   |
----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-10-04 14:57 UTC, MohamadJaara requested changes

2024-10-04 14:57 UTC, MohamadJaara commented on app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
> +        )
request: can we for now please keep the button for internal usage only for internal builds you can check this by calling `BuildConfig.PRIVATE_BUILD`

2024-10-07 08:22 UTC, MohamadJaara approved these changes

2024-10-08 16:27 UTC, saleniuk approved these changes
🏅

2024-10-10 09:51 UTC, merged