chore: Update app version name #WPB-11429
wireapp/wire-android pull request #3489
Opened 2024-10-08 15:01 UTC by m-zagorski

# What's new in this PR?

Update app version name to contain only the version ie 4.9.0 without version code and flavor. This will simplify fdroid integration.

### Issues

There were issues with matching version name with tag for fdroid integration, thats why we're simplifying it.

### Solutions

Version names generated contain only raw version name, the UI representation is build exactly as it was before so `versionName-leastSignificantVersionCode-flavor`

### Testing

#### How to Test

Open the app and check in the settings that version name is in unchanged format ie `4.9.0-32599-beta` so `versionName-leastSignificantVersionCode-flavor`

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-10-08 15:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/wireapp/wire-android?pullRequest=3489) <br/>All committers have signed the CLA.

2024-10-08 16:30 UTC, saleniuk approved these changes

2024-10-09 14:23 UTC, MohamadJaara requested changes
there are 2 places that need to be changed updated to include the lest significant digits of the code and the build flavour
1. [the template for bug report](https://github.com/wireapp/wire-android/blob/52decf5ace84d1aad8f3fcb99c3e35decfb65e70/app/src/main/kotlin/com/wire/android/util/EmailComposer.kt#L53) 
2. [the debug screen](https://github.com/wireapp/wire-android/blob/79c6a031332da08edd5487bda1278bf07481beb0/app/src/main/kotlin/com/wire/android/ui/debug/DebugScreen.kt#L106)

2024-10-09 16:07 UTC, m-zagorski commented
> there are 2 places that need to be changed updated to include the lest significant digits of the code and the build flavour
> 
> 1. [the template for bug report](https://github.com/wireapp/wire-android/blob/52decf5ace84d1aad8f3fcb99c3e35decfb65e70/app/src/main/kotlin/com/wire/android/util/EmailComposer.kt#L53)
> 2. [the debug screen](https://github.com/wireapp/wire-android/blob/79c6a031332da08edd5487bda1278bf07481beb0/app/src/main/kotlin/com/wire/android/ui/debug/DebugScreen.kt#L106)

Indeed, my mistake. I've changed those places and also other ones which were using raw `BuildConfig.VERSION_NAME` to maintain consistency

2024-10-09 18:51 UTC, MohamadJaara approved these changes

2024-10-11 12:28 UTC, merged