fix: Change app versioning for fdroid #WPB-11429
wireapp/wire-android pull request #3501
Opened 2024-10-14 08:33 UTC by m-zagorski

----
#### PR Submission Checklist for internal contributors
[
- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----](https://wearezeta.atlassian.net/browse/WPB-11429)

# What's new in this PR?

### Issues

Change the version name again, now we had a clean version for each build but this messes up with testing

### Solutions

So the idea is to differentiate builds for fdroid with a flag `isFDroidRelease` - and create version name based on that flag.
Then in the app we check if version name contains something other than plain version (simple `-` check should be enough) - and we also add a flavor to our displayed name.

### Testing

#### How to Test

Builds for testing should be in a form `version-code` and in the app settings we should always see `version-code-flavor`

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-10-14 09:06 UTC, yamilmedina requested changes
Looking excellent 👌  one thing to keep in mind is that the `fdroid` builds that goes to the store, are automated by the `fdroid` team. To achieve this change, we also need to change this automation script they use.

https://github.com/wireapp/wire-android/blob/7091769addcadffd5478eede09e6612ab9dc4964/docker-agent/builder.sh#L33

2024-10-14 11:06 UTC, yamilmedina commented on build-logic/plugins/src/main/kotlin/AndroidApplicationConventionPlugin.kt
> +                val versionNameBasedOnFDroid = if (isFDroidRelease) {
```suggestion
                val resolvedProductVersionName = if (isFDroidRelease) {
```

```suggestion
                val resolvedVersionName = if (isFDroidRelease) {
```

I cannot think of a better name but, maybe something like those options would work for both cases, fdroid and not fdroid

2024-10-15 08:21 UTC, yamilmedina approved these changes

2024-10-15 09:08 UTC, Garzas approved these changes

2024-10-15 10:55 UTC, merged