feat: Create team upgrade flow (WPB-11268)
wireapp/wire-android pull request #3517
Opened 2024-10-16 12:02 UTC by ohassine

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Description

A follow up PR of https://github.com/wireapp/wire-android/pull/3497

This PR creates the flow that allow the user to migrate from personal to team account.

I created a new navGraph `PersonalToTeamMigrationNavGraph` so we can display all steps in it.
And for all the screens are using a sharedViewModel called `TeamMigrationViewModel`

This is just the UI part, no API calls involved here.

(That "open team flow" is just used to start the flow)

https://github.com/user-attachments/assets/61aec808-b4c1-4afe-8e42-ac032ef36798

Needs releases with:

- [ ] GitHub link to other pull request

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-10-22 07:01 UTC, damian-kaczmarek requested changes
Not all of comments are request to change, some are just me trying to understand code better

2024-10-22 07:01 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
> +@OptIn(ExperimentalLayoutApi::class)
For me the IDE says there is no experimental api used

2024-10-22 07:01 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/BulletList.kt
> +fun BulletListPreview() {
The dark theme got dark text 

![image](https://github.com/user-attachments/assets/218f611e-7f75-4974-848a-1ff1cccb7c5e)

2024-10-22 07:01 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationScreen.kt
> +}
Would be nice to add preview makes it easier to quickly know what code is responsible for.

2024-10-22 07:01 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step1/TeamMigrationTeamPlanStepScreen.kt
> +fun TeamMigrationTeamPlanStepScreenPreview() {
hmm in the preview dark theme got a black text, but it looks ok in the app. Same for other screens. Why is it different? Can we somehow make it work also for a preview?

2024-10-22 07:01 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step1/TeamMigrationTeamPlanStepScreen.kt
> +fun LearnMoreWirePlans(
Could be private. Same is true for previews and other inside functions. Make using IDEs autocomplete a little bit cleaner.

2024-10-22 07:01 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step3/TeamMigrationConfirmationStepScreen.kt
> +            passwordTextState.text.isNotEmpty() && agreedToMigrationTerms.value && acceptedWireTermsOfUse.value
Shouldn't we somehow indicate that agreements are necessary? ie red asterisk

2024-10-22 07:01 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step4/TeamMigrationDoneStepScreen.kt
> +fun TeamMigrationDoneStepContent(
I noticed that we tend to do a lot of such callbacks instead of passing needed objects. Is there a reason for it? Maybe there is a doc explaining why we use such approach? Or maybe it wasn't really discussed?

2024-10-22 07:01 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step2/TeamMigrationTeamNameStepScreen.kt
> +        val isContinueButtonEnabled = teamNameTextFieldState.text.isNotEmpty()
Is it only requirement to have at least one sign?

2024-10-22 09:59 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
> +@OptIn(ExperimentalLayoutApi::class)
Yes removing it... some leftover

2024-10-22 10:03 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/BulletList.kt
> +fun BulletListPreview() {
Fixing that, I need to wrap the preview in `WireTheme`.

2024-10-22 10:05 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step1/TeamMigrationTeamPlanStepScreen.kt
> +fun TeamMigrationTeamPlanStepScreenPreview() {
Same as the other one missing `WireTheme`

2024-10-22 10:07 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step3/TeamMigrationConfirmationStepScreen.kt
> +            passwordTextState.text.isNotEmpty() && agreedToMigrationTerms.value && acceptedWireTermsOfUse.value
Yes we do, continue button stays greyed out until the user accepts the terms

2024-10-22 10:09 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step4/TeamMigrationDoneStepScreen.kt
> +fun TeamMigrationDoneStepContent(
It's recommended to hoist states/args to higher level in the UI hierarchy. This makes Composables more reusable and easier to test.

2024-10-22 10:12 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step2/TeamMigrationTeamNameStepScreen.kt
> +        val isContinueButtonEnabled = teamNameTextFieldState.text.isNotEmpty()
We need the user to enter his team name to enable Continue button, so he can proceed to next step

2024-10-22 10:16 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationScreen.kt
> +}
Preview wouldn't be rendered here, because the Composable is having a `DestinationsNavHost`.

2024-10-22 13:09 UTC, damian-kaczmarek approved these changes
some comments but not really significant ✅

2024-10-22 13:09 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationScreen.kt
> +}
It is possible. Problem is `LocalActivity.current` but you can either surround it with if 
```kotlin
 val isRunInPreview = LocalInspectionMode.current
    if(!isRunInPreview){}
```
or extract Column to `TeamMigrationScreenContent`(which is probably nicer as the production code is not modified to fulfil preview requirements). You can pass `navigator = rememberNavigator { }`

2024-10-22 13:09 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step3/TeamMigrationConfirmationStepScreen.kt
> +            passwordTextState.text.isNotEmpty() && agreedToMigrationTerms.value && acceptedWireTermsOfUse.value
I mean from the user perspective they just see disabled button there is no indication that checkboxes are required. It is still discoverable but not directly indicated. Small thing not really important

2024-10-22 13:09 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step2/TeamMigrationTeamNameStepScreen.kt
> +        val isContinueButtonEnabled = teamNameTextFieldState.text.isNotEmpty()
Yeah I know, question was is it Ok to have a team named "-", from the API perspective. Because that what will be accepted by the form.

2024-10-22 13:10 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step4/TeamMigrationDoneStepScreen.kt
> +fun TeamMigrationDoneStepContent(
OK, I have added a topic for a collective to discuss this. https://wearezeta.atlassian.net/browse/WPB-11793

2024-10-23 06:42 UTC, MohamadJaara approved these changes
great work as always

2024-10-23 10:22 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step3/TeamMigrationConfirmationStepScreen.kt
> +            passwordTextState.text.isNotEmpty() && agreedToMigrationTerms.value && acceptedWireTermsOfUse.value
We can improve this later, if we receive many feedbacks about it

2024-10-23 10:24 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step2/TeamMigrationTeamNameStepScreen.kt
> +        val isContinueButtonEnabled = teamNameTextFieldState.text.isNotEmpty()
Yes for now we don't do the check.. it's good point tho

2024-10-23 11:42 UTC, merged