fix: black screen when last caller in a group #WPB-10652
wireapp/wire-android pull request #3550
Opened 2024-10-23 12:44 UTC by damian-kaczmarek

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-10652" title="WPB-10652" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-10652</a>  [Android] calling PiP mode
  </td></table>
  <br />
 

# What's new in this PR?

### Issues

Couldn't reproduce the original issue but was able to reproduce black screen in following scenario:
- call to a group from account A
- join to call with account B
- enable video on account A
- leave the call with account B
- user A was left with a black screen instead of their own camera preview

### Causes (Optional)

There was assumption that on list of participants first account is user currently logged it. Based on that `first()` was called. This was no longer true with picture in picture enabled as self participant was then removed.

### Solutions

Used currently logged in UserId and compared it to a participant to decide if given call tile is selfUser. 

### Testing

#### How to Test

- call to a group from account A
- join to call with account B
- enable video on account A
- leave the call with account B
- user A should see own preview video

### Attachments (Optional)
Before: 

https://github.com/user-attachments/assets/b3970943-b37a-43a1-951e-f387b9d549c1 

After:

https://github.com/user-attachments/assets/cff0179b-e4d7-4b67-98a9-641dd94bb339

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-10-23 13:24 UTC, ohassine requested changes
Good catch! but Picture in picture feature is not release yet. We can merge this one into develop and assign this ticket WPB-10652 instead to it. (WPB-11117 looks different this PR)

2024-10-30 11:03 UTC, Garzas approved these changes

2024-10-30 12:55 UTC, saleniuk approved these changes

2024-10-30 13:58 UTC, ohassine approved these changes

2024-11-06 15:15 UTC, merged