feat: filter conversation list [WPB-11638]
wireapp/wire-android pull request #3555
Opened 2024-10-25 07:26 UTC by Garzas

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

- renamed `MenuBottomSheetItem` arguments to leading and trailing
- added conversation filter button and bottom sheet
- added empty conversation list for each filter

2024-10-25 08:49 UTC, borichellow reviewed
Cool! Just a small wish to improve accessibility ;P

2024-10-25 08:49 UTC, borichellow commented on app/src/main/kotlin/com/wire/android/ui/home/conversationslist/filter/ConversationFilterSheetContent.kt
> +                        onItemClick = { onChangeFilter(filter) },
can you please add `onItemClickDescription = stringResource(R.string.content_description_select_label)`

2024-10-25 10:28 UTC, MohamadJaara approved these changes

2024-10-28 12:55 UTC, damian-kaczmarek requested changes
Only real issue for me is that I can't see those screen when using filters

2024-10-28 12:55 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/AllConversationsScreen.kt
> +@HomeNavGraph()
Unnecessary empty `()` here and some other places

2024-10-28 12:55 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/navigation/HomeDestination.kt
>  import com.wire.android.R
When I select the filter (e.g. fav or group) screen stays empty. I check and `emptyListContent` never gets triggered. In `ConversationsScreenContent` the lazyPagingItems contains 3 elements. All nulls (called  get on them)

![image](https://github.com/user-attachments/assets/3cb47a95-c92e-49c4-8a55-ae9559b98768)

2024-10-28 12:55 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/navigation/HomeDestination.kt
> +        HomeDestination.Archive,
It is not in the issue. But from consistent UX perspective, should we also have same "How to" for archive screen?

2024-10-28 12:55 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
> +    private val containsNewActivitiesSection = conversationsSource != ConversationsSource.ARCHIVE
This is true for now but can be dangerous if we add a new one. Any newly added type in enum will have this set to true. It will be hard to predict then that adding ConversationsSource can cause this. I would propose a more verbose but safer private function that will use `when` with explicit mention of each type. That way analyser will bring developer notice that they should decide if this should be true or false for a new type.

2024-10-28 12:55 UTC, damian-kaczmarek commented on app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/ConversationsEmptyContent.kt
> +        if (filter != ConversationFilter.FAVORITES) {
Can be else or guard pattern with `return@Column` after line 90 and remove if

2024-10-29 11:49 UTC, damian-kaczmarek approved these changes

2024-10-29 16:14 UTC, merged