federation: consider domain when checking if user is a guest
wireapp/wire-android pull request #3585
Opened 2021-11-09 09:33 UTC by ohassine

## What's new in this PR?

Now we are considering domain when checking if the user is a guest

2021-11-09 09:43 UTC, AndroidBob commented
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3585/1/)

2021-11-09 13:58 UTC, makingthematrix requested changes

2021-11-09 13:58 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/model/UserData.scala
> +  def isGuest(ourTeamId: TeamId, ourDomain: Domain = Domain.Empty): Boolean = isGuest(Some(ourTeamId), Some(ourDomain))
I think using `Option[Domain]` makes the code unnecessarily complicated.
You can always use `Domain.Empty` as default. So, for example, it's safe to use `inject[Signal[Domain]]` even on a private account - in that case you will get a constant signal with the value `Domain.Empty`.

And then you can just compare domain directly: 
```
ourTeamId.isDefined && (teamId != ourTeamId || domain != ourDomain)
```

2021-11-09 13:58 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/model/UserData.scala
> +  def isGuest(ourTeamId: Option[TeamId], ourDomain: Option[Domain]): Boolean = {
So it means this method probably shouldn't be necessary. Try to use the above one instead of this one everywhere.

2021-11-09 15:28 UTC, ohassine commented on zmessaging/src/main/scala/com/waz/model/UserData.scala
> +  def isGuest(ourTeamId: TeamId, ourDomain: Domain = Domain.Empty): Boolean = isGuest(Some(ourTeamId), Some(ourDomain))
Got it

2021-11-09 15:37 UTC, AndroidBob commented
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3585/2/)

2021-11-10 08:00 UTC, makingthematrix approved these changes

2021-11-10 08:36 UTC, AndroidBob commented
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3585/3/)

2021-11-10 09:27 UTC, merged