federation: consider domain when checking if user is in the team
wireapp/wire-android pull request #3586
Opened 2021-11-09 10:57 UTC by ohassine

## What's new in this PR?

Now we are considering domain when checking if the user is in the team

2021-11-09 11:11 UTC, AndroidBob commented
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3586/1/)

2021-11-09 11:32 UTC, AndroidBob commented
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3586/2/)

2021-11-09 11:35 UTC, AndroidBob commented
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3586/3/)

2021-11-09 15:53 UTC, AndroidBob commented
Build Failure
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3586/4/)

2021-11-09 16:07 UTC, AndroidBob commented
Build Success
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3586/5/)

2021-11-09 16:18 UTC, AndroidBob commented
Build Success
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3586/6/)

2021-11-10 08:33 UTC, makingthematrix requested changes

2021-11-10 08:33 UTC, makingthematrix commented on app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
> +      chathead.setUserData(userData, userData.isInTeam(teamId, domain))
this could be a one-liner ;)

2021-11-10 08:33 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
> +                            domain:               Domain,
Please rebase this PR on top of the one about `isGuest` so you won't have to make the same changes twice.

2021-11-10 09:46 UTC, ohassine commented on app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
> +      chathead.setUserData(userData, userData.isInTeam(teamId, domain))
It's used twice for `isGuest` and `isInTeam`

2021-11-10 09:52 UTC, AndroidBob commented
Build Success
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3586/7/)

2021-11-10 10:55 UTC, AndroidBob commented
Build Success
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3586/8/)

2021-11-10 11:34 UTC, makingthematrix approved these changes

2021-11-10 11:45 UTC, merged