federation: consider domain when checking if the user is a external
wireapp/wire-android pull request #3587
Opened 2021-11-09 16:14 UTC by ohassine

## What's new in this PR?

Now we are considering domain when checking if the user is external

2021-11-09 16:24 UTC, AndroidBob commented
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3587/1/)

2021-11-10 08:35 UTC, makingthematrix requested changes

2021-11-10 08:35 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
> +                            domain:               Domain,
Same as with the other one - please rebase the PRs on top of one another to avoid duplicated changes.

2021-11-10 10:25 UTC, AndroidBob commented
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3587/2/)

2021-11-10 10:55 UTC, AndroidBob commented
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3587/3/)

2021-11-10 11:53 UTC, makingthematrix approved these changes

2021-11-10 11:59 UTC, AndroidBob commented
Build Success
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3587/4/)

2021-11-10 12:14 UTC, AndroidBob commented
Build Success
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3587/5/)

2021-11-10 12:53 UTC, merged