feat: connect to upgrade-personal-to-team API #WPB-11992
wireapp/wire-android pull request #3625
Opened 2024-11-13 15:41 UTC by damian-kaczmarek

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-11992" title="WPB-11992" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-11992</a>  [Android] Team creation for personal user - connect to the API - /upgrade-personal-to-team
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Adds calls to the API when migrating from personal to team account.

Needs releases with:

- https://github.com/wireapp/kalium/pull/3103

### Testing

#### Test Coverage (Optional)

Work in progress

- [ ] I have added automated test to this contribution

#### How to Test

To test you need to switch to anta 
https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/300351887/Testing+environments+for+federation#anta

The html with deeplinks switching can be downloaded here. You must logout first before switching. https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/300351887/Testing+environments+for+federation#anta

To get signup code you must read the email from [inbucket](https://inbucket.anta.wire.link/monitor). 
Password is on [1password](https://start.1password.com/open/i?a=FOQLGGWZU5EQXEJO3V3A5HI3DU&v=nqjxjxdabagisaqjlyfym4kye4&i=gprcgudpieokefbatxqlxctu2m&h=wire.1password.eu).

Then:
- create personal account
- go to you profile page, at the top you will see migration banner
- go through the process
- at the you should see success screen
- currently you will only see changes to your account after app restart, WIP: https://wearezeta.atlassian.net/browse/WPB-12187

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-11-20 09:39 UTC, ohassine requested changes

2024-11-20 09:39 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
> +    private val teamMigrationUseCase: MigrateFromPersonalToTeamUseCase
I'd suggest to use action oriented names as it's more clear.
`teamMigrationUseCase` does not provide an immediate understanding of what the use case is actually doing.
```suggestion
    private val migrateFromPersonalToTeam: MigrateFromPersonalToTeamUseCase
```

2024-11-20 09:39 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
> +    fun postTeamMigration(onSuccess: () -> Unit) {
The name is still generic one, team migration can be many things.
Maybe we should be more specific, something like : `migrateFromPersonalToTeamAccount`() ?

2024-11-20 09:39 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
> +    }
Can we cover it with unit test ?

2024-11-21 14:43 UTC, ohassine approved these changes

2024-11-21 16:08 UTC, yamilmedina approved these changes

2024-11-21 17:04 UTC, merged