feat(federation): add support for federated video calls  #FS-138
wireapp/wire-android pull request #3641
Opened 2022-01-12 08:15 UTC by ohassine

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-01-12 10:20 UTC, AndroidBob commented
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3641/1/)

2022-01-12 11:08 UTC, AndroidBob commented
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3641/2/)

2022-01-12 11:22 UTC, AndroidBob commented
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3641/3/)

2022-01-12 17:26 UTC, makingthematrix requested changes

2022-01-12 17:26 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/call/Avs.scala
> +          val domain  = DomainUtils.getDomainFromString(convId)
We need to parse the domain only if the federation flag is on.
Hmm, I can see now why `DomainUtils` might be useful as a common part for both `QualifiedId` and `RConvQualifiedId`. But if we keep it then it would be good to use the same methods in both those classes so we won't duplicate the logic.

2022-01-12 17:26 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/call/Avs.scala
> +    val conversationIdWithDomain = s"${convId.str}@${convDomain.str}"
Yup, it would be great to have all this joining and splitting of ids in one place.

2022-01-12 17:26 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
> +                         val domain:          Domain = Domain.Empty,
You don't need to provide the default value for the domain here. The dependency injection framework will take care of it.

2022-01-12 17:26 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
> +          QualifiedId(UserId(userIdString), domainString) -> clientIds.map(ClientId(_))
... and there should be a method that turns the string `userId` to QualifiedId :)

2022-01-12 17:26 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
> +                  avs.startCall(w, RConvId(convIdWithDomain), callType, convType, useConstantBitRate).map {
RConvId with a domain - consider RConvQualifiedId

2022-01-12 17:26 UTC, makingthematrix commented on zmessaging/src/main/scala/com/waz/service/call/DomainUtils.scala
> +    if(BuildConfig.FEDERATION_USER_DISCOVERY)
The `if` should also check if the domain is not empty. If it is, we should go with `else`. Otherwise we will get the invalid form `[userId]@`.

2022-01-13 09:27 UTC, ohassine commented on zmessaging/src/main/scala/com/waz/service/call/Avs.scala
> +          val domain  = DomainUtils.getDomainFromString(convId)
yes the check of Federation is done inside `getDomainFromString()`

2022-01-13 13:38 UTC, AndroidBob commented
Build Failure
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3641/4/)

2022-01-13 14:39 UTC, AndroidBob commented
Build Failure
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3641/6/)

2022-01-13 15:49 UTC, AndroidBob commented
Build Failure
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3641/7/)

2022-01-13 16:04 UTC, AndroidBob commented
Build Failure
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3641/8/)

2022-01-13 16:09 UTC, AndroidBob commented
Build Failure
ID:9
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3641/9/)

2022-01-13 16:43 UTC, AndroidBob commented
Build Failure
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3641/10/)

2022-01-13 16:56 UTC, AndroidBob commented
Build Failure
ID:11
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3641/11/)

2022-01-13 17:13 UTC, AndroidBob commented
Build Failure
ID:12
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3641/12/)

2022-01-13 17:36 UTC, AndroidBob commented
Build Success
ID:13
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3641/13/)

2022-01-14 09:25 UTC, makingthematrix approved these changes

2022-01-14 09:33 UTC, merged