feat: Deleted users adjustments [WPB-1655]
wireapp/wire-android pull request #3704
Opened 2024-12-03 13:41 UTC by m-zagorski

https://wearezeta.atlassian.net/browse/WPB-1655

# What's new in this PR?

### Issues

We were able to perform actions on deleted users, block them, change notifications, send invitation.

### Solutions

Use `blocked` flag to hide those actions

#### How to Test

- Delete user
- Check if you can open his profile - you shouldnt
- Check if longtapping on conversation gives the option. to change notifications and blocking - you shouldnt 
- Search for non deleted user, open its profile, then delete the user
- Options to invite, blockm and change notifications should also not be present

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-12-03 13:53 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
> +    }
Can we cover it with it unit test ?

2024-12-03 15:22 UTC, m-zagorski commented on app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
> +    }
done

2024-12-03 15:49 UTC, yamilmedina approved these changes

2024-12-04 13:34 UTC, MohamadJaara approved these changes

2024-12-04 16:57 UTC, MohamadJaara requested changes, later dismissed
lets move this change to the next release 4.11

2024-12-13 09:15 UTC, borichellow approved these changes

2024-12-13 11:43 UTC, merged