chore: hash device id
wireapp/wire-android pull request #973
Opened 2022-09-13 13:57 UTC by tmspzz

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-09-13 14:18 UTC, ohassine approved these changes

2022-09-13 14:18 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/WireApplication.kt
> +        if (android.os.Build.VERSION.SDK_INT >= 26) {
We can use `Build.VERSION_CODES.O` instead a magic number

2022-09-13 14:19 UTC, MohamadJaara commented on app/src/main/kotlin/com/wire/android/WireApplication.kt
> +            Datadog.setUserInfo(id = getDeviceId(this)?.sha256())
we need to change getDeviceId to read the device id only for 26+
and the app is still reading the device id in other places  like `WireApplication`

2022-09-13 14:19 UTC, MohamadJaara requested changes
the app is still reading the device id in other places like WireApplication

2022-09-13 14:28 UTC, MohamadJaara approved these changes
LGTM

2022-09-13 14:34 UTC, AndroidBob commented
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-973/4/) **failed**.

2022-09-13 15:36 UTC, AndroidBob commented
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-973/5/) **failed**.

2022-09-13 16:51 UTC, AndroidBob commented
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-973/6/) **failed**.

2022-09-14 12:10 UTC, AndroidBob commented
Build [10](https://10.10.124.134/job/wire-android-reloaded/job/PR-973/10/) **failed**.

2022-09-14 12:51 UTC, AndroidBob commented
Build [13](https://10.10.124.134/job/wire-android-reloaded/job/PR-973/13/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4419229)(4419229)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4419229)(4419229)-dev-release.apk)

2022-09-14 13:16 UTC, merged